In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
# Define the folder path and the column names
# '/Users/jul/Desktop/uni/Data Analytics/project/PROBE-202411'
# /Users/jul/Desktop/uni/Data Analytics/PROBE-202409
# '/Users/jul/Desktop/uni/Data Analytics/PROBE-202412'
folder_paths = [
    '/Users/jul/Desktop/uni/Data Analytics/PROBE-202412'
]
columns = [
    'VehicleID',
    'gpsvalid',
    'lat',
    'lon',
    'timestamp',
    'speed',
    'heading',
    'for_hire_light',
    'engine_acc'
]

In [3]:
# Initialize an empty list to store the dataframes
all_dfs = []

In [4]:

# Loop through all folders
for folder_path in folder_paths:
    # Loop through all files in the directory
    for filename in os.listdir(folder_path):
        # Check if the file is a CSV file
        if filename.endswith('.csv.out'):
            file_path = os.path.join(folder_path, filename)

            # Read the CSV file into a dataframe with the specified column names
            df = pd.read_csv(file_path, names=columns)

            # Append the dataframe to the list
            all_dfs.append(df)

# Concatenate all dataframes in the list into a single dataframe
combined_df = pd.concat(all_dfs, ignore_index=True)

In [5]:
combined_df

,VehicleID,gpsvalid,lat,lon,timestamp,speed,heading,for_hire_light,engine_acc
0,V8F0cK98HyTMrcSdeR47rexj0rw,1,13.73413,100.68927,2024-12-21 23:55:57,107,96,0,1
1,r8yh9EoluJ0u53F81KhXcZ8V6VQ,1,13.68293,100.46149,2024-12-21 23:56:41,0,348,0,0
2,fhAmmgsL3IogEfBatvNCwSLr04A,1,13.65472,100.30120,2024-12-21 23:57:46,0,1,0,0
3,Cggse+7450jI5U3HLEOfhoBCOGk,1,13.86938,100.46595,2024-12-21 23:57:50,0,110,0,0
4,gLq3BOZ8ggjCHmjhqWAQ7ZyVBlg,1,13.77983,100.39398,2024-12-21 23:58:03,0,302,0,0
...,...,...,...,...,...,...,...,...,...
59432987,YKvdFXsrD9SJiakUQEpwxEOaK1Q,1,13.86524,100.58894,2024-12-27 23:59:10,0,273,0,0
59432988,wsK20gYyyNpTfG3s/1IuVbg32WA,1,7.89154,98.38982,2024-12-27 23:59:10,35,352,0,1
59432989,s+FMc1WPBo2oVF06gx27GDr29G8,1,7.84152,98.30315,2024-12-27 23:59:10,0,177,0,0
59432990,FWfSz92y9h30nkpZ/xUTTwLPgkE,1,13.78749,100.64972,2024-12-27 23:59:10,59,33,0,1
59432991,adIwxxrEgUTuEKQLzwXlLjsi1Kc,1,13.66076,99.52271,2024-12-27 23:59:09,0,29,0,0

In [6]:
cleaned_df = combined_df.dropna()

In [7]:
cleaned_taxi_df = cleaned_df[
    (combined_df['gpsvalid'] == 1) &
    (combined_df['engine_acc'] == 1) &
    (combined_df['lat'].between(-90, 90)) &
    (combined_df['lon'].between(-180, 180)) &
    (combined_df['speed'] >= 0)
].copy().reset_index(drop=True)

In [8]:
# Find the unique VehicleIDs of every vehicle that EVER reported for_hire_light = 1
# This is our most reliable definition of a taxi.
taxi_ids = cleaned_taxi_df[cleaned_taxi_df['for_hire_light'] == 1]['VehicleID'].unique()

In [9]:
# Now, filter the main dataframe to keep ALL records for these identified taxis
# This gives us their full journey, not just when their light was on.
taxis_df = cleaned_taxi_df[cleaned_taxi_df['VehicleID'].isin(taxi_ids)].copy()

In [10]:
# The 'timestamp' column is just text right now. We need to convert it.
taxis_df['timestamp'] = pd.to_datetime(taxis_df['timestamp'])

Sort Data

In [11]:
# Sort by the vehicle first, then by the time.
taxis_df.sort_values(by=['VehicleID', 'timestamp'], inplace=True)

In [12]:
# Reset the index after sorting for a clean DataFrame
taxis_df.reset_index(drop=True, inplace=True)

In [13]:
# Extract time-based features from the timestamp
taxis_df['hour'] = taxis_df['timestamp'].dt.hour
taxis_df['day_of_week'] = taxis_df['timestamp'].dt.dayofweek # Monday=0, Sunday=6
taxis_df['is_weekend'] = (taxis_df['day_of_week'] >= 5).astype(int)

In [14]:
# --- Advanced: Identify Trips ---
# A trip starts when the 'for_hire_light' changes from 1 (empty) to 0 (occupied).
# We can create a 'trip_id' for each taxi.

# First, detect the change from 1 to 0
taxis_df['trip_start'] = (taxis_df['for_hire_light'].shift(1) == 1) & (taxis_df['for_hire_light'] == 0)

In [15]:
# We also need to ensure it's the same vehicle
taxis_df['trip_start'] = taxis_df['trip_start'] & (taxis_df['VehicleID'].shift(1) == taxis_df['VehicleID'])

In [16]:
# Now create a unique ID for each trip using a cumulative sum
taxis_df['trip_id'] = taxis_df.groupby('VehicleID')['trip_start'].cumsum()

In [17]:
# Let's clean up the intermediate column
taxis_df.drop(columns=['trip_start'], inplace=True)

In [18]:
taxis_df

,VehicleID,gpsvalid,lat,lon,timestamp,speed,heading,for_hire_light,engine_acc,hour,day_of_week,is_weekend,trip_id
0,++qQzutWwL31NcUo8s0jiGZzzS0,1,13.64478,100.63768,2024-12-02 08:34:52,0,100,1,1,8,0,0,0
1,++qQzutWwL31NcUo8s0jiGZzzS0,1,13.64478,100.63768,2024-12-02 08:36:52,0,100,1,1,8,0,0,0
2,++qQzutWwL31NcUo8s0jiGZzzS0,1,13.64490,100.63728,2024-12-02 08:38:52,11,219,1,1,8,0,0,0
3,++qQzutWwL31NcUo8s0jiGZzzS0,1,13.64066,100.63463,2024-12-02 08:39:52,0,210,1,1,8,0,0,0
4,++qQzutWwL31NcUo8s0jiGZzzS0,1,13.64285,100.63578,2024-12-02 08:42:52,12,25,1,1,8,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
17048599,zzLYPcDONaA8lLF2aJYFKnoRDQ4,1,13.93001,100.49104,2024-12-31 21:51:50,48,44,1,1,21,1,0,0
17048600,zzLYPcDONaA8lLF2aJYFKnoRDQ4,1,13.93532,100.49610,2024-12-31 21:52:50,45,32,1,1,21,1,0,0
17048601,zzLYPcDONaA8lLF2aJYFKnoRDQ4,1,13.94625,100.49688,2024-12-31 21:56:52,6,206,1,1,21,1,0,0
17048602,zzLYPcDONaA8lLF2aJYFKnoRDQ4,1,13.94636,100.49665,2024-12-31 21:58:51,0,206,1,1,21,1,0,0
17048603,zzLYPcDONaA8lLF2aJYFKnoRDQ4,1,13.94636,100.49665,2024-12-31 22:00:52,0,206,1,1,22,1,0,0

In [19]:
# cars with trip id
taxis_df.groupby('VehicleID')["trip_id"].nunique()

VehicleID
++qQzutWwL31NcUo8s0jiGZzzS0      1
+1indEOKr/ikPVrJQTVjw4FGxBE      1
+20prWr63K5svsMtTmdqLnmsTGE    287
+A3arvBS15eOvdHE+E06+Ng28+E    145
+BAgYWCbvz0z377ef3Yp687Pp+0    458
                              ...
zt6r6X6cjBVDqWxKcbyXkn1Cydw    472
zvkvMBxj2VDpNjIfmifwwxl6nMo     79
zwNAI8pHuCgPOF5NMs2nVaXBG04    218
zyy0Hv5yMoClNPQlx1tR4NBssFI      1
zzLYPcDONaA8lLF2aJYFKnoRDQ4      1
Name: trip_id, Length: 2099, dtype: int64

In [20]:
#how many taxis extracted
taxis_df['VehicleID'].nunique()

2099

In [21]:
#how many trips extracted
taxis_df.groupby('VehicleID')['trip_id'].max().sum()

np.int64(458878)

Calculate Idle Time

In [22]:
# It creates the unique ID for each continuous idle period.
taxis_df['idle_start'] = (taxis_df['for_hire_light'].shift(1) == 0) & \
                         (taxis_df['for_hire_light'] == 1) & \
                         (taxis_df['VehicleID'].shift(1) == taxis_df['VehicleID'])
taxis_df['idle_period_id'] = taxis_df.groupby('VehicleID')['idle_start'].cumsum()
taxis_df.loc[taxis_df['trip_id'] == 0, 'idle_period_id'] = 0

In [23]:
# Create a temporary DataFrame with only the idle data points
idle_periods_df = taxis_df[taxis_df['for_hire_light'] == 1].copy()

# Group by each unique idle period to calculate its duration
idle_summary = idle_periods_df.groupby(['VehicleID', 'idle_period_id']).agg(
    start_time=('timestamp', 'min'),
    end_time=('timestamp', 'max')
).reset_index()

# Calculate the duration in minutes
idle_summary['idle_duration_minutes'] = (idle_summary['end_time'] - idle_summary['start_time']).dt.total_seconds() / 60 + 1

print("--- This is the information we will merge back ---")
display(idle_summary[['VehicleID', 'idle_period_id', 'idle_duration_minutes']].head())

--- This is the information we will merge back ---

                     VehicleID  idle_period_id  idle_duration_minutes
0  ++qQzutWwL31NcUo8s0jiGZzzS0               0           37340.483333
1  +1indEOKr/ikPVrJQTVjw4FGxBE               0           44041.950000
2  +20prWr63K5svsMtTmdqLnmsTGE               0              34.000000
3  +20prWr63K5svsMtTmdqLnmsTGE               2              28.000000
4  +20prWr63K5svsMtTmdqLnmsTGE               3              11.783333

In [24]:
# We use a 'left' merge to ensure we keep ALL original rows from taxis_df
# The merge will add the 'idle_duration_minutes' from the summary to the main table
# based on the matching VehicleID and idle_period_id.
taxis_df = pd.merge(
    taxis_df,
    idle_summary[['VehicleID', 'idle_period_id', 'idle_duration_minutes']],
    on=['VehicleID', 'idle_period_id'],
    how='left'
)

# After merging, the rows that were NOT idle (i.e., part of a trip) will have NaN
# for the idle duration. We should fill these with 0.
taxis_df['idle_duration_minutes'].fillna(0, inplace=True)

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1755066191.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  taxis_df['idle_duration_minutes'].fillna(0, inplace=True)

In [25]:
taxis_df.drop(columns=['idle_start'], inplace=True)

In [26]:
taxis_df

,VehicleID,gpsvalid,lat,lon,timestamp,speed,heading,for_hire_light,engine_acc,hour,day_of_week,is_weekend,trip_id,idle_period_id,idle_duration_minutes
0,++qQzutWwL31NcUo8s0jiGZzzS0,1,13.64478,100.63768,2024-12-02 08:34:52,0,100,1,1,8,0,0,0,0,37340.483333
1,++qQzutWwL31NcUo8s0jiGZzzS0,1,13.64478,100.63768,2024-12-02 08:36:52,0,100,1,1,8,0,0,0,0,37340.483333
2,++qQzutWwL31NcUo8s0jiGZzzS0,1,13.64490,100.63728,2024-12-02 08:38:52,11,219,1,1,8,0,0,0,0,37340.483333
3,++qQzutWwL31NcUo8s0jiGZzzS0,1,13.64066,100.63463,2024-12-02 08:39:52,0,210,1,1,8,0,0,0,0,37340.483333
4,++qQzutWwL31NcUo8s0jiGZzzS0,1,13.64285,100.63578,2024-12-02 08:42:52,12,25,1,1,8,0,0,0,0,37340.483333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17048599,zzLYPcDONaA8lLF2aJYFKnoRDQ4,1,13.93001,100.49104,2024-12-31 21:51:50,48,44,1,1,21,1,0,0,0,44099.000000
17048600,zzLYPcDONaA8lLF2aJYFKnoRDQ4,1,13.93532,100.49610,2024-12-31 21:52:50,45,32,1,1,21,1,0,0,0,44099.000000
17048601,zzLYPcDONaA8lLF2aJYFKnoRDQ4,1,13.94625,100.49688,2024-12-31 21:56:52,6,206,1,1,21,1,0,0,0,44099.000000
17048602,zzLYPcDONaA8lLF2aJYFKnoRDQ4,1,13.94636,100.49665,2024-12-31 21:58:51,0,206,1,1,21,1,0,0,0,44099.000000
17048603,zzLYPcDONaA8lLF2aJYFKnoRDQ4,1,13.94636,100.49665,2024-12-31 22:00:52,0,206,1,1,22,1,0,0,0,44099.000000

Filter out irrelavant date and time

In [27]:
unique_years = taxis_df['timestamp'].dt.year.unique()
unique_years.sort()
unique_years

array([1970, 2024], dtype=int32)

In [28]:
# filter out years more than 2024 and less than 2015
year_series = taxis_df['timestamp'].dt.year

# Keep only the rows where the year is between 2016 and 2024 (inclusive)
# "later than 2015" means >= 2016
# "drop further than 2024" means <= 2024

taxis_df = taxis_df[(year_series == 2024)].copy()

In [29]:
taxis_df

,VehicleID,gpsvalid,lat,lon,timestamp,speed,heading,for_hire_light,engine_acc,hour,day_of_week,is_weekend,trip_id,idle_period_id,idle_duration_minutes
0,++qQzutWwL31NcUo8s0jiGZzzS0,1,13.64478,100.63768,2024-12-02 08:34:52,0,100,1,1,8,0,0,0,0,37340.483333
1,++qQzutWwL31NcUo8s0jiGZzzS0,1,13.64478,100.63768,2024-12-02 08:36:52,0,100,1,1,8,0,0,0,0,37340.483333
2,++qQzutWwL31NcUo8s0jiGZzzS0,1,13.64490,100.63728,2024-12-02 08:38:52,11,219,1,1,8,0,0,0,0,37340.483333
3,++qQzutWwL31NcUo8s0jiGZzzS0,1,13.64066,100.63463,2024-12-02 08:39:52,0,210,1,1,8,0,0,0,0,37340.483333
4,++qQzutWwL31NcUo8s0jiGZzzS0,1,13.64285,100.63578,2024-12-02 08:42:52,12,25,1,1,8,0,0,0,0,37340.483333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17048599,zzLYPcDONaA8lLF2aJYFKnoRDQ4,1,13.93001,100.49104,2024-12-31 21:51:50,48,44,1,1,21,1,0,0,0,44099.000000
17048600,zzLYPcDONaA8lLF2aJYFKnoRDQ4,1,13.93532,100.49610,2024-12-31 21:52:50,45,32,1,1,21,1,0,0,0,44099.000000
17048601,zzLYPcDONaA8lLF2aJYFKnoRDQ4,1,13.94625,100.49688,2024-12-31 21:56:52,6,206,1,1,21,1,0,0,0,44099.000000
17048602,zzLYPcDONaA8lLF2aJYFKnoRDQ4,1,13.94636,100.49665,2024-12-31 21:58:51,0,206,1,1,21,1,0,0,0,44099.000000
17048603,zzLYPcDONaA8lLF2aJYFKnoRDQ4,1,13.94636,100.49665,2024-12-31 22:00:52,0,206,1,1,22,1,0,0,0,44099.000000

In [30]:
taxis_df.groupby('trip_id')["VehicleID"].nunique()

trip_id
0      2099
1      1570
2      1533
3      1513
4      1494
       ...
913       1
914       1
915       1
916       1
917       1
Name: VehicleID, Length: 918, dtype: int64

Filter to Just BMR Bangkok

In [31]:
#Define Regions
BKK_REGION_BOUNDS = {
    'min_lat': 13.4,
    'max_lat': 14.2,
    'min_lon': 99.9,
    'max_lon': 101.3
}

In [32]:
taxis_df_bkk = taxis_df[
    (taxis_df['lat'] >= BKK_REGION_BOUNDS['min_lat']) &
    (taxis_df['lat'] <= BKK_REGION_BOUNDS['max_lat']) &
    (taxis_df['lon'] >= BKK_REGION_BOUNDS['min_lon']) &
    (taxis_df['lon'] <= BKK_REGION_BOUNDS['max_lon'])
].copy()

In [33]:
taxis_df_bkk

,VehicleID,gpsvalid,lat,lon,timestamp,speed,heading,for_hire_light,engine_acc,hour,day_of_week,is_weekend,trip_id,idle_period_id,idle_duration_minutes
0,++qQzutWwL31NcUo8s0jiGZzzS0,1,13.64478,100.63768,2024-12-02 08:34:52,0,100,1,1,8,0,0,0,0,37340.483333
1,++qQzutWwL31NcUo8s0jiGZzzS0,1,13.64478,100.63768,2024-12-02 08:36:52,0,100,1,1,8,0,0,0,0,37340.483333
2,++qQzutWwL31NcUo8s0jiGZzzS0,1,13.64490,100.63728,2024-12-02 08:38:52,11,219,1,1,8,0,0,0,0,37340.483333
3,++qQzutWwL31NcUo8s0jiGZzzS0,1,13.64066,100.63463,2024-12-02 08:39:52,0,210,1,1,8,0,0,0,0,37340.483333
4,++qQzutWwL31NcUo8s0jiGZzzS0,1,13.64285,100.63578,2024-12-02 08:42:52,12,25,1,1,8,0,0,0,0,37340.483333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17048599,zzLYPcDONaA8lLF2aJYFKnoRDQ4,1,13.93001,100.49104,2024-12-31 21:51:50,48,44,1,1,21,1,0,0,0,44099.000000
17048600,zzLYPcDONaA8lLF2aJYFKnoRDQ4,1,13.93532,100.49610,2024-12-31 21:52:50,45,32,1,1,21,1,0,0,0,44099.000000
17048601,zzLYPcDONaA8lLF2aJYFKnoRDQ4,1,13.94625,100.49688,2024-12-31 21:56:52,6,206,1,1,21,1,0,0,0,44099.000000
17048602,zzLYPcDONaA8lLF2aJYFKnoRDQ4,1,13.94636,100.49665,2024-12-31 21:58:51,0,206,1,1,21,1,0,0,0,44099.000000
17048603,zzLYPcDONaA8lLF2aJYFKnoRDQ4,1,13.94636,100.49665,2024-12-31 22:00:52,0,206,1,1,22,1,0,0,0,44099.000000

In [34]:
#filter speed
taxis_df_bkk = taxis_df_bkk[taxis_df_bkk['speed'] <= 180].copy()

In [35]:
taxis_df_bkk

,VehicleID,gpsvalid,lat,lon,timestamp,speed,heading,for_hire_light,engine_acc,hour,day_of_week,is_weekend,trip_id,idle_period_id,idle_duration_minutes
0,++qQzutWwL31NcUo8s0jiGZzzS0,1,13.64478,100.63768,2024-12-02 08:34:52,0,100,1,1,8,0,0,0,0,37340.483333
1,++qQzutWwL31NcUo8s0jiGZzzS0,1,13.64478,100.63768,2024-12-02 08:36:52,0,100,1,1,8,0,0,0,0,37340.483333
2,++qQzutWwL31NcUo8s0jiGZzzS0,1,13.64490,100.63728,2024-12-02 08:38:52,11,219,1,1,8,0,0,0,0,37340.483333
3,++qQzutWwL31NcUo8s0jiGZzzS0,1,13.64066,100.63463,2024-12-02 08:39:52,0,210,1,1,8,0,0,0,0,37340.483333
4,++qQzutWwL31NcUo8s0jiGZzzS0,1,13.64285,100.63578,2024-12-02 08:42:52,12,25,1,1,8,0,0,0,0,37340.483333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17048599,zzLYPcDONaA8lLF2aJYFKnoRDQ4,1,13.93001,100.49104,2024-12-31 21:51:50,48,44,1,1,21,1,0,0,0,44099.000000
17048600,zzLYPcDONaA8lLF2aJYFKnoRDQ4,1,13.93532,100.49610,2024-12-31 21:52:50,45,32,1,1,21,1,0,0,0,44099.000000
17048601,zzLYPcDONaA8lLF2aJYFKnoRDQ4,1,13.94625,100.49688,2024-12-31 21:56:52,6,206,1,1,21,1,0,0,0,44099.000000
17048602,zzLYPcDONaA8lLF2aJYFKnoRDQ4,1,13.94636,100.49665,2024-12-31 21:58:51,0,206,1,1,21,1,0,0,0,44099.000000
17048603,zzLYPcDONaA8lLF2aJYFKnoRDQ4,1,13.94636,100.49665,2024-12-31 22:00:52,0,206,1,1,22,1,0,0,0,44099.000000

In [36]:
#how many taxis extracted
taxis_df_bkk['VehicleID'].nunique()

2021

In [37]:
taxis_df_bkk.groupby('VehicleID')['trip_id'].max().sum()

np.int64(457471)

In [38]:
taxis_df_bkk.columns

Index(['VehicleID', 'gpsvalid', 'lat', 'lon', 'timestamp', 'speed', 'heading',
       'for_hire_light', 'engine_acc', 'hour', 'day_of_week', 'is_weekend',
       'trip_id', 'idle_period_id', 'idle_duration_minutes'],
      dtype='object')

In [39]:
# Save as CSV
taxis_df_bkk.to_csv("cleaned_taxis_11_2024.csv", index=False)

In [40]:
# Example: read data and compute fare
df = pd.read_csv('cleaned_taxis_11_2024.csv')

# Ensure timestamp is in datetime format and sort the data
df['timestamp'] = pd.to_datetime(df['timestamp'])
# We must sort by VehicleID first, then trip_id, then timestamp
df = df.sort_values(by=['VehicleID', 'trip_id', 'timestamp'])

In [41]:
def haversine_distance(lon1, lat1, lon2, lat2):
    """
    Calculate the great circle distance in kilometers between two points
    on the earth (specified in decimal degrees).
    """
    lon1, lat1, lon2, lat2 = map(np.radians, [lon1, lat1, lon2, lat2])
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    a = np.sin(dlat/2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2)**2
    c = 2 * np.arcsin(np.sqrt(a))
    r = 6371 # Radius of earth in kilometers.
    return c * r

In [42]:
# --- Part 1: Calculate distance between each point (same as before) ---
df['lat_next'] = df.groupby(['VehicleID', 'trip_id'])['lat'].shift(-1)
df['lon_next'] = df.groupby(['VehicleID', 'trip_id'])['lon'].shift(-1)

# This column is the distance between one point and the next, not the total
df['segment_distance_km'] = haversine_distance(df['lon'], df['lat'], df['lon_next'], df['lat_next'])

# --- Part 2: Calculate the TOTAL distance for the whole trip (same as before) ---
# This creates a summary table with one row per trip and its total distance
trip_distances = df.groupby(['VehicleID', 'trip_id'])['segment_distance_km'].sum().reset_index()
trip_distances.rename(columns={'segment_distance_km': 'total_trip_distance_km'}, inplace=True)


# --- Part 3: Merge the total trip distance back to the main dataframe ---
# This is the new step you were looking for.
df = pd.merge(df, trip_distances, on=['VehicleID', 'trip_id'], how='left')

#drop all rows that has trip distance that more than 300 km
df = df[df['total_trip_distance_km'] <= 300]

#drop all rows that has trip distance that equal to 0 km
df = df[df['total_trip_distance_km'] > 0]

In [43]:
def calculate_total_trip_fees(distance_km):
    """
    Calculates the taxi fare in THB based on the provided distance in kilometers,
    using the official Thai taxi rate structure.
    """
    # Handle cases with no or very small distance
    if distance_km <= 0:
        return 0

    # First 1 km
    fare = 35.0

    if distance_km > 1:
        # km >1 to 10
        d = min(distance_km, 10) - 1
        fare += d * 6.50

    if distance_km > 10:
        # km >10 to 20
        d = min(distance_km, 20) - 10
        fare += d * 7.00

    if distance_km > 20:
        # km >20 to 40
        d = min(distance_km, 40) - 20
        fare += d * 8.00

    if distance_km > 40:
        # km >40 to 60
        d = min(distance_km, 60) - 40
        fare += d * 8.50

    if distance_km > 60:
        # km >60 to 80
        d = min(distance_km, 80) - 60
        fare += d * 9.00

    if distance_km > 80:
        # km >80
        d = distance_km - 80
        fare += d * 10.50

    return fare

In [44]:
# (Assuming you have already defined the calculate_total_trip_fees function)
df['total_trip_fees'] = df['total_trip_distance_km'].apply(calculate_total_trip_fees)

In [45]:
# getting all important features
# --- We will group by each unique trip to calculate the new features ---
trip_groups = df.groupby(['VehicleID', 'trip_id'])

# --- 1. Calculate Trip Duration ---
# Get the start and end time for each trip
trip_start_time = trip_groups['timestamp'].min()
trip_end_time = trip_groups['timestamp'].max()

# Calculate duration in seconds and then minutes
duration_seconds = (trip_end_time - trip_start_time).dt.total_seconds()
duration_minutes = duration_seconds / 60

# --- 2. Extract Pickup Time Features ---
# We use the start time for this
pickup_hour = trip_start_time.dt.hour
pickup_dayofweek = trip_start_time.dt.dayofweek # Monday=0, Sunday=6

# --- 3. Calculate Average Speed ---
average_speed = trip_groups['speed'].mean()

# --- 4. Get Start and End Locations ---
start_lat = trip_groups['lat'].first()
start_lon = trip_groups['lon'].first()
end_lat = trip_groups['lat'].last()
end_lon = trip_groups['lon'].last()

# --- 5. Assemble the new features into a single DataFrame ---
features_df = pd.DataFrame({
    'duration_minutes': duration_minutes,
    'pickup_hour': pickup_hour,
    'pickup_dayofweek': pickup_dayofweek,
    'average_speed': average_speed,
    'start_lat': start_lat,
    'start_lon': start_lon,
    'end_lat': end_lat,
    'end_lon': end_lon
})

In [46]:
# Now, merge the features into your main 'df'
# The 'on' parameter tells pandas to match rows using VehicleID and trip_id
# The 'how='left'' ensures you keep all rows from your original df
features_df_to_merge = features_df.reset_index()
df = pd.merge(df, features_df_to_merge, on=['VehicleID', 'trip_id'], how='left')

In [47]:
df
df = df.dropna()

In [48]:
df

,VehicleID,gpsvalid,lat,lon,timestamp,speed,heading,for_hire_light,engine_acc,hour,...,total_trip_distance_km,total_trip_fees,duration_minutes,pickup_hour,pickup_dayofweek,average_speed,start_lat,start_lon,end_lat,end_lon
0,+20prWr63K5svsMtTmdqLnmsTGE,1,13.66729,100.58770,2024-12-01 05:24:13,0,290,0,1,5,...,36.505692,295.545534,60.866667,5,6,38.090909,13.66729,100.58770,13.69314,100.75144
1,+20prWr63K5svsMtTmdqLnmsTGE,1,13.66738,100.58770,2024-12-01 05:26:05,0,290,0,1,5,...,36.505692,295.545534,60.866667,5,6,38.090909,13.66729,100.58770,13.69314,100.75144
2,+20prWr63K5svsMtTmdqLnmsTGE,1,13.66738,100.58770,2024-12-01 05:28:05,0,290,0,1,5,...,36.505692,295.545534,60.866667,5,6,38.090909,13.66729,100.58770,13.69314,100.75144
3,+20prWr63K5svsMtTmdqLnmsTGE,1,13.66734,100.58778,2024-12-01 05:30:05,0,290,0,1,5,...,36.505692,295.545534,60.866667,5,6,38.090909,13.66729,100.58770,13.69314,100.75144
4,+20prWr63K5svsMtTmdqLnmsTGE,1,13.66734,100.58778,2024-12-01 05:31:05,0,290,0,1,5,...,36.505692,295.545534,60.866667,5,6,38.090909,13.66729,100.58770,13.69314,100.75144
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12108883,zwNAI8pHuCgPOF5NMs2nVaXBG04,1,13.73320,100.38991,2024-12-26 17:30:57,24,81,1,1,17,...,48.191423,393.127093,763.600000,4,3,43.368421,13.91573,100.59949,13.77508,100.39478
12108884,zwNAI8pHuCgPOF5NMs2nVaXBG04,1,13.73133,100.39144,2024-12-26 17:31:58,31,91,1,1,17,...,48.191423,393.127093,763.600000,4,3,43.368421,13.91573,100.59949,13.77508,100.39478
12108885,zwNAI8pHuCgPOF5NMs2nVaXBG04,1,13.73560,100.39541,2024-12-26 17:33:57,58,359,1,1,17,...,48.191423,393.127093,763.600000,4,3,43.368421,13.91573,100.59949,13.77508,100.39478
12108886,zwNAI8pHuCgPOF5NMs2nVaXBG04,1,13.75033,100.39522,2024-12-26 17:35:58,52,359,1,1,17,...,48.191423,393.127093,763.600000,4,3,43.368421,13.91573,100.59949,13.77508,100.39478
12108887,zwNAI8pHuCgPOF5NMs2nVaXBG04,1,13.75985,100.39505,2024-12-26 17:37:58,68,357,1,1,17,...,48.191423,393.127093,763.600000,4,3,43.368421,13.91573,100.59949,13.77508,100.39478

In [49]:
df.columns

Index(['VehicleID', 'gpsvalid', 'lat', 'lon', 'timestamp', 'speed', 'heading',
       'for_hire_light', 'engine_acc', 'hour', 'day_of_week', 'is_weekend',
       'trip_id', 'idle_period_id', 'idle_duration_minutes', 'lat_next',
       'lon_next', 'segment_distance_km', 'total_trip_distance_km',
       'total_trip_fees', 'duration_minutes', 'pickup_hour',
       'pickup_dayofweek', 'average_speed', 'start_lat', 'start_lon',
       'end_lat', 'end_lon'],
      dtype='object')

Feature Engineering

In [50]:
from sklearn.cluster import MiniBatchKMeans
import pandas as pd

# Assuming 'df' is your main dataframe
# Create 100 location clusters. You can experiment with this number.
kmeans = MiniBatchKMeans(n_clusters=100, batch_size=10000, random_state=42, n_init=10)
df['zone_id'] = kmeans.fit_predict(df[['lat', 'lon']])

# First, identify pickup and dropoff events
df['pickup_flag'] = ((df['for_hire_light'].shift(1) == 1) & (df['for_hire_light'] == 0)).astype(int)
df['dropoff_flag'] = ((df['for_hire_light'].shift(1) == 0) & (df['for_hire_light'] == 1)).astype(int)

# 1. Check if 'timestamp' is a column before trying to set it as the index
if 'timestamp' in df.columns:
    df.set_index('timestamp', inplace=True)

# Sort the DataFrame by the timestamp index before doing the rolling calculation
df.sort_index(inplace=True)

# By adding .values, we assign the results directly, ignoring the index alignment issue.
# This is safe because the dataframe is already sorted.
df['pickups_in_zone_last_hr'] = df.groupby('zone_id')['pickup_flag'].rolling('1H').sum().reset_index(0, drop=True).values
df['dropoffs_in_zone_last_hr'] = df.groupby('zone_id')['dropoff_flag'].rolling('1H').sum().reset_index(0, drop=True).values

# Fill any NaNs that result from the rolling window
df.fillna({'pickups_in_zone_last_hr': 0, 'dropoffs_in_zone_last_hr': 0}, inplace=True)

# Reset index to bring 'timestamp' back as a column
df.reset_index(inplace=True)

# Create a feature for 'zone_id' combined with the hour
df['zone_hour_interaction'] = df['zone_id'].astype(str) + '_' + df['hour'].astype(str)

# Now, label encode this new categorical feature so the model can use it
df['zone_hour_interaction'] = df['zone_hour_interaction'].astype('category').cat.codes

# Ensure data is sorted for accurate lag features
df.sort_values(by=['VehicleID', 'timestamp'], inplace=True)

# --- THE FIX IS HERE ---
# Apply .rolling() to the GroupBy object BEFORE selecting the 'speed' column.
# Then, select 'speed' and calculate the mean.
rolling_avg_speed = df.groupby('VehicleID').rolling('15T', on='timestamp')['speed'].mean()

# The result of a rolling operation on a groupby is a Series with a MultiIndex.
# We need to drop the 'VehicleID' level of the index to align it back to the original df.
df['avg_speed_last_15m'] = rolling_avg_speed.reset_index(level=0, drop=True).values
# --- END OF FIX ---


# Fill NaNs for the start of each taxi's journey
# Using 'bfill' (backfill) is a good choice here to fill the initial nulls.
df['avg_speed_last_15m'].fillna(method='bfill', inplace=True)

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/608406458.py:22: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df['pickups_in_zone_last_hr'] = df.groupby('zone_id')['pickup_flag'].rolling('1H').sum().reset_index(0, drop=True).values
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/608406458.py:23: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df['dropoffs_in_zone_last_hr'] = df.groupby('zone_id')['dropoff_flag'].rolling('1H').sum().reset_index(0, drop=True).values
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/608406458.py:43: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  rolling_avg_speed = df.groupby('VehicleID').rolling('15T', on='timestamp')['speed'].mean()
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/608406458.py:43: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  rolling_avg_speed = df.groupby('VehicleID').rolling('15T', on='timestamp')['speed'].mean()
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/608406458.py:53: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['avg_speed_last_15m'].fillna(method='bfill', inplace=True)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/608406458.py:53: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['avg_speed_last_15m'].fillna(method='bfill', inplace=True)

In [51]:
df

,timestamp,VehicleID,gpsvalid,lat,lon,speed,heading,for_hire_light,engine_acc,hour,...,start_lon,end_lat,end_lon,zone_id,pickup_flag,dropoff_flag,pickups_in_zone_last_hr,dropoffs_in_zone_last_hr,zone_hour_interaction,avg_speed_last_15m
44126,2024-12-01 05:24:13,+20prWr63K5svsMtTmdqLnmsTGE,1,13.66729,100.58770,0,290,0,1,5,...,100.58770,13.69314,100.75144,21,0,0,21.0,20.0,331,0.000000
44423,2024-12-01 05:26:05,+20prWr63K5svsMtTmdqLnmsTGE,1,13.66738,100.58770,0,290,0,1,5,...,100.58770,13.69314,100.75144,21,0,0,13.0,16.0,331,0.000000
44719,2024-12-01 05:28:05,+20prWr63K5svsMtTmdqLnmsTGE,1,13.66738,100.58770,0,290,0,1,5,...,100.58770,13.69314,100.75144,21,0,0,12.0,19.0,331,0.000000
45039,2024-12-01 05:30:05,+20prWr63K5svsMtTmdqLnmsTGE,1,13.66734,100.58778,0,290,0,1,5,...,100.58770,13.69314,100.75144,21,0,0,7.0,13.0,331,0.000000
45134,2024-12-01 05:31:05,+20prWr63K5svsMtTmdqLnmsTGE,1,13.66734,100.58778,0,290,0,1,5,...,100.58770,13.69314,100.75144,21,0,0,4.0,12.0,331,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9640311,2024-12-26 17:30:57,zwNAI8pHuCgPOF5NMs2nVaXBG04,1,13.73320,100.38991,24,81,1,1,17,...,100.59949,13.77508,100.39478,51,0,0,14.0,12.0,1113,31.333333
9640584,2024-12-26 17:31:58,zwNAI8pHuCgPOF5NMs2nVaXBG04,1,13.73133,100.39144,31,91,1,1,17,...,100.59949,13.77508,100.39478,51,0,0,16.0,16.0,1113,31.250000
9641386,2024-12-26 17:33:57,zwNAI8pHuCgPOF5NMs2nVaXBG04,1,13.73560,100.39541,58,359,1,1,17,...,100.59949,13.77508,100.39478,51,0,0,9.0,16.0,1113,36.600000
9642101,2024-12-26 17:35:58,zwNAI8pHuCgPOF5NMs2nVaXBG04,1,13.75033,100.39522,52,359,1,1,17,...,100.59949,13.77508,100.39478,60,0,0,7.0,7.0,1353,39.166667
9642863,2024-12-26 17:37:58,zwNAI8pHuCgPOF5NMs2nVaXBG04,1,13.75985,100.39505,68,357,1,1,17,...,100.59949,13.77508,100.39478,60,0,0,15.0,16.0,1353,43.285714

In [52]:
df.columns

Index(['timestamp', 'VehicleID', 'gpsvalid', 'lat', 'lon', 'speed', 'heading',
       'for_hire_light', 'engine_acc', 'hour', 'day_of_week', 'is_weekend',
       'trip_id', 'idle_period_id', 'idle_duration_minutes', 'lat_next',
       'lon_next', 'segment_distance_km', 'total_trip_distance_km',
       'total_trip_fees', 'duration_minutes', 'pickup_hour',
       'pickup_dayofweek', 'average_speed', 'start_lat', 'start_lon',
       'end_lat', 'end_lon', 'zone_id', 'pickup_flag', 'dropoff_flag',
       'pickups_in_zone_last_hr', 'dropoffs_in_zone_last_hr',
       'zone_hour_interaction', 'avg_speed_last_15m'],
      dtype='object')

In [53]:
# Paste this whole cell into your notebook (replaces previous functions).
import math
from datetime import timedelta
from typing import Iterable, Optional, Tuple, List

import numpy as np
import pandas as pd

# Optional: avoid installing packages during heavy processing — prefer pre-install
try:
    import h3
except Exception as e:
    raise ImportError("Missing 'h3' package. Install it in your environment (pip install h3) before running.") from e

# H3 wrappers (compatible with h3 v3/v4)
def _h3_cell(lat: float, lon: float, res: int) -> Optional[str]:
    if pd.isna(lat) or pd.isna(lon):
        return None
    if hasattr(h3, "geo_to_h3"):
        return h3.geo_to_h3(lat, lon, res)
    if hasattr(h3, "latlng_to_cell"):
        return h3.latlng_to_cell(lat, lon, res)
    raise AttributeError("No suitable H3 function for lat/lon -> cell")

def _h3_neighbors(cell: str, k: int) -> List[str]:
    if cell is None:
        return []
    if hasattr(h3, "k_ring"):
        return list(h3.k_ring(cell, k))
    if hasattr(h3, "grid_disk"):
        return list(h3.grid_disk(cell, k))
    return [cell]

# --------------------------
# Helpers
# --------------------------
def _as_5min_floor(ts: pd.Series) -> pd.Series:
    return (ts.dt.floor("5min")).astype("datetime64[ns]")

def _sin_cos(series: pd.Series, period: float) -> Tuple[pd.Series, pd.Series]:
    radians = 2 * math.pi * (series.astype(float) / period)
    return np.sin(radians), np.cos(radians)

def build_complete_index(time_bins: Iterable[pd.Timestamp], cells: Iterable[str]) -> pd.MultiIndex:
    return pd.MultiIndex.from_product([pd.Index(time_bins, name="time_bin"), pd.Index(cells, name="h3_cell")])

# --------------------------
# Core functions (safe)
# --------------------------
def assign_h3_cells(
    df: pd.DataFrame,
    lat_col: str,
    lon_col: str,
    h3_res: int = 7,
    out_col: str = "h3_cell",
) -> pd.DataFrame:
    df = df.copy()
    # vectorized-ish mapping using list comprehension (safe)
    coords = df[[lat_col, lon_col]].to_numpy()
    df[out_col] = [_h3_cell(lat, lon, h3_res) for lat, lon in coords]
    return df

def aggregate_events_to_cells(
    df: pd.DataFrame,
    ts_col: str,
    cell_col: str,
    bin_minutes: int = 5,
    value_col: Optional[str] = None,
    agg_name: str = "count",
    complete_index: Optional[pd.MultiIndex] = None,
) -> pd.DataFrame:
    df = df.copy()
    df["time_bin"] = _as_5min_floor(pd.to_datetime(df[ts_col]))
    if value_col is None or agg_name == "count":
        grouped = df.groupby(["time_bin", cell_col]).size().rename("value").to_frame()
    else:
        grouped = df.groupby(["time_bin", cell_col])[value_col].agg(agg_name).rename("value").to_frame()
    if complete_index is not None:
        grouped = grouped.reindex(complete_index, fill_value=0)
    return grouped.reset_index()

def add_time_features(frame: pd.DataFrame) -> pd.DataFrame:
    frame = frame.copy()
    frame["hour"] = frame["time_bin"].dt.hour
    frame["dow"] = frame["time_bin"].dt.weekday
    frame["is_weekend"] = (frame["dow"].isin([5, 6])).astype(int)
    frame["minute_of_day"] = frame["time_bin"].dt.hour * 60 + frame["time_bin"].dt.minute
    sin_h, cos_h = _sin_cos(frame["hour"], 24)
    sin_m, cos_m = _sin_cos(frame["minute_of_day"], 24 * 60)
    frame["sin_hour"], frame["cos_hour"] = sin_h, cos_h
    frame["sin_min"], frame["cos_min"] = sin_m, cos_m
    return frame

def add_lagged_counts(
    frame: pd.DataFrame,
    group_col: str,
    value_col: str = "pickup_cnt",
    lags: Tuple[int, ...] = (1, 2, 3),
    mas: Tuple[int, ...] = (6, 12),
    prefix: str = "pickup",
) -> pd.DataFrame:
    frame = frame.copy()
    frame = frame.sort_values([group_col, "time_bin"])
    def _per_group(g: pd.DataFrame) -> pd.DataFrame:
        g = g.copy()
        for k in lags:
            g[f"{prefix}_lag_{k}"] = g[value_col].shift(k)
        for w in mas:
            g[f"{prefix}_ma_{w}"] = g[value_col].rolling(window=w, min_periods=1).mean()
        return g
    frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
    return frame

def add_neighbor_aggregates(
    frame: pd.DataFrame,
    cell_col: str = "h3_cell",
    value_cols: Tuple[str, ...] = ("pickup_cnt", "pickup_lag_1", "pickup_lag_2", "pickup_lag_3"),
    k_rings: Tuple[int, ...] = (1, 2),
    max_batch_cells: int = 2000,
) -> pd.DataFrame:
    """
    Memory-friendly neighbor aggregates computed in batches.
    Produces columns: nbr{K}_mean_{value_col}
    """
    frame = frame.copy()
    # minimal tmp that we need
    tmp = frame[["time_bin", cell_col] + list(value_cols)].copy()
    unique_cells = [c for c in tmp[cell_col].dropna().unique().tolist()]
    if len(unique_cells) == 0:
        # add zero neighbor columns and return
        for k in k_rings:
            for v in value_cols:
                frame[f"nbr{k}_mean_{v}"] = 0.0
        return frame

    # initialize columns
    for k in k_rings:
        for v in value_cols:
            frame[f"nbr{k}_mean_{v}"] = np.nan

    # index tmp for fast merge lookups
    lookup = tmp.rename(columns={cell_col: "cell_nbr"}).set_index(["time_bin", "cell_nbr"])

    # function to process batch
    def process_batch(batch_cells: List[str]):
        # build map DataFrame: cell_src x neighbor cell_nbr (for max ring to save repeated calls)
        rows = []
        for c in batch_cells:
            rows.append({"cell_src": c, "neighbors": _h3_neighbors(c, max(k_rings))})
        map_df = pd.DataFrame(rows).explode("neighbors").rename(columns={"neighbors": "cell_nbr"})
        # join times by merging with available lookup keys:
        # create a merge-ready DataFrame by repeating map_df for each time_bin (cartesian) would be heavy,
        # so instead iterate over unique time bins — still expensive but batched by cells reduces peak mem.
        time_bins = tmp["time_bin"].drop_duplicates().tolist()
        # For memory reasons keep iteration over time bins (time bins often smaller than cells)
        # build a small list of results to merge back
        results = []
        for tb in time_bins:
            # values available for this time bin
            try:
                vals = lookup.loc[tb]
            except KeyError:
                # no data for this time bin
                continue
            vals = vals.reset_index()  # columns: cell_nbr + value_cols
            # map_df join with vals on cell_nbr
            joined = map_df.merge(vals, on="cell_nbr", how="left")
            if joined.empty:
                continue
            # for each k compute neighbor means by selecting neighbors that fall into k-ring sets
            for k in k_rings:
                # precompute neighbors_k for each cell_src
                nk_map = {c: set(_h3_neighbors(c, k)) for c in batch_cells}
                # filter joined rows by neighbor membership
                # joined has columns: cell_src, cell_nbr, value_cols...
                joined["is_in_k"] = joined.apply(lambda r, nm=nk_map: (r["cell_nbr"] in nm.get(r["cell_src"], set())), axis=1)
                subset = joined[joined["is_in_k"]]
                if subset.empty:
                    # still need to create rows (no neighbors found) -> default NaN
                    continue
                grp = subset.groupby("cell_src")[list(value_cols)].mean().reset_index()
                for v in value_cols:
                    colname = f"nbr{k}_mean_{v}"
                    grp2 = grp[["cell_src", v]].rename(columns={"cell_src": cell_col, v: colname})
                    # attach time_bin for merging back
                    grp2["time_bin"] = tb
                    results.append(grp2[["time_bin", cell_col, colname]])
        if len(results) == 0:
            return
        merged = pd.concat(results, axis=0, ignore_index=True)
        # merge into frame
        frame_cols_to_merge = [c for c in merged.columns if c not in ["time_bin", cell_col]]
        frame_local = frame.merge(merged, on=["time_bin", cell_col], how="left")
        # update frame in place for new columns
        for c in frame_local.columns:
            if c.startswith("nbr") and c in frame.columns:
                frame[c] = frame_local[c]
        return

    # process unique_cells in batches
    n = len(unique_cells)
    for i in range(0, n, max_batch_cells):
        batch = unique_cells[i : i + max_batch_cells]
        process_batch(batch)

    # finally fill any NaNs with 0
    nbr_cols = [c for c in frame.columns if c.startswith("nbr")]
    frame[nbr_cols] = frame[nbr_cols].fillna(0.0)
    return frame

def build_features_safe(
    trips: pd.DataFrame,
    pickup_time_col: str,
    pickup_lat_col: str,
    pickup_lon_col: str,
    dropoff_time_col: Optional[str] = None,
    dropoff_lat_col: Optional[str] = None,
    dropoff_lon_col: Optional[str] = None,
    # h3_res: int = 7,
    h3_res: int = 7,
    start_time: Optional[pd.Timestamp] = None,
    end_time: Optional[pd.Timestamp] = None,
    max_cells_for_full_index: int = 20000,  # safety threshold
    neighbor_batch_cells: int = 2000,
) -> Tuple[pd.DataFrame, pd.Series, pd.DataFrame]:
    """
    Safer version of build_features:
     - default h3_res=7 for fewer cells
     - guards for empty inputs
     - will raise a clear error if resource limits would be exceeded
    """
    df = trips.copy()
    if df.shape[0] == 0:
        raise ValueError("trips DataFrame is empty")

    df[pickup_time_col] = pd.to_datetime(df[pickup_time_col])
    if start_time is not None:
        df = df[df[pickup_time_col] >= pd.to_datetime(start_time)]
    if end_time is not None:
        df = df[df[pickup_time_col] < pd.to_datetime(end_time)]
    if df.shape[0] == 0:
        raise ValueError("No rows after time filtering")

    # Assign pickup cell (drop rows where assignment failed)
    df = assign_h3_cells(df, pickup_lat_col, pickup_lon_col, h3_res=h3_res, out_col="pickup_cell")
    df = df.dropna(subset=[pickup_time_col, "pickup_cell"])
    if df.shape[0] == 0:
        raise ValueError("No valid pickup events after assigning h3 cell and dropping NaNs")

    # initial aggregate to know extent
    agg0 = aggregate_events_to_cells(df=df, ts_col=pickup_time_col, cell_col="pickup_cell", bin_minutes=5)
    if agg0.empty:
        raise ValueError("No aggregated pickups found (agg0 empty)")

    time_start = agg0["time_bin"].min()
    time_end = agg0["time_bin"].max()
    time_bins = pd.date_range(start=time_start, end=time_end, freq="5min")
    cells = agg0["pickup_cell"].dropna().unique().tolist()
    if len(cells) == 0:
        raise ValueError("No h3 cells found in pickups")

    # safety guard: if cells * time_bins huge, abort with an informative error
    est_rows = len(cells) * len(time_bins)
    if est_rows > 50_000_000:  # arbitrary big threshold; adjust if you want risk
        raise MemoryError(f"Estimated full grid size {est_rows:,} > 50M rows. Reduce h3_res or window.")

    if len(cells) > max_cells_for_full_index:
        raise MemoryError(f"Number of cells ({len(cells):,}) > max_cells_for_full_index ({max_cells_for_full_index}). "
                          "Consider lowering h3_res, restricting bounding box, or sampling.")

    full_idx = build_complete_index(time_bins, cells)

    pickup_grid = aggregate_events_to_cells(
        df=df[[pickup_time_col, "pickup_cell"]].rename(columns={pickup_time_col: "ts", "pickup_cell": "h3_cell"}).dropna(),
        ts_col="ts",
        cell_col="h3_cell",
        bin_minutes=5,
        complete_index=full_idx,
    ).rename(columns={"value": "pickup_cnt"})

    # dropoffs (supply) — optional
    if dropoff_lat_col and dropoff_lon_col and dropoff_time_col and all(col in df.columns for col in [dropoff_lat_col, dropoff_lon_col, dropoff_time_col]):
        ddf = df[[dropoff_time_col, dropoff_lat_col, dropoff_lon_col]].dropna().copy()
        ddf = assign_h3_cells(ddf, dropoff_lat_col, dropoff_lon_col, h3_res=h3_res, out_col="drop_cell")
        drop_grid = aggregate_events_to_cells(
            df=ddf,
            ts_col=dropoff_time_col,
            cell_col="drop_cell",
            bin_minutes=5,
            complete_index=full_idx,
        ).rename(columns={"drop_cell": "h3_cell", "value": "dropoff_cnt"})
    else:
        drop_grid = None

    base = pickup_grid.copy()
    if drop_grid is not None:
        base = base.merge(drop_grid, on=["time_bin", "h3_cell"], how="left")
        base["dropoff_cnt"] = base["dropoff_cnt"].fillna(0)
    else:
        base["dropoff_cnt"] = 0

    base = add_time_features(base)
    base = add_lagged_counts(base, group_col="h3_cell", value_col="pickup_cnt", lags=(1,2,3), mas=(6,12), prefix="pickup")
    base = add_lagged_counts(base, group_col="h3_cell", value_col="dropoff_cnt", lags=(1,2,3), mas=(6,12), prefix="dropoff")
    base["net_inflow"] = base["dropoff_cnt"] - base["pickup_cnt"]

    # neighbor aggregates (batched)
    base = add_neighbor_aggregates(
        base,
        cell_col="h3_cell",
        value_cols=("pickup_cnt", "pickup_lag_1", "pickup_lag_2", "pickup_lag_3", "dropoff_cnt"),
        k_rings=(1,2),
        max_batch_cells=neighbor_batch_cells,
    )

    base = base.sort_values(["h3_cell", "time_bin"]).reset_index(drop=True)
    base["future_pickup_cnt"] = base.groupby("h3_cell")["pickup_cnt"].shift(-1)
    target = (base["future_pickup_cnt"].fillna(0) > 0).astype(int).rename("y_next5_has_pickup")

    feature_cols = [
        "hour", "dow", "is_weekend", "sin_hour", "cos_hour", "sin_min", "cos_min",
        "pickup_cnt", "dropoff_cnt", "net_inflow",
        "pickup_lag_1", "pickup_lag_2", "pickup_lag_3", "pickup_ma_6", "pickup_ma_12",
        "dropoff_lag_1", "dropoff_lag_2", "dropoff_lag_3", "dropoff_ma_6", "dropoff_ma_12",
        "nbr1_mean_pickup_cnt", "nbr2_mean_pickup_cnt",
        "nbr1_mean_pickup_lag_1", "nbr2_mean_pickup_lag_1",
        "nbr1_mean_pickup_lag_2", "nbr2_mean_pickup_lag_2",
        "nbr1_mean_pickup_lag_3", "nbr2_mean_pickup_lag_3",
        "nbr1_mean_dropoff_cnt", "nbr2_mean_dropoff_cnt",
    ]
    for c in feature_cols:
        if c not in base.columns:
            base[c] = 0.0

    X = base[feature_cols].fillna(0.0)
    meta = base[["time_bin", "h3_cell", "pickup_cnt"]].copy()
    return X, target, meta

# quick helper alias to preserve old name if you want:
build_features = build_features_safe

print("Safe H3 5-minute feature utilities loaded (build_features). Recommended defaults: h3_res=7 on 16GB MacBook Air.")

Safe H3 5-minute feature utilities loaded (build_features). Recommended defaults: h3_res=7 on 16GB MacBook Air.

In [ ]:
# MEMORY-OPTIMIZED PROCESSING - PREVENTS CRASHES WHILE KEEPING h3_res=7 and k_rings=(1,2)
# Enhanced version with better memory management and smaller processing chunks

import gc
import pandas as pd
from pathlib import Path
import numpy as np
import psutil
import os

def get_memory_usage():
    """Get current memory usage in MB"""
    process = psutil.Process(os.getpid())
    return process.memory_info().rss / 1024 / 1024

def get_busiest_cells_per_window(trips_df, h3_res=7, top_n=200):
    """Get top N busiest cells for this time window - reduced from 200 to 150"""
    # Assign cells
    trips_with_cells = assign_h3_cells(
        trips_df.copy(), 
        "pickup_latitude", 
        "pickup_longitude", 
        h3_res=h3_res, 
        out_col="pickup_cell"
    )
    # Count pickups per cell
    cell_counts = trips_with_cells["pickup_cell"].value_counts()
    # Return top N cells
    top_cells = cell_counts.head(top_n).index.tolist()
    return top_cells

def add_neighbor_aggregates_optimized(
    frame: pd.DataFrame,
    cell_col: str = "h3_cell",
    value_cols: tuple = ("pickup_cnt", "pickup_lag_1", "pickup_lag_2", "pickup_lag_3"),
    k_rings: tuple = (1, 2),
    max_batch_cells: int = 60,  # Much smaller batches
    memory_threshold_mb: int = 10000,  # Stop if memory gets too high
) -> pd.DataFrame:
    """
    Memory-optimized version of add_neighbor_aggregates
    """
    frame = frame.copy()
    
    # Check initial memory
    initial_memory = get_memory_usage()
    print(f"  Initial memory: {initial_memory:.1f} MB")
    
    # minimal tmp that we need
    tmp = frame[["time_bin", cell_col] + list(value_cols)].copy()
    unique_cells = [c for c in tmp[cell_col].dropna().unique().tolist()]
    
    if len(unique_cells) == 0:
        # add zero neighbor columns and return
        for k in k_rings:
            for v in value_cols:
                frame[f"nbr{k}_mean_{v}"] = 0.0
        return frame

    # initialize columns
    for k in k_rings:
        for v in value_cols:
            frame[f"nbr{k}_mean_{v}"] = np.nan

    # index tmp for fast merge lookups
    lookup = tmp.rename(columns={cell_col: "cell_nbr"}).set_index(["time_bin", "cell_nbr"])

    # function to process batch with memory monitoring
    def process_batch_optimized(batch_cells: list):
        current_memory = get_memory_usage()
        if current_memory > memory_threshold_mb:
            print(f"  ⚠️ Memory threshold reached ({current_memory:.1f} MB), skipping batch")
            return
            
        # build map DataFrame: cell_src x neighbor cell_nbr (for max ring to save repeated calls)
        rows = []
        for c in batch_cells:
            try:
                neighbors = _h3_neighbors(c, max(k_rings))
                rows.append({"cell_src": c, "neighbors": neighbors})
            except Exception as e:
                print(f"  ⚠️ Error getting neighbors for cell {c}: {e}")
                continue
                
        if not rows:
            return
            
        map_df = pd.DataFrame(rows).explode("neighbors").rename(columns={"neighbors": "cell_nbr"})
        
        # Process time bins in smaller chunks
        time_bins = tmp["time_bin"].drop_duplicates().tolist()
        results = []
        
        # Process time bins in smaller chunks to reduce memory
        time_chunk_size = min(100, len(time_bins))  # Process max 50 time bins at once
        
        for i in range(0, len(time_bins), time_chunk_size):
            time_chunk = time_bins[i:i + time_chunk_size]
            
            for tb in time_chunk:
                # values available for this time bin
                try:
                    vals = lookup.loc[tb]
                except KeyError:
                    continue
                    
                vals = vals.reset_index()
                
                # map_df join with vals on cell_nbr
                joined = map_df.merge(vals, on="cell_nbr", how="left")
                if joined.empty:
                    continue
                    
                # for each k compute neighbor means by selecting neighbors that fall into k-ring sets
                for k in k_rings:
                    # precompute neighbors_k for each cell_src
                    nk_map = {}
                    for c in batch_cells:
                        try:
                            nk_map[c] = set(_h3_neighbors(c, k))
                        except Exception as e:
                            print(f"  ⚠️ Error getting k={k} neighbors for cell {c}: {e}")
                            continue
                    
                    # filter joined rows by neighbor membership using vectorized operations
                    if nk_map:
                        # Create a more efficient membership check
                        joined["is_in_k"] = False
                        for cell_src, neighbors in nk_map.items():
                            mask = joined["cell_src"] == cell_src
                            joined.loc[mask, "is_in_k"] = joined.loc[mask, "cell_nbr"].isin(neighbors)
                        
                        subset = joined[joined["is_in_k"]]
                        if subset.empty:
                            continue
                            
                        grp = subset.groupby("cell_src")[list(value_cols)].mean().reset_index()
                        for v in value_cols:
                            colname = f"nbr{k}_mean_{v}"
                            grp2 = grp[["cell_src", v]].rename(columns={"cell_src": cell_col, v: colname})
                            grp2["time_bin"] = tb
                            results.append(grp2[["time_bin", cell_col, colname]])
            
            # Force garbage collection after each time chunk
            gc.collect()
            
        if len(results) == 0:
            return
            
        try:
            merged = pd.concat(results, axis=0, ignore_index=True)
            # merge into frame
            frame_cols_to_merge = [c for c in merged.columns if c not in ["time_bin", cell_col]]
            frame_local = frame.merge(merged, on=["time_bin", cell_col], how="left")
            # update frame in place for new columns
            for c in frame_local.columns:
                if c.startswith("nbr") and c in frame.columns:
                    frame[c] = frame_local[c]
        except Exception as e:
            print(f"  ⚠️ Error merging neighbor results: {e}")

    # process unique_cells in very small batches
    n = len(unique_cells)
    batch_size = min(max_batch_cells, 60)  # Even smaller batches
    
    for i in range(0, n, batch_size):
        batch = unique_cells[i : i + batch_size]
        print(f"  Processing cell batch {i//batch_size + 1}/{(n-1)//batch_size + 1} ({len(batch)} cells)")
        
        process_batch_optimized(batch)
        
        # Force garbage collection after each batch
        gc.collect()
        
        # Check memory after each batch
        current_memory = get_memory_usage()
        if current_memory > memory_threshold_mb:
            print(f"  ⚠️ Memory limit reached, stopping neighbor processing")
            break

    # finally fill any NaNs with 0
    nbr_cols = [c for c in frame.columns if c.startswith("nbr")]
    frame[nbr_cols] = frame[nbr_cols].fillna(0.0)
    return frame

def build_features_memory_optimized(
    trips: pd.DataFrame,
    pickup_time_col: str,
    pickup_lat_col: str,
    pickup_lon_col: str,
    dropoff_time_col: str = None,
    dropoff_lat_col: str = None,
    dropoff_lon_col: str = None,
    h3_res: int = 7,
    start_time: pd.Timestamp = None,
    end_time: pd.Timestamp = None,
    max_cells_for_full_index: int = 180,  # Reduced from 200
    neighbor_batch_cells: int = 30,   # Reduced from 50
) -> tuple:
    """
    Memory-optimized version of build_features that prevents crashes
    """
    print(f"  Building features with h3_res={h3_res}, max_cells={max_cells_for_full_index}")
    print(f"  Initial memory: {get_memory_usage():.1f} MB")
    
    df = trips.copy()
    if df.shape[0] == 0:
        raise ValueError("trips DataFrame is empty")

    df[pickup_time_col] = pd.to_datetime(df[pickup_time_col])
    if start_time is not None:
        df = df[df[pickup_time_col] >= pd.to_datetime(start_time)]
    if end_time is not None:
        df = df[df[pickup_time_col] < pd.to_datetime(end_time)]
    if df.shape[0] == 0:
        raise ValueError("No rows after time filtering")

    # Assign pickup cell (drop rows where assignment failed)
    df = assign_h3_cells(df, pickup_lat_col, pickup_lon_col, h3_res=h3_res, out_col="pickup_cell")
    df = df.dropna(subset=[pickup_time_col, "pickup_cell"])
    if df.shape[0] == 0:
        raise ValueError("No valid pickup events after assigning h3 cell and dropping NaNs")

    # initial aggregate to know extent
    agg0 = aggregate_events_to_cells(df=df, ts_col=pickup_time_col, cell_col="pickup_cell", bin_minutes=5)
    if agg0.empty:
        raise ValueError("No aggregated pickups found (agg0 empty)")

    time_start = agg0["time_bin"].min()
    time_end = agg0["time_bin"].max()
    time_bins = pd.date_range(start=time_start, end=time_end, freq="5min")
    cells = agg0["pickup_cell"].dropna().unique().tolist()
    if len(cells) == 0:
        raise ValueError("No h3 cells found in pickups")

    # safety guard: if cells * time_bins huge, abort with an informative error
    est_rows = len(cells) * len(time_bins)
    if est_rows > 10_000_000:  # Reduced threshold
        raise MemoryError(f"Estimated full grid size {est_rows:,} > 10M rows. Reduce h3_res or window.")

    if len(cells) > max_cells_for_full_index:
        raise MemoryError(f"Number of cells ({len(cells):,}) > max_cells_for_full_index ({max_cells_for_full_index}). "
                          "Consider lowering h3_res, restricting bounding box, or sampling.")

    full_idx = build_complete_index(time_bins, cells)

    pickup_grid = aggregate_events_to_cells(
        df=df[[pickup_time_col, "pickup_cell"]].rename(columns={pickup_time_col: "ts", "pickup_cell": "h3_cell"}).dropna(),
        ts_col="ts",
        cell_col="h3_cell",
        bin_minutes=5,
        complete_index=full_idx,
    ).rename(columns={"value": "pickup_cnt"})

    # dropoffs (supply) — optional
    if dropoff_lat_col and dropoff_lon_col and dropoff_time_col and all(col in df.columns for col in [dropoff_lat_col, dropoff_lon_col, dropoff_time_col]):
        ddf = df[[dropoff_time_col, dropoff_lat_col, dropoff_lon_col]].dropna().copy()
        ddf = assign_h3_cells(ddf, dropoff_lat_col, dropoff_lon_col, h3_res=h3_res, out_col="drop_cell")
        drop_grid = aggregate_events_to_cells(
            df=ddf,
            ts_col=dropoff_time_col,
            cell_col="drop_cell",
            bin_minutes=5,
            complete_index=full_idx,
        ).rename(columns={"drop_cell": "h3_cell", "value": "dropoff_cnt"})
    else:
        drop_grid = None

    base = pickup_grid.copy()
    if drop_grid is not None:
        base = base.merge(drop_grid, on=["time_bin", "h3_cell"], how="left")
        base["dropoff_cnt"] = base["dropoff_cnt"].fillna(0)
    else:
        base["dropoff_cnt"] = 0

    base = add_time_features(base)
    base = add_lagged_counts(base, group_col="h3_cell", value_col="pickup_cnt", lags=(1,2,3), mas=(6,12), prefix="pickup")
    base = add_lagged_counts(base, group_col="h3_cell", value_col="dropoff_cnt", lags=(1,2,3), mas=(6,12), prefix="dropoff")
    base["net_inflow"] = base["dropoff_cnt"] - base["pickup_cnt"]

    print(f"  Memory before neighbor processing: {get_memory_usage():.1f} MB")
    
    # Use optimized neighbor aggregates
    base = add_neighbor_aggregates_optimized(
        base,
        cell_col="h3_cell",
        value_cols=("pickup_cnt", "pickup_lag_1", "pickup_lag_2", "pickup_lag_3", "dropoff_cnt"),
        k_rings=(1, 2),  # Keep k_rings=(1,2) as requested
        max_batch_cells=neighbor_batch_cells,
    )

    base = base.sort_values(["h3_cell", "time_bin"]).reset_index(drop=True)
    base["future_pickup_cnt"] = base.groupby("h3_cell")["pickup_cnt"].shift(-1)
    target = (base["future_pickup_cnt"].fillna(0) > 0).astype(int).rename("y_next5_has_pickup")

    feature_cols = [
        "hour", "dow", "is_weekend", "sin_hour", "cos_hour", "sin_min", "cos_min",
        "pickup_cnt", "dropoff_cnt", "net_inflow",
        "pickup_lag_1", "pickup_lag_2", "pickup_lag_3", "pickup_ma_6", "pickup_ma_12",
        "dropoff_lag_1", "dropoff_lag_2", "dropoff_lag_3", "dropoff_ma_6", "dropoff_ma_12",
        "nbr1_mean_pickup_cnt", "nbr2_mean_pickup_cnt",
        "nbr1_mean_pickup_lag_1", "nbr2_mean_pickup_lag_1",
        "nbr1_mean_pickup_lag_2", "nbr2_mean_pickup_lag_2",
        "nbr1_mean_pickup_lag_3", "nbr2_mean_pickup_lag_3",
        "nbr1_mean_dropoff_cnt", "nbr2_mean_dropoff_cnt",
    ]
    for c in feature_cols:
        if c not in base.columns:
            base[c] = 0.0

    X = base[feature_cols].fillna(0.0)
    meta = base[["time_bin", "h3_cell", "pickup_cnt"]].copy()
    
    print(f"  Final memory: {get_memory_usage():.1f} MB")
    return X, target, meta

def process_time_window_optimized(trips_window, h3_res=7, max_cells=150):
    """Process a single time window with optimized memory management"""
    if trips_window.empty:
        return None, None, None
    
    # Get busiest cells for this window only
    top_cells = get_busiest_cells_per_window(trips_window, h3_res=h3_res, top_n=max_cells)
    
    if not top_cells:
        return None, None, None
    
    # Filter trips to only include top cells
    trips_with_cells = assign_h3_cells(
        trips_window.copy(), 
        "pickup_latitude", 
        "pickup_longitude", 
        h3_res=h3_res, 
        out_col="pickup_cell"
    )
    trips_filtered = trips_with_cells[trips_with_cells["pickup_cell"].isin(top_cells)].copy()
    
    if trips_filtered.empty:
        return None, None, None
    
    print(f"  Processing {len(trips_filtered)} trips in {len(top_cells)} cells")
    
    try:
        X, y, meta = build_features_memory_optimized(
            trips=trips_filtered,
            pickup_time_col="pickup_datetime",
            pickup_lat_col="pickup_latitude",
            pickup_lon_col="pickup_longitude", 
            dropoff_time_col=None,
            dropoff_lat_col=None,
            dropoff_lon_col=None,
            h3_res=h3_res,
            max_cells_for_full_index=max_cells,
            neighbor_batch_cells=30,  # Small batches
        )
        return X, y, meta
    except Exception as e:
        print(f"  ❌ Window failed: {e}")
        return None, None, None
    
# Ensure 'trips' exists with the expected columns
if 'trips' not in globals():
    if 'df' in globals():
        trips = df.rename(columns={
            'timestamp': 'pickup_datetime',
            'lat': 'pickup_latitude',
            'lon': 'pickup_longitude'
        })[['pickup_datetime', 'pickup_latitude', 'pickup_longitude']].dropna()
    elif 'taxis_df' in globals():
        trips = taxis_df.rename(columns={
            'timestamp': 'pickup_datetime',
            'lat': 'pickup_latitude',
            'lon': 'pickup_longitude'
        })[['pickup_datetime', 'pickup_latitude', 'pickup_longitude']].dropna()
    else:
        raise NameError("Define 'trips' with columns: pickup_datetime, pickup_latitude, pickup_longitude.")

trips['pickup_datetime'] = pd.to_datetime(trips['pickup_datetime'])

print("=== MEMORY-OPTIMIZED PROCESSING ===")
print(f"Total trips to process: {len(trips)}")
print(f"Initial memory: {get_memory_usage():.1f} MB")

# Create 2-hour time windows
trips["pickup_datetime"] = pd.to_datetime(trips["pickup_datetime"])
start_time = trips["pickup_datetime"].min()
end_time = trips["pickup_datetime"].max()

# Create 2-hour windows
window_hours = 2
windows = pd.date_range(start_time, end_time, freq=f"{window_hours}H")

print(f"Created {len(windows)-1} time windows of {window_hours} hours each")

# Output files
output_dir = Path("/Users/jul/Desktop/uni/Data Analytics/Taxi-Income-Optimizer/PickUP rate/prepared_data")
output_dir.mkdir(exist_ok=True)

X_path = output_dir / "X_features_5min_optimized.csv"
y_path = output_dir / "y_target_5min_optimized.csv" 
meta_path = output_dir / "meta_5min_optimized.csv"

# Process each window
all_X = []
all_y = []
all_meta = []

for i in range(len(windows)-1):
    window_start = windows[i]
    window_end = windows[i+1]
    
    print(f"\n--- Window {i+1}/{len(windows)-1}: {window_start} to {window_end} ---")
    print(f"Memory before window: {get_memory_usage():.1f} MB")
    
    # Filter trips for this window
    window_trips = trips[
        (trips["pickup_datetime"] >= window_start) & 
        (trips["pickup_datetime"] < window_end)
    ].copy()
    
    if window_trips.empty:
        print("  No trips in this window, skipping")
        continue
    
    print(f"  Found {len(window_trips)} trips in window")
    
    # Process window with optimized function
    X, y, meta = process_time_window_optimized(window_trips, h3_res=7, max_cells=150)
    
    if X is not None:
        all_X.append(X)
        all_y.append(y)
        all_meta.append(meta)
        print(f"  ✅ Generated {len(X)} feature rows")
    else:
        print(f"  ❌ Window failed")
    
    # Force garbage collection
    del window_trips
    gc.collect()
    
    print(f"Memory after window: {get_memory_usage():.1f} MB")

print(f"\n=== RESULTS ===")
if all_X:
    print(f"Successfully processed {len(all_X)} windows")
    print(f"Total feature rows: {sum(len(x) for x in all_X)}")
    
    # Combine all results
    print("Combining results...")
    X_combined = pd.concat(all_X, ignore_index=True)
    y_combined = pd.concat(all_y, ignore_index=True)
    meta_combined = pd.concat(all_meta, ignore_index=True)
    
    # Save to files
    print(f"Saving to files...")
    X_combined.to_csv(X_path, index=False)
    y_combined.to_csv(y_path, index=False)
    meta_combined.to_csv(meta_path, index=False)
    
    print(f"✅ Saved {len(X_combined)} feature rows to:")
    print(f"  - {X_path}")
    print(f"  - {y_path}")
    print(f"  - {meta_path}")
else:
    print("❌ No windows processed successfully")

=== MEMORY-OPTIMIZED PROCESSING ===
Total trips to process: 11651983
Initial memory: 1169.3 MB
Created 640 time windows of 2 hours each

--- Window 1/640: 2024-11-08 15:01:45 to 2024-11-08 17:01:45 ---
Memory before window: 1272.8 MB
  Found 3 trips in window
  Processing 3 trips in 1 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1273.1 MB
  Memory before neighbor processing: 1273.4 MB
  Initial memory: 1273.4 MB
  Processing cell batch 1/1 (1 cells)

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/2071981944.py:391: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  windows = pd.date_range(start_time, end_time, freq=f"{window_hours}H")
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Final memory: 1274.1 MB
  ✅ Generated 1 feature rows
Memory after window: 1274.2 MB

--- Window 2/640: 2024-11-08 17:01:45 to 2024-11-08 19:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 3/640: 2024-11-08 19:01:45 to 2024-11-08 21:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 4/640: 2024-11-08 21:01:45 to 2024-11-08 23:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 5/640: 2024-11-08 23:01:45 to 2024-11-09 01:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 6/640: 2024-11-09 01:01:45 to 2024-11-09 03:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 7/640: 2024-11-09 03:01:45 to 2024-11-09 05:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 8/640: 2024-11-09 05:01:45 to 2024-11-09 07:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 9/640: 2024-11-09 07:01:45 to 2024-11-09 09:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 10/640: 2024-11-09 09:01:45 to 2024-11-09 11:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 11/640: 2024-11-09 11:01:45 to 2024-11-09 13:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 12/640: 2024-11-09 13:01:45 to 2024-11-09 15:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 13/640: 2024-11-09 15:01:45 to 2024-11-09 17:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 14/640: 2024-11-09 17:01:45 to 2024-11-09 19:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 15/640: 2024-11-09 19:01:45 to 2024-11-09 21:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 16/640: 2024-11-09 21:01:45 to 2024-11-09 23:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 17/640: 2024-11-09 23:01:45 to 2024-11-10 01:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 18/640: 2024-11-10 01:01:45 to 2024-11-10 03:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 19/640: 2024-11-10 03:01:45 to 2024-11-10 05:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 20/640: 2024-11-10 05:01:45 to 2024-11-10 07:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 21/640: 2024-11-10 07:01:45 to 2024-11-10 09:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 22/640: 2024-11-10 09:01:45 to 2024-11-10 11:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 23/640: 2024-11-10 11:01:45 to 2024-11-10 13:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 24/640: 2024-11-10 13:01:45 to 2024-11-10 15:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 25/640: 2024-11-10 15:01:45 to 2024-11-10 17:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 26/640: 2024-11-10 17:01:45 to 2024-11-10 19:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 27/640: 2024-11-10 19:01:45 to 2024-11-10 21:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 28/640: 2024-11-10 21:01:45 to 2024-11-10 23:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 29/640: 2024-11-10 23:01:45 to 2024-11-11 01:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 30/640: 2024-11-11 01:01:45 to 2024-11-11 03:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 31/640: 2024-11-11 03:01:45 to 2024-11-11 05:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 32/640: 2024-11-11 05:01:45 to 2024-11-11 07:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 33/640: 2024-11-11 07:01:45 to 2024-11-11 09:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 34/640: 2024-11-11 09:01:45 to 2024-11-11 11:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 35/640: 2024-11-11 11:01:45 to 2024-11-11 13:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 36/640: 2024-11-11 13:01:45 to 2024-11-11 15:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 37/640: 2024-11-11 15:01:45 to 2024-11-11 17:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 38/640: 2024-11-11 17:01:45 to 2024-11-11 19:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 39/640: 2024-11-11 19:01:45 to 2024-11-11 21:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 40/640: 2024-11-11 21:01:45 to 2024-11-11 23:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 41/640: 2024-11-11 23:01:45 to 2024-11-12 01:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 42/640: 2024-11-12 01:01:45 to 2024-11-12 03:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 43/640: 2024-11-12 03:01:45 to 2024-11-12 05:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 44/640: 2024-11-12 05:01:45 to 2024-11-12 07:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 45/640: 2024-11-12 07:01:45 to 2024-11-12 09:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 46/640: 2024-11-12 09:01:45 to 2024-11-12 11:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 47/640: 2024-11-12 11:01:45 to 2024-11-12 13:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 48/640: 2024-11-12 13:01:45 to 2024-11-12 15:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 49/640: 2024-11-12 15:01:45 to 2024-11-12 17:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 50/640: 2024-11-12 17:01:45 to 2024-11-12 19:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 51/640: 2024-11-12 19:01:45 to 2024-11-12 21:01:45 ---
Memory before window: 1274.2 MB
  No trips in this window, skipping

--- Window 52/640: 2024-11-12 21:01:45 to 2024-11-12 23:01:45 ---
Memory before window: 1274.3 MB
  No trips in this window, skipping

--- Window 53/640: 2024-11-12 23:01:45 to 2024-11-13 01:01:45 ---
Memory before window: 1274.3 MB
  No trips in this window, skipping

--- Window 54/640: 2024-11-13 01:01:45 to 2024-11-13 03:01:45 ---
Memory before window: 1274.3 MB
  No trips in this window, skipping

--- Window 55/640: 2024-11-13 03:01:45 to 2024-11-13 05:01:45 ---
Memory before window: 1274.3 MB
  No trips in this window, skipping

--- Window 56/640: 2024-11-13 05:01:45 to 2024-11-13 07:01:45 ---
Memory before window: 1274.3 MB
  No trips in this window, skipping

--- Window 57/640: 2024-11-13 07:01:45 to 2024-11-13 09:01:45 ---
Memory before window: 1274.3 MB
  No trips in this window, skipping

--- Window 58/640: 2024-11-13 09:01:45 to 2024-11-13 11:01:45 ---
Memory before window: 1274.3 MB
  Found 2 trips in window
  Processing 2 trips in 1 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1274.3 MB
  Memory before neighbor processing: 1274.4 MB
  Initial memory: 1274.4 MB
  Processing cell batch 1/1 (1 cells)
  Final memory: 1274.5 MB
  ✅ Generated 6 feature rows
Memory after window: 1274.5 MB

--- Window 59/640: 2024-11-13 11:01:45 to 2024-11-13 13:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 60/640: 2024-11-13 13:01:45 to 2024-11-13 15:01:45 ---
Memory before window: 1274.5 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  No trips in this window, skipping

--- Window 61/640: 2024-11-13 15:01:45 to 2024-11-13 17:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 62/640: 2024-11-13 17:01:45 to 2024-11-13 19:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 63/640: 2024-11-13 19:01:45 to 2024-11-13 21:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 64/640: 2024-11-13 21:01:45 to 2024-11-13 23:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 65/640: 2024-11-13 23:01:45 to 2024-11-14 01:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 66/640: 2024-11-14 01:01:45 to 2024-11-14 03:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 67/640: 2024-11-14 03:01:45 to 2024-11-14 05:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 68/640: 2024-11-14 05:01:45 to 2024-11-14 07:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 69/640: 2024-11-14 07:01:45 to 2024-11-14 09:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 70/640: 2024-11-14 09:01:45 to 2024-11-14 11:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 71/640: 2024-11-14 11:01:45 to 2024-11-14 13:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 72/640: 2024-11-14 13:01:45 to 2024-11-14 15:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 73/640: 2024-11-14 15:01:45 to 2024-11-14 17:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 74/640: 2024-11-14 17:01:45 to 2024-11-14 19:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 75/640: 2024-11-14 19:01:45 to 2024-11-14 21:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 76/640: 2024-11-14 21:01:45 to 2024-11-14 23:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 77/640: 2024-11-14 23:01:45 to 2024-11-15 01:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 78/640: 2024-11-15 01:01:45 to 2024-11-15 03:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 79/640: 2024-11-15 03:01:45 to 2024-11-15 05:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 80/640: 2024-11-15 05:01:45 to 2024-11-15 07:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 81/640: 2024-11-15 07:01:45 to 2024-11-15 09:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 82/640: 2024-11-15 09:01:45 to 2024-11-15 11:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 83/640: 2024-11-15 11:01:45 to 2024-11-15 13:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 84/640: 2024-11-15 13:01:45 to 2024-11-15 15:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 85/640: 2024-11-15 15:01:45 to 2024-11-15 17:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 86/640: 2024-11-15 17:01:45 to 2024-11-15 19:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 87/640: 2024-11-15 19:01:45 to 2024-11-15 21:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 88/640: 2024-11-15 21:01:45 to 2024-11-15 23:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 89/640: 2024-11-15 23:01:45 to 2024-11-16 01:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 90/640: 2024-11-16 01:01:45 to 2024-11-16 03:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 91/640: 2024-11-16 03:01:45 to 2024-11-16 05:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 92/640: 2024-11-16 05:01:45 to 2024-11-16 07:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 93/640: 2024-11-16 07:01:45 to 2024-11-16 09:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 94/640: 2024-11-16 09:01:45 to 2024-11-16 11:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 95/640: 2024-11-16 11:01:45 to 2024-11-16 13:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 96/640: 2024-11-16 13:01:45 to 2024-11-16 15:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 97/640: 2024-11-16 15:01:45 to 2024-11-16 17:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 98/640: 2024-11-16 17:01:45 to 2024-11-16 19:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 99/640: 2024-11-16 19:01:45 to 2024-11-16 21:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 100/640: 2024-11-16 21:01:45 to 2024-11-16 23:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 101/640: 2024-11-16 23:01:45 to 2024-11-17 01:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 102/640: 2024-11-17 01:01:45 to 2024-11-17 03:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 103/640: 2024-11-17 03:01:45 to 2024-11-17 05:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 104/640: 2024-11-17 05:01:45 to 2024-11-17 07:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 105/640: 2024-11-17 07:01:45 to 2024-11-17 09:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 106/640: 2024-11-17 09:01:45 to 2024-11-17 11:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 107/640: 2024-11-17 11:01:45 to 2024-11-17 13:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 108/640: 2024-11-17 13:01:45 to 2024-11-17 15:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 109/640: 2024-11-17 15:01:45 to 2024-11-17 17:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 110/640: 2024-11-17 17:01:45 to 2024-11-17 19:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 111/640: 2024-11-17 19:01:45 to 2024-11-17 21:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 112/640: 2024-11-17 21:01:45 to 2024-11-17 23:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 113/640: 2024-11-17 23:01:45 to 2024-11-18 01:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 114/640: 2024-11-18 01:01:45 to 2024-11-18 03:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 115/640: 2024-11-18 03:01:45 to 2024-11-18 05:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 116/640: 2024-11-18 05:01:45 to 2024-11-18 07:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 117/640: 2024-11-18 07:01:45 to 2024-11-18 09:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 118/640: 2024-11-18 09:01:45 to 2024-11-18 11:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 119/640: 2024-11-18 11:01:45 to 2024-11-18 13:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 120/640: 2024-11-18 13:01:45 to 2024-11-18 15:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 121/640: 2024-11-18 15:01:45 to 2024-11-18 17:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 122/640: 2024-11-18 17:01:45 to 2024-11-18 19:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 123/640: 2024-11-18 19:01:45 to 2024-11-18 21:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 124/640: 2024-11-18 21:01:45 to 2024-11-18 23:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 125/640: 2024-11-18 23:01:45 to 2024-11-19 01:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 126/640: 2024-11-19 01:01:45 to 2024-11-19 03:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 127/640: 2024-11-19 03:01:45 to 2024-11-19 05:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 128/640: 2024-11-19 05:01:45 to 2024-11-19 07:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 129/640: 2024-11-19 07:01:45 to 2024-11-19 09:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 130/640: 2024-11-19 09:01:45 to 2024-11-19 11:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 131/640: 2024-11-19 11:01:45 to 2024-11-19 13:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 132/640: 2024-11-19 13:01:45 to 2024-11-19 15:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 133/640: 2024-11-19 15:01:45 to 2024-11-19 17:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 134/640: 2024-11-19 17:01:45 to 2024-11-19 19:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 135/640: 2024-11-19 19:01:45 to 2024-11-19 21:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 136/640: 2024-11-19 21:01:45 to 2024-11-19 23:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 137/640: 2024-11-19 23:01:45 to 2024-11-20 01:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 138/640: 2024-11-20 01:01:45 to 2024-11-20 03:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 139/640: 2024-11-20 03:01:45 to 2024-11-20 05:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 140/640: 2024-11-20 05:01:45 to 2024-11-20 07:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 141/640: 2024-11-20 07:01:45 to 2024-11-20 09:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 142/640: 2024-11-20 09:01:45 to 2024-11-20 11:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 143/640: 2024-11-20 11:01:45 to 2024-11-20 13:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 144/640: 2024-11-20 13:01:45 to 2024-11-20 15:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 145/640: 2024-11-20 15:01:45 to 2024-11-20 17:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 146/640: 2024-11-20 17:01:45 to 2024-11-20 19:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 147/640: 2024-11-20 19:01:45 to 2024-11-20 21:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 148/640: 2024-11-20 21:01:45 to 2024-11-20 23:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 149/640: 2024-11-20 23:01:45 to 2024-11-21 01:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 150/640: 2024-11-21 01:01:45 to 2024-11-21 03:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 151/640: 2024-11-21 03:01:45 to 2024-11-21 05:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 152/640: 2024-11-21 05:01:45 to 2024-11-21 07:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 153/640: 2024-11-21 07:01:45 to 2024-11-21 09:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 154/640: 2024-11-21 09:01:45 to 2024-11-21 11:01:45 ---
Memory before window: 1274.5 MB
  No trips in this window, skipping

--- Window 155/640: 2024-11-21 11:01:45 to 2024-11-21 13:01:45 ---
Memory before window: 1274.5 MB
  Found 1 trips in window
  Processing 1 trips in 1 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1274.6 MB
  Memory before neighbor processing: 1274.6 MB
  Initial memory: 1274.6 MB
  Processing cell batch 1/1 (1 cells)

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Final memory: 1274.6 MB
  ✅ Generated 1 feature rows
Memory after window: 1274.6 MB

--- Window 156/640: 2024-11-21 13:01:45 to 2024-11-21 15:01:45 ---
Memory before window: 1274.6 MB
  No trips in this window, skipping

--- Window 157/640: 2024-11-21 15:01:45 to 2024-11-21 17:01:45 ---
Memory before window: 1274.6 MB
  No trips in this window, skipping

--- Window 158/640: 2024-11-21 17:01:45 to 2024-11-21 19:01:45 ---
Memory before window: 1274.6 MB
  No trips in this window, skipping

--- Window 159/640: 2024-11-21 19:01:45 to 2024-11-21 21:01:45 ---
Memory before window: 1274.6 MB
  No trips in this window, skipping

--- Window 160/640: 2024-11-21 21:01:45 to 2024-11-21 23:01:45 ---
Memory before window: 1274.6 MB
  No trips in this window, skipping

--- Window 161/640: 2024-11-21 23:01:45 to 2024-11-22 01:01:45 ---
Memory before window: 1274.6 MB
  No trips in this window, skipping

--- Window 162/640: 2024-11-22 01:01:45 to 2024-11-22 03:01:45 ---
Memory before window: 1274.6 MB
  Found 1 trips in window
  Processing 1 trips in 1 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1274.7 MB
  Memory before neighbor processing: 1274.7 MB
  Initial memory: 1274.7 MB
  Processing cell batch 1/1 (1 cells)
  Final memory: 1274.7 MB
  ✅ Generated 1 feature rows
Memory after window: 1274.7 MB

--- Window 163/640: 2024-11-22 03:01:45 to 2024-11-22 05:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 164/640: 2024-11-22 05:01:45 to 2024-11-22 07:01:45 ---
Memory before window: 1274.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  No trips in this window, skipping

--- Window 165/640: 2024-11-22 07:01:45 to 2024-11-22 09:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 166/640: 2024-11-22 09:01:45 to 2024-11-22 11:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 167/640: 2024-11-22 11:01:45 to 2024-11-22 13:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 168/640: 2024-11-22 13:01:45 to 2024-11-22 15:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 169/640: 2024-11-22 15:01:45 to 2024-11-22 17:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 170/640: 2024-11-22 17:01:45 to 2024-11-22 19:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 171/640: 2024-11-22 19:01:45 to 2024-11-22 21:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 172/640: 2024-11-22 21:01:45 to 2024-11-22 23:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 173/640: 2024-11-22 23:01:45 to 2024-11-23 01:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 174/640: 2024-11-23 01:01:45 to 2024-11-23 03:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 175/640: 2024-11-23 03:01:45 to 2024-11-23 05:01:45 ---
Memory before window: 1274.7 MB
  Found 1 trips in window
  Processing 1 trips in 1 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1274.7 MB
  Memory before neighbor processing: 1274.7 MB
  Initial memory: 1274.7 MB
  Processing cell batch 1/1 (1 cells)
  Final memory: 1274.7 MB
  ✅ Generated 1 feature rows

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

Memory after window: 1274.7 MB

--- Window 176/640: 2024-11-23 05:01:45 to 2024-11-23 07:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 177/640: 2024-11-23 07:01:45 to 2024-11-23 09:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 178/640: 2024-11-23 09:01:45 to 2024-11-23 11:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 179/640: 2024-11-23 11:01:45 to 2024-11-23 13:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 180/640: 2024-11-23 13:01:45 to 2024-11-23 15:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 181/640: 2024-11-23 15:01:45 to 2024-11-23 17:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 182/640: 2024-11-23 17:01:45 to 2024-11-23 19:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 183/640: 2024-11-23 19:01:45 to 2024-11-23 21:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 184/640: 2024-11-23 21:01:45 to 2024-11-23 23:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 185/640: 2024-11-23 23:01:45 to 2024-11-24 01:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 186/640: 2024-11-24 01:01:45 to 2024-11-24 03:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 187/640: 2024-11-24 03:01:45 to 2024-11-24 05:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 188/640: 2024-11-24 05:01:45 to 2024-11-24 07:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 189/640: 2024-11-24 07:01:45 to 2024-11-24 09:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 190/640: 2024-11-24 09:01:45 to 2024-11-24 11:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 191/640: 2024-11-24 11:01:45 to 2024-11-24 13:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 192/640: 2024-11-24 13:01:45 to 2024-11-24 15:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 193/640: 2024-11-24 15:01:45 to 2024-11-24 17:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 194/640: 2024-11-24 17:01:45 to 2024-11-24 19:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 195/640: 2024-11-24 19:01:45 to 2024-11-24 21:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 196/640: 2024-11-24 21:01:45 to 2024-11-24 23:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 197/640: 2024-11-24 23:01:45 to 2024-11-25 01:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 198/640: 2024-11-25 01:01:45 to 2024-11-25 03:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 199/640: 2024-11-25 03:01:45 to 2024-11-25 05:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 200/640: 2024-11-25 05:01:45 to 2024-11-25 07:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 201/640: 2024-11-25 07:01:45 to 2024-11-25 09:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 202/640: 2024-11-25 09:01:45 to 2024-11-25 11:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 203/640: 2024-11-25 11:01:45 to 2024-11-25 13:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 204/640: 2024-11-25 13:01:45 to 2024-11-25 15:01:45 ---
Memory before window: 1274.7 MB
  Found 1 trips in window
  Processing 1 trips in 1 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1274.7 MB
  Memory before neighbor processing: 1274.7 MB
  Initial memory: 1274.7 MB
  Processing cell batch 1/1 (1 cells)
  Final memory: 1274.7 MB
  ✅ Generated 1 feature rows
Memory after window: 1274.7 MB

--- Window 205/640: 2024-11-25 15:01:45 to 2024-11-25 17:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 206/640: 2024-11-25 17:01:45 to 2024-11-25 19:01:45 ---
Memory before window: 1274.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  No trips in this window, skipping

--- Window 207/640: 2024-11-25 19:01:45 to 2024-11-25 21:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 208/640: 2024-11-25 21:01:45 to 2024-11-25 23:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 209/640: 2024-11-25 23:01:45 to 2024-11-26 01:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 210/640: 2024-11-26 01:01:45 to 2024-11-26 03:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 211/640: 2024-11-26 03:01:45 to 2024-11-26 05:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 212/640: 2024-11-26 05:01:45 to 2024-11-26 07:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 213/640: 2024-11-26 07:01:45 to 2024-11-26 09:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 214/640: 2024-11-26 09:01:45 to 2024-11-26 11:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 215/640: 2024-11-26 11:01:45 to 2024-11-26 13:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 216/640: 2024-11-26 13:01:45 to 2024-11-26 15:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 217/640: 2024-11-26 15:01:45 to 2024-11-26 17:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 218/640: 2024-11-26 17:01:45 to 2024-11-26 19:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 219/640: 2024-11-26 19:01:45 to 2024-11-26 21:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 220/640: 2024-11-26 21:01:45 to 2024-11-26 23:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 221/640: 2024-11-26 23:01:45 to 2024-11-27 01:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 222/640: 2024-11-27 01:01:45 to 2024-11-27 03:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 223/640: 2024-11-27 03:01:45 to 2024-11-27 05:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 224/640: 2024-11-27 05:01:45 to 2024-11-27 07:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 225/640: 2024-11-27 07:01:45 to 2024-11-27 09:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 226/640: 2024-11-27 09:01:45 to 2024-11-27 11:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 227/640: 2024-11-27 11:01:45 to 2024-11-27 13:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 228/640: 2024-11-27 13:01:45 to 2024-11-27 15:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 229/640: 2024-11-27 15:01:45 to 2024-11-27 17:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 230/640: 2024-11-27 17:01:45 to 2024-11-27 19:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 231/640: 2024-11-27 19:01:45 to 2024-11-27 21:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 232/640: 2024-11-27 21:01:45 to 2024-11-27 23:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 233/640: 2024-11-27 23:01:45 to 2024-11-28 01:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 234/640: 2024-11-28 01:01:45 to 2024-11-28 03:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 235/640: 2024-11-28 03:01:45 to 2024-11-28 05:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 236/640: 2024-11-28 05:01:45 to 2024-11-28 07:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 237/640: 2024-11-28 07:01:45 to 2024-11-28 09:01:45 ---
Memory before window: 1274.7 MB
  Found 1 trips in window
  Processing 1 trips in 1 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1274.7 MB
  Memory before neighbor processing: 1274.7 MB
  Initial memory: 1274.7 MB
  Processing cell batch 1/1 (1 cells)
  Final memory: 1274.7 MB
  ✅ Generated 1 feature rows
Memory after window: 1274.7 MB

--- Window 238/640: 2024-11-28 09:01:45 to 2024-11-28 11:01:45 ---
Memory before window: 1274.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  No trips in this window, skipping

--- Window 239/640: 2024-11-28 11:01:45 to 2024-11-28 13:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 240/640: 2024-11-28 13:01:45 to 2024-11-28 15:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 241/640: 2024-11-28 15:01:45 to 2024-11-28 17:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 242/640: 2024-11-28 17:01:45 to 2024-11-28 19:01:45 ---
Memory before window: 1274.7 MB
  Found 1 trips in window
  Processing 1 trips in 1 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1274.7 MB
  Memory before neighbor processing: 1274.7 MB
  Initial memory: 1274.7 MB
  Processing cell batch 1/1 (1 cells)
  Final memory: 1274.7 MB
  ✅ Generated 1 feature rows

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

Memory after window: 1274.7 MB

--- Window 243/640: 2024-11-28 19:01:45 to 2024-11-28 21:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 244/640: 2024-11-28 21:01:45 to 2024-11-28 23:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 245/640: 2024-11-28 23:01:45 to 2024-11-29 01:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 246/640: 2024-11-29 01:01:45 to 2024-11-29 03:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 247/640: 2024-11-29 03:01:45 to 2024-11-29 05:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 248/640: 2024-11-29 05:01:45 to 2024-11-29 07:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 249/640: 2024-11-29 07:01:45 to 2024-11-29 09:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 250/640: 2024-11-29 09:01:45 to 2024-11-29 11:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 251/640: 2024-11-29 11:01:45 to 2024-11-29 13:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 252/640: 2024-11-29 13:01:45 to 2024-11-29 15:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 253/640: 2024-11-29 15:01:45 to 2024-11-29 17:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 254/640: 2024-11-29 17:01:45 to 2024-11-29 19:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 255/640: 2024-11-29 19:01:45 to 2024-11-29 21:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 256/640: 2024-11-29 21:01:45 to 2024-11-29 23:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 257/640: 2024-11-29 23:01:45 to 2024-11-30 01:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 258/640: 2024-11-30 01:01:45 to 2024-11-30 03:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 259/640: 2024-11-30 03:01:45 to 2024-11-30 05:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 260/640: 2024-11-30 05:01:45 to 2024-11-30 07:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 261/640: 2024-11-30 07:01:45 to 2024-11-30 09:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 262/640: 2024-11-30 09:01:45 to 2024-11-30 11:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 263/640: 2024-11-30 11:01:45 to 2024-11-30 13:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 264/640: 2024-11-30 13:01:45 to 2024-11-30 15:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 265/640: 2024-11-30 15:01:45 to 2024-11-30 17:01:45 ---
Memory before window: 1274.7 MB
  No trips in this window, skipping

--- Window 266/640: 2024-11-30 17:01:45 to 2024-11-30 19:01:45 ---
Memory before window: 1274.7 MB
  Found 1 trips in window
  Processing 1 trips in 1 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1274.8 MB
  Memory before neighbor processing: 1274.8 MB
  Initial memory: 1274.8 MB
  Processing cell batch 1/1 (1 cells)
  Final memory: 1274.8 MB
  ✅ Generated 1 feature rows
Memory after window: 1274.8 MB

--- Window 267/640: 2024-11-30 19:01:45 to 2024-11-30 21:01:45 ---
Memory before window: 1274.8 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Found 2 trips in window
  Processing 2 trips in 2 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1274.8 MB
  Memory before neighbor processing: 1274.8 MB
  Initial memory: 1274.8 MB
  Processing cell batch 1/1 (2 cells)
  Final memory: 1274.8 MB
  ✅ Generated 8 feature rows
Memory after window: 1274.8 MB

--- Window 268/640: 2024-11-30 21:01:45 to 2024-11-30 23:01:45 ---
Memory before window: 1274.8 MB
  No trips in this window, skipping

--- Window 269/640: 2024-11-30 23:01:45 to 2024-12-01 01:01:45 ---
Memory before window: 1274.8 MB
  Found 9794 trips in window
  Processing 8396 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1284.2 MB
  Memory before neighbor processing: 1290.4 MB
  Initial memory: 1290.8 MB
  Processing cell batch 1/5 (30 cells)

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1317.0 MB
  ✅ Generated 3000 feature rows
Memory after window: 1317.0 MB

--- Window 270/640: 2024-12-01 01:01:45 to 2024-12-01 03:01:45 ---
Memory before window: 1317.0 MB
  Found 16191 trips in window
  Processing 14179 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1318.2 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1319.0 MB
  Initial memory: 1319.2 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1335.8 MB
  ✅ Generated 3750 feature rows
Memory after window: 1335.8 MB

--- Window 271/640: 2024-12-01 03:01:45 to 2024-12-01 05:01:45 ---
Memory before window: 1335.8 MB
  Found 14893 trips in window
  Processing 12724 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1337.9 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1338.7 MB
  Initial memory: 1338.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1340.2 MB
  ✅ Generated 3750 feature rows
Memory after window: 1340.2 MB

--- Window 272/640: 2024-12-01 05:01:45 to 2024-12-01 07:01:45 ---
Memory before window: 1340.2 MB
  Found 19869 trips in window
  Processing 16085 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1343.2 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1343.4 MB
  Initial memory: 1343.4 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1356.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 1356.0 MB

--- Window 273/640: 2024-12-01 07:01:45 to 2024-12-01 09:01:45 ---
Memory before window: 1356.0 MB
  Found 28172 trips in window
  Processing 21283 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1359.3 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1359.3 MB
  Initial memory: 1359.3 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1361.7 MB
  ✅ Generated 3750 feature rows
Memory after window: 1361.7 MB

--- Window 274/640: 2024-12-01 09:01:45 to 2024-12-01 11:01:45 ---
Memory before window: 1361.7 MB
  Found 34416 trips in window
  Processing 25758 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1363.4 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1363.6 MB
  Initial memory: 1363.6 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1365.2 MB
  ✅ Generated 3750 feature rows
Memory after window: 1365.2 MB

--- Window 275/640: 2024-12-01 11:01:45 to 2024-12-01 13:01:45 ---
Memory before window: 1365.2 MB
  Found 38703 trips in window
  Processing 29989 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1366.2 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1366.2 MB
  Initial memory: 1366.2 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1369.2 MB
  ✅ Generated 3750 feature rows
Memory after window: 1369.2 MB

--- Window 276/640: 2024-12-01 13:01:45 to 2024-12-01 15:01:45 ---
Memory before window: 1369.2 MB
  Found 39968 trips in window
  Processing 31038 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1369.9 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1369.9 MB
  Initial memory: 1369.9 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1370.5 MB
  ✅ Generated 3750 feature rows
Memory after window: 1370.5 MB

--- Window 277/640: 2024-12-01 15:01:45 to 2024-12-01 17:01:45 ---
Memory before window: 1370.5 MB
  Found 41129 trips in window
  Processing 32218 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1371.0 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1371.0 MB
  Initial memory: 1371.0 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1371.6 MB
  ✅ Generated 3750 feature rows
Memory after window: 1371.6 MB

--- Window 278/640: 2024-12-01 17:01:45 to 2024-12-01 19:01:45 ---
Memory before window: 1371.6 MB
  Found 41271 trips in window
  Processing 32300 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1372.0 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1372.0 MB
  Initial memory: 1372.0 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1372.4 MB
  ✅ Generated 3750 feature rows
Memory after window: 1372.4 MB

--- Window 279/640: 2024-12-01 19:01:45 to 2024-12-01 21:01:45 ---
Memory before window: 1372.4 MB
  Found 34126 trips in window
  Processing 27254 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1372.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1372.7 MB
  Initial memory: 1372.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1373.2 MB
  ✅ Generated 3750 feature rows
Memory after window: 1373.2 MB

--- Window 280/640: 2024-12-01 21:01:45 to 2024-12-01 23:01:45 ---
Memory before window: 1373.2 MB
  Found 26488 trips in window
  Processing 21855 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1373.4 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1373.5 MB
  Initial memory: 1373.5 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1375.6 MB
  ✅ Generated 3750 feature rows
Memory after window: 1375.6 MB

--- Window 281/640: 2024-12-01 23:01:45 to 2024-12-02 01:01:45 ---
Memory before window: 1375.6 MB
  Found 17723 trips in window
  Processing 15126 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1375.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1375.7 MB
  Initial memory: 1375.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1375.9 MB
  ✅ Generated 3750 feature rows
Memory after window: 1375.9 MB

--- Window 282/640: 2024-12-02 01:01:45 to 2024-12-02 03:01:45 ---
Memory before window: 1375.9 MB
  Found 11538 trips in window
  Processing 10007 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1376.0 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1376.4 MB
  Initial memory: 1376.4 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1379.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 1379.0 MB

--- Window 283/640: 2024-12-02 03:01:45 to 2024-12-02 05:01:45 ---
Memory before window: 1379.0 MB
  Found 12047 trips in window
  Processing 10001 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1379.1 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1379.1 MB
  Initial memory: 1379.1 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1379.3 MB
  ✅ Generated 3750 feature rows
Memory after window: 1379.3 MB

--- Window 284/640: 2024-12-02 05:01:45 to 2024-12-02 07:01:45 ---
Memory before window: 1379.3 MB
  Found 22644 trips in window
  Processing 17698 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1379.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1379.7 MB
  Initial memory: 1379.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1382.1 MB
  ✅ Generated 3750 feature rows
Memory after window: 1382.1 MB

--- Window 285/640: 2024-12-02 07:01:45 to 2024-12-02 09:01:45 ---
Memory before window: 1382.1 MB
  Found 32928 trips in window
  Processing 24314 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1382.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1382.7 MB
  Initial memory: 1382.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1384.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 1384.0 MB

--- Window 286/640: 2024-12-02 09:01:45 to 2024-12-02 11:01:45 ---
Memory before window: 1384.0 MB
  Found 35920 trips in window
  Processing 27427 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1384.4 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1384.4 MB
  Initial memory: 1384.4 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1387.5 MB
  ✅ Generated 3750 feature rows
Memory after window: 1387.5 MB

--- Window 287/640: 2024-12-02 11:01:45 to 2024-12-02 13:01:45 ---
Memory before window: 1387.5 MB
  Found 37219 trips in window
  Processing 29055 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1387.8 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1387.8 MB
  Initial memory: 1387.8 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1389.9 MB
  ✅ Generated 3750 feature rows
Memory after window: 1389.9 MB

--- Window 288/640: 2024-12-02 13:01:45 to 2024-12-02 15:01:45 ---
Memory before window: 1389.9 MB
  Found 40230 trips in window
  Processing 31692 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1390.5 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1390.5 MB
  Initial memory: 1390.5 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1391.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 1391.0 MB

--- Window 289/640: 2024-12-02 15:01:45 to 2024-12-02 17:01:45 ---
Memory before window: 1391.0 MB
  Found 42567 trips in window
  Processing 33021 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1391.5 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1391.5 MB
  Initial memory: 1391.5 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1393.3 MB
  ✅ Generated 3750 feature rows
Memory after window: 1393.3 MB

--- Window 290/640: 2024-12-02 17:01:45 to 2024-12-02 19:01:45 ---
Memory before window: 1393.3 MB
  Found 42319 trips in window
  Processing 33189 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1393.6 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1393.7 MB
  Initial memory: 1393.8 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1395.1 MB
  ✅ Generated 3750 feature rows
Memory after window: 1395.1 MB

--- Window 291/640: 2024-12-02 19:01:45 to 2024-12-02 21:01:45 ---
Memory before window: 1395.1 MB
  Found 36709 trips in window
  Processing 28760 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1395.4 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1395.4 MB
  Initial memory: 1395.4 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1397.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 1397.0 MB

--- Window 292/640: 2024-12-02 21:01:45 to 2024-12-02 23:01:45 ---
Memory before window: 1397.0 MB
  Found 26336 trips in window
  Processing 21869 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1397.2 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1397.2 MB
  Initial memory: 1397.2 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1397.5 MB
  ✅ Generated 3750 feature rows
Memory after window: 1397.5 MB

--- Window 293/640: 2024-12-02 23:01:45 to 2024-12-03 01:01:45 ---
Memory before window: 1397.5 MB
  Found 16837 trips in window
  Processing 14712 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1397.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1397.7 MB
  Initial memory: 1397.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1398.9 MB
  ✅ Generated 3750 feature rows
Memory after window: 1398.9 MB

--- Window 294/640: 2024-12-03 01:01:45 to 2024-12-03 03:01:45 ---
Memory before window: 1398.9 MB
  Found 10938 trips in window
  Processing 9764 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1400.0 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1400.1 MB
  Initial memory: 1400.1 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1400.4 MB
  ✅ Generated 3750 feature rows
Memory after window: 1400.4 MB

--- Window 295/640: 2024-12-03 03:01:45 to 2024-12-03 05:01:45 ---
Memory before window: 1400.4 MB
  Found 11454 trips in window
  Processing 9935 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1400.5 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1400.5 MB
  Initial memory: 1400.5 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1401.6 MB
  ✅ Generated 3750 feature rows
Memory after window: 1401.6 MB

--- Window 296/640: 2024-12-03 05:01:45 to 2024-12-03 07:01:45 ---
Memory before window: 1401.6 MB
  Found 22701 trips in window
  Processing 17770 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1401.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1401.7 MB
  Initial memory: 1401.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1402.8 MB
  ✅ Generated 3750 feature rows
Memory after window: 1402.8 MB

--- Window 297/640: 2024-12-03 07:01:45 to 2024-12-03 09:01:45 ---
Memory before window: 1402.8 MB
  Found 34186 trips in window
  Processing 25344 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1403.2 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1403.3 MB
  Initial memory: 1403.3 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1403.8 MB
  ✅ Generated 3750 feature rows
Memory after window: 1403.8 MB

--- Window 298/640: 2024-12-03 09:01:45 to 2024-12-03 11:01:45 ---
Memory before window: 1403.8 MB
  Found 38089 trips in window
  Processing 29526 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1404.1 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1404.1 MB
  Initial memory: 1404.1 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1405.3 MB
  ✅ Generated 3750 feature rows
Memory after window: 1405.3 MB

--- Window 299/640: 2024-12-03 11:01:45 to 2024-12-03 13:01:45 ---
Memory before window: 1405.3 MB
  Found 36896 trips in window
  Processing 29868 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1405.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1405.8 MB
  Initial memory: 1405.8 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1407.6 MB
  ✅ Generated 3750 feature rows
Memory after window: 1407.6 MB

--- Window 300/640: 2024-12-03 13:01:45 to 2024-12-03 15:01:45 ---
Memory before window: 1407.6 MB
  Found 41681 trips in window
  Processing 33465 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1408.0 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1408.1 MB
  Initial memory: 1408.1 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1410.1 MB
  ✅ Generated 3750 feature rows
Memory after window: 1410.1 MB

--- Window 301/640: 2024-12-03 15:01:45 to 2024-12-03 17:01:45 ---
Memory before window: 1410.1 MB
  Found 43877 trips in window
  Processing 34929 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1410.6 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1410.6 MB
  Initial memory: 1410.6 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1413.8 MB
  ✅ Generated 3750 feature rows
Memory after window: 1413.8 MB

--- Window 302/640: 2024-12-03 17:01:45 to 2024-12-03 19:01:45 ---
Memory before window: 1413.8 MB
  Found 42331 trips in window
  Processing 33440 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1414.2 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1414.2 MB
  Initial memory: 1414.2 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1415.2 MB
  ✅ Generated 3750 feature rows
Memory after window: 1415.2 MB

--- Window 303/640: 2024-12-03 19:01:45 to 2024-12-03 21:01:45 ---
Memory before window: 1415.2 MB
  Found 38166 trips in window
  Processing 31163 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1415.5 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1415.5 MB
  Initial memory: 1415.5 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1415.6 MB
  ✅ Generated 3750 feature rows
Memory after window: 1415.6 MB

--- Window 304/640: 2024-12-03 21:01:45 to 2024-12-03 23:01:45 ---
Memory before window: 1415.6 MB
  Found 27428 trips in window
  Processing 22948 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1415.8 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1416.1 MB
  Initial memory: 1416.1 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1416.3 MB
  ✅ Generated 3750 feature rows
Memory after window: 1416.3 MB

--- Window 305/640: 2024-12-03 23:01:45 to 2024-12-04 01:01:45 ---
Memory before window: 1416.3 MB
  Found 17749 trips in window
  Processing 15561 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1416.5 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1416.7 MB
  Initial memory: 1416.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1416.9 MB
  ✅ Generated 3750 feature rows
Memory after window: 1416.9 MB

--- Window 306/640: 2024-12-04 01:01:45 to 2024-12-04 03:01:45 ---
Memory before window: 1416.9 MB
  Found 11963 trips in window
  Processing 10751 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1417.0 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1417.1 MB
  Initial memory: 1417.1 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1417.4 MB
  ✅ Generated 3750 feature rows
Memory after window: 1417.4 MB

--- Window 307/640: 2024-12-04 03:01:45 to 2024-12-04 05:01:45 ---
Memory before window: 1417.4 MB
  Found 13082 trips in window
  Processing 11519 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1417.6 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1417.6 MB
  Initial memory: 1417.6 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1418.4 MB
  ✅ Generated 3750 feature rows
Memory after window: 1418.4 MB

--- Window 308/640: 2024-12-04 05:01:45 to 2024-12-04 07:01:45 ---
Memory before window: 1418.4 MB
  Found 24157 trips in window
  Processing 19507 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1418.6 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1418.6 MB
  Initial memory: 1418.6 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1419.7 MB
  ✅ Generated 3750 feature rows
Memory after window: 1419.7 MB

--- Window 309/640: 2024-12-04 07:01:45 to 2024-12-04 09:01:45 ---
Memory before window: 1419.7 MB
  Found 34938 trips in window
  Processing 26657 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1420.0 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1420.0 MB
  Initial memory: 1420.0 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1421.2 MB
  ✅ Generated 3750 feature rows
Memory after window: 1421.2 MB

--- Window 310/640: 2024-12-04 09:01:45 to 2024-12-04 11:01:45 ---
Memory before window: 1421.2 MB
  Found 38036 trips in window
  Processing 29855 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1421.4 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1421.4 MB
  Initial memory: 1421.4 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1423.5 MB
  ✅ Generated 3750 feature rows
Memory after window: 1423.5 MB

--- Window 311/640: 2024-12-04 11:01:45 to 2024-12-04 13:01:45 ---
Memory before window: 1423.5 MB
  Found 37018 trips in window
  Processing 30040 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1423.9 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1424.0 MB
  Initial memory: 1424.0 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1425.7 MB
  ✅ Generated 3750 feature rows
Memory after window: 1425.7 MB

--- Window 312/640: 2024-12-04 13:01:45 to 2024-12-04 15:01:45 ---
Memory before window: 1425.7 MB
  Found 41689 trips in window
  Processing 33433 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1426.2 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1426.2 MB
  Initial memory: 1426.3 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1428.9 MB
  ✅ Generated 3750 feature rows
Memory after window: 1428.9 MB

--- Window 313/640: 2024-12-04 15:01:45 to 2024-12-04 17:01:45 ---
Memory before window: 1428.9 MB
  Found 45726 trips in window
  Processing 36931 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1429.6 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1429.9 MB
  Initial memory: 1429.9 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1431.9 MB
  ✅ Generated 3750 feature rows
Memory after window: 1431.9 MB

--- Window 314/640: 2024-12-04 17:01:45 to 2024-12-04 19:01:45 ---
Memory before window: 1431.9 MB
  Found 46285 trips in window
  Processing 36886 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1432.3 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1432.3 MB
  Initial memory: 1432.3 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1433.6 MB
  ✅ Generated 3750 feature rows
Memory after window: 1433.6 MB

--- Window 315/640: 2024-12-04 19:01:45 to 2024-12-04 21:01:45 ---
Memory before window: 1433.6 MB
  Found 41955 trips in window
  Processing 34161 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1434.0 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1434.0 MB
  Initial memory: 1434.0 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1436.3 MB
  ✅ Generated 3750 feature rows
Memory after window: 1436.3 MB

--- Window 316/640: 2024-12-04 21:01:45 to 2024-12-04 23:01:45 ---
Memory before window: 1436.3 MB
  Found 32390 trips in window
  Processing 26841 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1436.5 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1436.5 MB
  Initial memory: 1436.5 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1436.7 MB
  ✅ Generated 3750 feature rows
Memory after window: 1436.7 MB

--- Window 317/640: 2024-12-04 23:01:45 to 2024-12-05 01:01:45 ---
Memory before window: 1436.7 MB
  Found 21356 trips in window
  Processing 18304 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1436.9 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1436.9 MB
  Initial memory: 1436.9 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1437.3 MB
  ✅ Generated 3750 feature rows
Memory after window: 1437.3 MB

--- Window 318/640: 2024-12-05 01:01:45 to 2024-12-05 03:01:45 ---
Memory before window: 1437.3 MB
  Found 15120 trips in window
  Processing 13132 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1437.4 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1437.4 MB
  Initial memory: 1437.4 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1437.8 MB
  ✅ Generated 3750 feature rows
Memory after window: 1437.8 MB

--- Window 319/640: 2024-12-05 03:01:45 to 2024-12-05 05:01:45 ---
Memory before window: 1437.8 MB
  Found 14398 trips in window
  Processing 12670 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1437.9 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1438.5 MB
  Initial memory: 1438.5 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1438.5 MB
  ✅ Generated 3750 feature rows
Memory after window: 1438.5 MB

--- Window 320/640: 2024-12-05 05:01:45 to 2024-12-05 07:01:45 ---
Memory before window: 1438.5 MB
  Found 22875 trips in window
  Processing 18508 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1438.6 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1438.6 MB
  Initial memory: 1438.6 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1438.8 MB
  ✅ Generated 3750 feature rows
Memory after window: 1438.8 MB

--- Window 321/640: 2024-12-05 07:01:45 to 2024-12-05 09:01:45 ---
Memory before window: 1438.8 MB
  Found 30352 trips in window
  Processing 23266 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1439.1 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1439.1 MB
  Initial memory: 1439.1 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1439.3 MB
  ✅ Generated 3750 feature rows
Memory after window: 1439.3 MB

--- Window 322/640: 2024-12-05 09:01:45 to 2024-12-05 11:01:45 ---
Memory before window: 1439.3 MB
  Found 35924 trips in window
  Processing 27448 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1439.5 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1439.5 MB
  Initial memory: 1439.5 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1441.3 MB
  ✅ Generated 3750 feature rows
Memory after window: 1441.3 MB

--- Window 323/640: 2024-12-05 11:01:45 to 2024-12-05 13:01:45 ---
Memory before window: 1441.3 MB
  Found 39542 trips in window
  Processing 31413 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1441.6 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1441.6 MB
  Initial memory: 1441.6 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1441.8 MB
  ✅ Generated 3750 feature rows
Memory after window: 1441.8 MB

--- Window 324/640: 2024-12-05 13:01:45 to 2024-12-05 15:01:45 ---
Memory before window: 1441.8 MB
  Found 40172 trips in window
  Processing 32177 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1442.2 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1442.5 MB
  Initial memory: 1442.5 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1444.6 MB
  ✅ Generated 3750 feature rows
Memory after window: 1444.6 MB

--- Window 325/640: 2024-12-05 15:01:45 to 2024-12-05 17:01:45 ---
Memory before window: 1444.6 MB
  Found 42834 trips in window
  Processing 34175 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1444.9 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1444.9 MB
  Initial memory: 1444.9 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1445.1 MB
  ✅ Generated 3750 feature rows
Memory after window: 1445.1 MB

--- Window 326/640: 2024-12-05 17:01:45 to 2024-12-05 19:01:45 ---
Memory before window: 1445.1 MB
  Found 41409 trips in window
  Processing 33306 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1445.5 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1445.6 MB
  Initial memory: 1445.6 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1446.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 1446.0 MB

--- Window 327/640: 2024-12-05 19:01:45 to 2024-12-05 21:01:45 ---
Memory before window: 1446.0 MB
  Found 34622 trips in window
  Processing 28471 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1446.3 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1446.3 MB
  Initial memory: 1446.3 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1448.2 MB
  ✅ Generated 3750 feature rows
Memory after window: 1448.2 MB

--- Window 328/640: 2024-12-05 21:01:45 to 2024-12-05 23:01:45 ---
Memory before window: 1448.2 MB
  Found 26313 trips in window
  Processing 22374 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1448.5 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1448.5 MB
  Initial memory: 1448.5 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1449.9 MB
  ✅ Generated 3750 feature rows
Memory after window: 1449.9 MB

--- Window 329/640: 2024-12-05 23:01:45 to 2024-12-06 01:01:45 ---
Memory before window: 1449.9 MB
  Found 17334 trips in window
  Processing 15302 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1450.0 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1450.0 MB
  Initial memory: 1450.0 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1450.2 MB
  ✅ Generated 3750 feature rows
Memory after window: 1450.2 MB

--- Window 330/640: 2024-12-06 01:01:45 to 2024-12-06 03:01:45 ---
Memory before window: 1450.2 MB
  Found 11752 trips in window
  Processing 10879 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1450.3 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1450.3 MB
  Initial memory: 1450.3 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1450.7 MB
  ✅ Generated 3750 feature rows
Memory after window: 1450.7 MB

--- Window 331/640: 2024-12-06 03:01:45 to 2024-12-06 05:01:45 ---
Memory before window: 1450.7 MB
  Found 12730 trips in window
  Processing 11134 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1450.8 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1450.9 MB
  Initial memory: 1450.9 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1451.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 1451.0 MB

--- Window 332/640: 2024-12-06 05:01:45 to 2024-12-06 07:01:45 ---
Memory before window: 1451.0 MB
  Found 23684 trips in window
  Processing 18906 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1451.2 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1451.2 MB
  Initial memory: 1451.2 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1451.4 MB
  ✅ Generated 3750 feature rows
Memory after window: 1451.4 MB

--- Window 333/640: 2024-12-06 07:01:45 to 2024-12-06 09:01:45 ---
Memory before window: 1451.4 MB
  Found 34939 trips in window
  Processing 27040 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1451.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1451.7 MB
  Initial memory: 1451.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1453.1 MB
  ✅ Generated 3750 feature rows
Memory after window: 1453.1 MB

--- Window 334/640: 2024-12-06 09:01:45 to 2024-12-06 11:01:45 ---
Memory before window: 1453.1 MB
  Found 38239 trips in window
  Processing 29660 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1453.2 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1453.3 MB
  Initial memory: 1453.3 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1454.4 MB
  ✅ Generated 3750 feature rows
Memory after window: 1454.4 MB

--- Window 335/640: 2024-12-06 11:01:45 to 2024-12-06 13:01:45 ---
Memory before window: 1454.4 MB
  Found 37712 trips in window
  Processing 29659 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1454.6 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1454.6 MB
  Initial memory: 1454.6 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1457.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 1457.0 MB

--- Window 336/640: 2024-12-06 13:01:45 to 2024-12-06 15:01:45 ---
Memory before window: 1457.0 MB
  Found 40680 trips in window
  Processing 32810 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1457.3 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1457.3 MB
  Initial memory: 1457.3 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1457.9 MB
  ✅ Generated 3750 feature rows
Memory after window: 1457.9 MB

--- Window 337/640: 2024-12-06 15:01:45 to 2024-12-06 17:01:45 ---
Memory before window: 1457.9 MB
  Found 44931 trips in window
  Processing 35820 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1458.1 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1458.1 MB
  Initial memory: 1458.1 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1460.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 1460.0 MB

--- Window 338/640: 2024-12-06 17:01:45 to 2024-12-06 19:01:45 ---
Memory before window: 1460.0 MB
  Found 45642 trips in window
  Processing 35796 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1460.3 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1460.3 MB
  Initial memory: 1460.3 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1461.1 MB
  ✅ Generated 3750 feature rows
Memory after window: 1461.1 MB

--- Window 339/640: 2024-12-06 19:01:45 to 2024-12-06 21:01:45 ---
Memory before window: 1461.1 MB
  Found 39366 trips in window
  Processing 30955 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1461.4 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1461.4 MB
  Initial memory: 1461.4 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1461.5 MB
  ✅ Generated 3750 feature rows
Memory after window: 1461.5 MB

--- Window 340/640: 2024-12-06 21:01:45 to 2024-12-06 23:01:45 ---
Memory before window: 1461.5 MB
  Found 30100 trips in window
  Processing 24923 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1461.6 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1461.7 MB
  Initial memory: 1461.9 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1464.5 MB
  ✅ Generated 3750 feature rows
Memory after window: 1464.5 MB

--- Window 341/640: 2024-12-06 23:01:45 to 2024-12-07 01:01:45 ---
Memory before window: 1464.5 MB
  Found 20114 trips in window
  Processing 17366 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1464.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1464.7 MB
  Initial memory: 1464.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1464.7 MB
  ✅ Generated 3750 feature rows
Memory after window: 1464.7 MB

--- Window 342/640: 2024-12-07 01:01:45 to 2024-12-07 03:01:45 ---
Memory before window: 1464.7 MB
  Found 14799 trips in window
  Processing 13389 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1464.9 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1464.9 MB
  Initial memory: 1464.9 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1465.5 MB
  ✅ Generated 3750 feature rows
Memory after window: 1465.5 MB

--- Window 343/640: 2024-12-07 03:01:45 to 2024-12-07 05:01:45 ---
Memory before window: 1465.5 MB
  Found 13393 trips in window
  Processing 11790 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1465.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1465.7 MB
  Initial memory: 1465.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1465.7 MB
  ✅ Generated 3750 feature rows
Memory after window: 1465.7 MB

--- Window 344/640: 2024-12-07 05:01:45 to 2024-12-07 07:01:45 ---
Memory before window: 1465.7 MB
  Found 21117 trips in window
  Processing 17416 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1465.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1465.7 MB
  Initial memory: 1465.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1466.6 MB
  ✅ Generated 3750 feature rows
Memory after window: 1466.6 MB

--- Window 345/640: 2024-12-07 07:01:45 to 2024-12-07 09:01:45 ---
Memory before window: 1466.6 MB
  Found 29721 trips in window
  Processing 22590 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1467.0 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1467.0 MB
  Initial memory: 1467.0 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1467.5 MB
  ✅ Generated 3750 feature rows
Memory after window: 1467.5 MB

--- Window 346/640: 2024-12-07 09:01:45 to 2024-12-07 11:01:45 ---
Memory before window: 1467.5 MB
  Found 36999 trips in window
  Processing 28488 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1467.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1467.7 MB
  Initial memory: 1467.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1469.9 MB
  ✅ Generated 3750 feature rows
Memory after window: 1469.9 MB

--- Window 347/640: 2024-12-07 11:01:45 to 2024-12-07 13:01:45 ---
Memory before window: 1469.9 MB
  Found 39060 trips in window
  Processing 30330 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1470.3 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1470.5 MB
  Initial memory: 1470.5 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1470.5 MB
  ✅ Generated 3750 feature rows
Memory after window: 1470.5 MB

--- Window 348/640: 2024-12-07 13:01:45 to 2024-12-07 15:01:45 ---
Memory before window: 1470.5 MB
  Found 41832 trips in window
  Processing 34047 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1470.8 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1470.8 MB
  Initial memory: 1470.8 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1471.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 1471.0 MB

--- Window 349/640: 2024-12-07 15:01:45 to 2024-12-07 17:01:45 ---
Memory before window: 1471.0 MB
  Found 44515 trips in window
  Processing 35997 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1471.3 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1471.3 MB
  Initial memory: 1471.3 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1471.5 MB
  ✅ Generated 3750 feature rows
Memory after window: 1471.5 MB

--- Window 350/640: 2024-12-07 17:01:45 to 2024-12-07 19:01:45 ---
Memory before window: 1471.5 MB
  Found 45022 trips in window
  Processing 35751 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1471.9 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1471.9 MB
  Initial memory: 1471.9 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1473.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 1473.0 MB

--- Window 351/640: 2024-12-07 19:01:45 to 2024-12-07 21:01:45 ---
Memory before window: 1473.0 MB
  Found 38769 trips in window
  Processing 31534 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1473.3 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1473.3 MB
  Initial memory: 1473.3 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1477.5 MB
  ✅ Generated 3750 feature rows
Memory after window: 1477.5 MB

--- Window 352/640: 2024-12-07 21:01:45 to 2024-12-07 23:01:45 ---
Memory before window: 1477.5 MB
  Found 31055 trips in window
  Processing 26025 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1477.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1477.7 MB
  Initial memory: 1477.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1478.3 MB
  ✅ Generated 3750 feature rows
Memory after window: 1478.3 MB

--- Window 353/640: 2024-12-07 23:01:45 to 2024-12-08 01:01:45 ---
Memory before window: 1478.3 MB
  Found 22886 trips in window
  Processing 19454 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1478.6 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1478.6 MB
  Initial memory: 1478.6 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1478.6 MB
  ✅ Generated 3750 feature rows
Memory after window: 1478.6 MB

--- Window 354/640: 2024-12-08 01:01:45 to 2024-12-08 03:01:45 ---
Memory before window: 1478.6 MB
  Found 15172 trips in window
  Processing 13472 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1478.8 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1478.8 MB
  Initial memory: 1478.8 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1478.8 MB
  ✅ Generated 3750 feature rows
Memory after window: 1478.8 MB

--- Window 355/640: 2024-12-08 03:01:45 to 2024-12-08 05:01:45 ---
Memory before window: 1478.8 MB
  Found 14780 trips in window
  Processing 12701 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1479.0 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1479.1 MB
  Initial memory: 1479.1 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1481.3 MB
  ✅ Generated 3750 feature rows
Memory after window: 1481.3 MB

--- Window 356/640: 2024-12-08 05:01:45 to 2024-12-08 07:01:45 ---
Memory before window: 1481.3 MB
  Found 20653 trips in window
  Processing 16403 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1481.4 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1481.4 MB
  Initial memory: 1481.4 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1481.9 MB
  ✅ Generated 3750 feature rows
Memory after window: 1481.9 MB

--- Window 357/640: 2024-12-08 07:01:45 to 2024-12-08 09:01:45 ---
Memory before window: 1481.9 MB
  Found 29890 trips in window
  Processing 22502 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1482.2 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1482.2 MB
  Initial memory: 1482.2 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1483.7 MB
  ✅ Generated 3750 feature rows
Memory after window: 1483.7 MB

--- Window 358/640: 2024-12-08 09:01:45 to 2024-12-08 11:01:45 ---
Memory before window: 1483.7 MB
  Found 35562 trips in window
  Processing 26840 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1484.0 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1484.0 MB
  Initial memory: 1484.0 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1484.4 MB
  ✅ Generated 3750 feature rows
Memory after window: 1484.4 MB

--- Window 359/640: 2024-12-08 11:01:45 to 2024-12-08 13:01:45 ---
Memory before window: 1484.4 MB
  Found 39099 trips in window
  Processing 30937 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1484.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1484.7 MB
  Initial memory: 1484.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1485.2 MB
  ✅ Generated 3750 feature rows
Memory after window: 1485.2 MB

--- Window 360/640: 2024-12-08 13:01:45 to 2024-12-08 15:01:45 ---
Memory before window: 1485.2 MB
  Found 40344 trips in window
  Processing 32469 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1485.6 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1485.6 MB
  Initial memory: 1485.6 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1486.2 MB
  ✅ Generated 3750 feature rows
Memory after window: 1486.2 MB

--- Window 361/640: 2024-12-08 15:01:45 to 2024-12-08 17:01:45 ---
Memory before window: 1486.2 MB
  Found 41770 trips in window
  Processing 33412 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1486.5 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1486.5 MB
  Initial memory: 1486.5 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1487.2 MB
  ✅ Generated 3750 feature rows
Memory after window: 1487.2 MB

--- Window 362/640: 2024-12-08 17:01:45 to 2024-12-08 19:01:45 ---
Memory before window: 1487.2 MB
  Found 41155 trips in window
  Processing 32096 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1487.4 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1487.7 MB
  Initial memory: 1487.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1489.4 MB
  ✅ Generated 3750 feature rows
Memory after window: 1489.4 MB

--- Window 363/640: 2024-12-08 19:01:45 to 2024-12-08 21:01:45 ---
Memory before window: 1489.4 MB
  Found 34683 trips in window
  Processing 28106 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1489.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1489.7 MB
  Initial memory: 1489.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1492.9 MB
  ✅ Generated 3750 feature rows
Memory after window: 1492.9 MB

--- Window 364/640: 2024-12-08 21:01:45 to 2024-12-08 23:01:45 ---
Memory before window: 1492.9 MB
  Found 26423 trips in window
  Processing 21979 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1493.0 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1493.1 MB
  Initial memory: 1493.1 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1493.1 MB
  ✅ Generated 3750 feature rows
Memory after window: 1493.1 MB

--- Window 365/640: 2024-12-08 23:01:45 to 2024-12-09 01:01:45 ---
Memory before window: 1493.1 MB
  Found 17379 trips in window
  Processing 15035 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1493.3 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1493.3 MB
  Initial memory: 1493.3 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1457.5 MB
  ✅ Generated 3750 feature rows
Memory after window: 1457.5 MB

--- Window 366/640: 2024-12-09 01:01:45 to 2024-12-09 03:01:45 ---
Memory before window: 1457.5 MB
  Found 12893 trips in window
  Processing 11516 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1449.2 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1442.1 MB
  Initial memory: 1442.1 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1429.2 MB
  ✅ Generated 3750 feature rows
Memory after window: 1429.2 MB

--- Window 367/640: 2024-12-09 03:01:45 to 2024-12-09 05:01:45 ---
Memory before window: 1429.2 MB
  Found 13295 trips in window
  Processing 11521 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1429.4 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1429.4 MB
  Initial memory: 1429.4 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1430.4 MB
  ✅ Generated 3750 feature rows
Memory after window: 1430.4 MB

--- Window 368/640: 2024-12-09 05:01:45 to 2024-12-09 07:01:45 ---
Memory before window: 1430.4 MB
  Found 24743 trips in window
  Processing 19488 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1430.5 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1430.5 MB
  Initial memory: 1430.5 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1431.1 MB
  ✅ Generated 3750 feature rows
Memory after window: 1431.1 MB

--- Window 369/640: 2024-12-09 07:01:45 to 2024-12-09 09:01:45 ---
Memory before window: 1431.1 MB
  Found 34010 trips in window
  Processing 25410 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1431.3 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1431.3 MB
  Initial memory: 1431.3 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1433.2 MB
  ✅ Generated 3750 feature rows
Memory after window: 1433.2 MB

--- Window 370/640: 2024-12-09 09:01:45 to 2024-12-09 11:01:45 ---
Memory before window: 1433.2 MB
  Found 37909 trips in window
  Processing 29375 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1433.5 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1433.5 MB
  Initial memory: 1433.5 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1437.1 MB
  ✅ Generated 3750 feature rows
Memory after window: 1437.1 MB

--- Window 371/640: 2024-12-09 11:01:45 to 2024-12-09 13:01:45 ---
Memory before window: 1437.1 MB
  Found 38147 trips in window
  Processing 30771 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1437.4 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1437.4 MB
  Initial memory: 1437.4 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1440.4 MB
  ✅ Generated 3750 feature rows
Memory after window: 1440.4 MB

--- Window 372/640: 2024-12-09 13:01:45 to 2024-12-09 15:01:45 ---
Memory before window: 1440.4 MB
  Found 41593 trips in window
  Processing 33739 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1440.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1440.7 MB
  Initial memory: 1440.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1442.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 1442.0 MB

--- Window 373/640: 2024-12-09 15:01:45 to 2024-12-09 17:01:45 ---
Memory before window: 1442.0 MB
  Found 42965 trips in window
  Processing 34483 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1442.3 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1442.4 MB
  Initial memory: 1442.4 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1442.6 MB
  ✅ Generated 3750 feature rows
Memory after window: 1442.6 MB

--- Window 374/640: 2024-12-09 17:01:45 to 2024-12-09 19:01:45 ---
Memory before window: 1442.6 MB
  Found 43082 trips in window
  Processing 34544 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1442.9 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1442.9 MB
  Initial memory: 1442.9 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1444.3 MB
  ✅ Generated 3750 feature rows
Memory after window: 1444.3 MB

--- Window 375/640: 2024-12-09 19:01:45 to 2024-12-09 21:01:45 ---
Memory before window: 1444.3 MB
  Found 36980 trips in window
  Processing 29823 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1444.6 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1444.6 MB
  Initial memory: 1444.6 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1444.7 MB
  ✅ Generated 3750 feature rows
Memory after window: 1444.7 MB

--- Window 376/640: 2024-12-09 21:01:45 to 2024-12-09 23:01:45 ---
Memory before window: 1444.7 MB
  Found 28041 trips in window
  Processing 23398 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1444.9 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1444.9 MB
  Initial memory: 1444.9 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1444.9 MB
  ✅ Generated 3750 feature rows
Memory after window: 1444.9 MB

--- Window 377/640: 2024-12-09 23:01:45 to 2024-12-10 01:01:45 ---
Memory before window: 1444.9 MB
  Found 17850 trips in window
  Processing 15405 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1445.1 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1445.2 MB
  Initial memory: 1445.2 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1445.2 MB
  ✅ Generated 3750 feature rows
Memory after window: 1445.2 MB

--- Window 378/640: 2024-12-10 01:01:45 to 2024-12-10 03:01:45 ---
Memory before window: 1445.2 MB
  Found 12329 trips in window
  Processing 10984 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1445.3 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1445.3 MB
  Initial memory: 1445.3 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1445.3 MB
  ✅ Generated 3750 feature rows
Memory after window: 1445.3 MB

--- Window 379/640: 2024-12-10 03:01:45 to 2024-12-10 05:01:45 ---
Memory before window: 1445.3 MB
  Found 12539 trips in window
  Processing 10889 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1445.3 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1445.6 MB
  Initial memory: 1445.6 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1446.6 MB
  ✅ Generated 3750 feature rows
Memory after window: 1446.6 MB

--- Window 380/640: 2024-12-10 05:01:45 to 2024-12-10 07:01:45 ---
Memory before window: 1446.6 MB
  Found 20324 trips in window
  Processing 16275 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1446.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1446.7 MB
  Initial memory: 1446.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1448.8 MB
  ✅ Generated 3750 feature rows
Memory after window: 1448.8 MB

--- Window 381/640: 2024-12-10 07:01:45 to 2024-12-10 09:01:45 ---
Memory before window: 1448.8 MB
  Found 28751 trips in window
  Processing 21927 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1449.0 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1449.6 MB
  Initial memory: 1449.6 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1449.6 MB
  ✅ Generated 3750 feature rows
Memory after window: 1449.6 MB

--- Window 382/640: 2024-12-10 09:01:45 to 2024-12-10 11:01:45 ---
Memory before window: 1449.6 MB
  Found 35409 trips in window
  Processing 27757 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1449.8 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1449.8 MB
  Initial memory: 1449.8 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1451.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 1451.0 MB

--- Window 383/640: 2024-12-10 11:01:45 to 2024-12-10 13:01:45 ---
Memory before window: 1451.0 MB
  Found 38975 trips in window
  Processing 30977 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1451.3 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1451.3 MB
  Initial memory: 1451.3 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1452.6 MB
  ✅ Generated 3750 feature rows
Memory after window: 1452.6 MB

--- Window 384/640: 2024-12-10 13:01:45 to 2024-12-10 15:01:45 ---
Memory before window: 1452.6 MB
  Found 40542 trips in window
  Processing 33050 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1453.0 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1453.0 MB
  Initial memory: 1453.0 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1454.9 MB
  ✅ Generated 3750 feature rows
Memory after window: 1454.9 MB

--- Window 385/640: 2024-12-10 15:01:45 to 2024-12-10 17:01:45 ---
Memory before window: 1454.9 MB
  Found 42507 trips in window
  Processing 34622 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1455.3 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1455.3 MB
  Initial memory: 1455.3 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1455.9 MB
  ✅ Generated 3750 feature rows
Memory after window: 1455.9 MB

--- Window 386/640: 2024-12-10 17:01:45 to 2024-12-10 19:01:45 ---
Memory before window: 1455.9 MB
  Found 41778 trips in window
  Processing 33501 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1456.2 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1456.2 MB
  Initial memory: 1456.2 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1456.2 MB
  ✅ Generated 3750 feature rows
Memory after window: 1456.2 MB

--- Window 387/640: 2024-12-10 19:01:45 to 2024-12-10 21:01:45 ---
Memory before window: 1456.2 MB
  Found 35543 trips in window
  Processing 29329 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1456.5 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1456.5 MB
  Initial memory: 1456.5 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1458.4 MB
  ✅ Generated 3750 feature rows
Memory after window: 1458.4 MB

--- Window 388/640: 2024-12-10 21:01:45 to 2024-12-10 23:01:45 ---
Memory before window: 1458.4 MB
  Found 26376 trips in window
  Processing 22555 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1458.5 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1458.5 MB
  Initial memory: 1458.5 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1458.5 MB
  ✅ Generated 3750 feature rows
Memory after window: 1458.5 MB

--- Window 389/640: 2024-12-10 23:01:45 to 2024-12-11 01:01:45 ---
Memory before window: 1458.5 MB
  Found 17181 trips in window
  Processing 15217 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1458.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1458.7 MB
  Initial memory: 1458.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1458.7 MB
  ✅ Generated 3750 feature rows
Memory after window: 1458.7 MB

--- Window 390/640: 2024-12-11 01:01:45 to 2024-12-11 03:01:45 ---
Memory before window: 1458.7 MB
  Found 12276 trips in window
  Processing 11295 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1458.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1458.7 MB
  Initial memory: 1458.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1458.7 MB
  ✅ Generated 3750 feature rows
Memory after window: 1458.7 MB

--- Window 391/640: 2024-12-11 03:01:45 to 2024-12-11 05:01:45 ---
Memory before window: 1458.7 MB
  Found 12937 trips in window
  Processing 10977 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1458.9 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1458.9 MB
  Initial memory: 1458.9 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1459.4 MB
  ✅ Generated 3750 feature rows
Memory after window: 1459.4 MB

--- Window 392/640: 2024-12-11 05:01:45 to 2024-12-11 07:01:45 ---
Memory before window: 1459.4 MB
  Found 24923 trips in window
  Processing 20258 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1459.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1459.7 MB
  Initial memory: 1459.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1460.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 1460.0 MB

--- Window 393/640: 2024-12-11 07:01:45 to 2024-12-11 09:01:45 ---
Memory before window: 1460.0 MB
  Found 35563 trips in window
  Processing 27112 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1460.2 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1460.2 MB
  Initial memory: 1460.2 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1461.8 MB
  ✅ Generated 3750 feature rows
Memory after window: 1461.8 MB

--- Window 394/640: 2024-12-11 09:01:45 to 2024-12-11 11:01:45 ---
Memory before window: 1461.8 MB
  Found 36177 trips in window
  Processing 28313 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1462.0 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1462.0 MB
  Initial memory: 1462.0 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1463.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 1463.0 MB

--- Window 395/640: 2024-12-11 11:01:45 to 2024-12-11 13:01:45 ---
Memory before window: 1463.0 MB
  Found 35167 trips in window
  Processing 28915 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1463.3 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1463.3 MB
  Initial memory: 1463.3 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1465.6 MB
  ✅ Generated 3750 feature rows
Memory after window: 1465.6 MB

--- Window 396/640: 2024-12-11 13:01:45 to 2024-12-11 15:01:45 ---
Memory before window: 1465.6 MB
  Found 40887 trips in window
  Processing 33895 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1465.9 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1465.9 MB
  Initial memory: 1465.9 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1467.2 MB
  ✅ Generated 3750 feature rows
Memory after window: 1467.2 MB

--- Window 397/640: 2024-12-11 15:01:45 to 2024-12-11 17:01:45 ---
Memory before window: 1467.2 MB
  Found 45590 trips in window
  Processing 36711 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1467.6 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1467.6 MB
  Initial memory: 1467.6 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1468.9 MB
  ✅ Generated 3750 feature rows
Memory after window: 1468.9 MB

--- Window 398/640: 2024-12-11 17:01:45 to 2024-12-11 19:01:45 ---
Memory before window: 1468.9 MB
  Found 45041 trips in window
  Processing 36632 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1469.1 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1469.1 MB
  Initial memory: 1469.1 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1469.5 MB
  ✅ Generated 3750 feature rows
Memory after window: 1469.5 MB

--- Window 399/640: 2024-12-11 19:01:45 to 2024-12-11 21:01:45 ---
Memory before window: 1469.5 MB
  Found 38478 trips in window
  Processing 32143 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1469.8 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1469.8 MB
  Initial memory: 1469.8 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1470.5 MB
  ✅ Generated 3750 feature rows
Memory after window: 1470.5 MB

--- Window 400/640: 2024-12-11 21:01:45 to 2024-12-11 23:01:45 ---
Memory before window: 1470.5 MB
  Found 28566 trips in window
  Processing 24309 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1470.8 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1470.8 MB
  Initial memory: 1470.8 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1470.8 MB
  ✅ Generated 3750 feature rows
Memory after window: 1470.8 MB

--- Window 401/640: 2024-12-11 23:01:45 to 2024-12-12 01:01:45 ---
Memory before window: 1470.8 MB
  Found 18149 trips in window
  Processing 16064 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1470.9 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1470.9 MB
  Initial memory: 1470.9 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1470.9 MB
  ✅ Generated 3750 feature rows
Memory after window: 1470.9 MB

--- Window 402/640: 2024-12-12 01:01:45 to 2024-12-12 03:01:45 ---
Memory before window: 1470.9 MB
  Found 12794 trips in window
  Processing 11687 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1471.0 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1471.0 MB
  Initial memory: 1471.0 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1471.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 1471.0 MB

--- Window 403/640: 2024-12-12 03:01:45 to 2024-12-12 05:01:45 ---
Memory before window: 1471.0 MB
  Found 13164 trips in window
  Processing 11481 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1471.1 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1471.1 MB
  Initial memory: 1471.1 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1471.2 MB
  ✅ Generated 3750 feature rows
Memory after window: 1471.2 MB

--- Window 404/640: 2024-12-12 05:01:45 to 2024-12-12 07:01:45 ---
Memory before window: 1471.2 MB
  Found 24312 trips in window
  Processing 19440 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1471.5 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1471.5 MB
  Initial memory: 1471.5 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1471.6 MB
  ✅ Generated 3750 feature rows
Memory after window: 1471.6 MB

--- Window 405/640: 2024-12-12 07:01:45 to 2024-12-12 09:01:45 ---
Memory before window: 1471.6 MB
  Found 35841 trips in window
  Processing 26914 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1471.8 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1471.8 MB
  Initial memory: 1471.8 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1474.2 MB
  ✅ Generated 3750 feature rows
Memory after window: 1474.2 MB

--- Window 406/640: 2024-12-12 09:01:45 to 2024-12-12 11:01:45 ---
Memory before window: 1474.2 MB
  Found 39030 trips in window
  Processing 30282 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1474.4 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1474.4 MB
  Initial memory: 1474.4 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1474.7 MB
  ✅ Generated 3750 feature rows
Memory after window: 1474.7 MB

--- Window 407/640: 2024-12-12 11:01:45 to 2024-12-12 13:01:45 ---
Memory before window: 1474.7 MB
  Found 38797 trips in window
  Processing 31277 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1475.0 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1475.0 MB
  Initial memory: 1475.0 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1477.3 MB
  ✅ Generated 3750 feature rows
Memory after window: 1477.3 MB

--- Window 408/640: 2024-12-12 13:01:45 to 2024-12-12 15:01:45 ---
Memory before window: 1477.3 MB
  Found 40753 trips in window
  Processing 33642 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1477.6 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1477.6 MB
  Initial memory: 1477.6 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1480.4 MB
  ✅ Generated 3750 feature rows
Memory after window: 1480.4 MB

--- Window 409/640: 2024-12-12 15:01:45 to 2024-12-12 17:01:45 ---
Memory before window: 1480.4 MB
  Found 44673 trips in window
  Processing 35872 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1480.9 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1480.9 MB
  Initial memory: 1480.9 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1484.5 MB
  ✅ Generated 3750 feature rows
Memory after window: 1484.5 MB

--- Window 410/640: 2024-12-12 17:01:45 to 2024-12-12 19:01:45 ---
Memory before window: 1484.5 MB
  Found 43797 trips in window
  Processing 34451 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1484.6 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1484.7 MB
  Initial memory: 1484.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1486.3 MB
  ✅ Generated 3750 feature rows
Memory after window: 1486.3 MB

--- Window 411/640: 2024-12-12 19:01:45 to 2024-12-12 21:01:45 ---
Memory before window: 1486.3 MB
  Found 38745 trips in window
  Processing 31778 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1486.6 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1486.7 MB
  Initial memory: 1486.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1487.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 1487.0 MB

--- Window 412/640: 2024-12-12 21:01:45 to 2024-12-12 23:01:45 ---
Memory before window: 1487.0 MB
  Found 29095 trips in window
  Processing 24675 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1487.2 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1487.3 MB
  Initial memory: 1487.3 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1487.3 MB
  ✅ Generated 3750 feature rows
Memory after window: 1487.3 MB

--- Window 413/640: 2024-12-12 23:01:45 to 2024-12-13 01:01:45 ---
Memory before window: 1487.3 MB
  Found 19234 trips in window
  Processing 16992 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1487.4 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1487.4 MB
  Initial memory: 1487.4 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1489.1 MB
  ✅ Generated 3750 feature rows
Memory after window: 1489.1 MB

--- Window 414/640: 2024-12-13 01:01:45 to 2024-12-13 03:01:45 ---
Memory before window: 1489.1 MB
  Found 13927 trips in window
  Processing 12590 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1489.3 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1489.3 MB
  Initial memory: 1489.3 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1489.9 MB
  ✅ Generated 3750 feature rows
Memory after window: 1489.9 MB

--- Window 415/640: 2024-12-13 03:01:45 to 2024-12-13 05:01:45 ---
Memory before window: 1489.9 MB
  Found 13844 trips in window
  Processing 11847 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1490.0 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1490.0 MB
  Initial memory: 1490.0 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1490.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 1490.0 MB

--- Window 416/640: 2024-12-13 05:01:45 to 2024-12-13 07:01:45 ---
Memory before window: 1490.0 MB
  Found 23734 trips in window
  Processing 19316 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1490.1 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1490.1 MB
  Initial memory: 1490.1 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1490.1 MB
  ✅ Generated 3750 feature rows
Memory after window: 1490.1 MB

--- Window 417/640: 2024-12-13 07:01:45 to 2024-12-13 09:01:45 ---
Memory before window: 1490.1 MB
  Found 36368 trips in window
  Processing 27792 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1490.4 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1490.4 MB
  Initial memory: 1490.4 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1490.4 MB
  ✅ Generated 3750 feature rows
Memory after window: 1490.4 MB

--- Window 418/640: 2024-12-13 09:01:45 to 2024-12-13 11:01:45 ---
Memory before window: 1490.4 MB
  Found 38429 trips in window
  Processing 29315 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1490.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1490.7 MB
  Initial memory: 1490.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1494.3 MB
  ✅ Generated 3750 feature rows
Memory after window: 1494.3 MB

--- Window 419/640: 2024-12-13 11:01:45 to 2024-12-13 13:01:45 ---
Memory before window: 1494.3 MB
  Found 39691 trips in window
  Processing 31506 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1494.6 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1494.6 MB
  Initial memory: 1494.6 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1495.1 MB
  ✅ Generated 3750 feature rows
Memory after window: 1495.1 MB

--- Window 420/640: 2024-12-13 13:01:45 to 2024-12-13 15:01:45 ---
Memory before window: 1495.1 MB
  Found 42933 trips in window
  Processing 34332 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1495.4 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1495.4 MB
  Initial memory: 1495.4 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1495.5 MB
  ✅ Generated 3750 feature rows
Memory after window: 1495.5 MB

--- Window 421/640: 2024-12-13 15:01:45 to 2024-12-13 17:01:45 ---
Memory before window: 1495.5 MB
  Found 44221 trips in window
  Processing 34786 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1495.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1495.7 MB
  Initial memory: 1495.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1499.2 MB
  ✅ Generated 3750 feature rows
Memory after window: 1499.2 MB

--- Window 422/640: 2024-12-13 17:01:45 to 2024-12-13 19:01:45 ---
Memory before window: 1499.2 MB
  Found 45757 trips in window
  Processing 36651 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1499.6 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1499.6 MB
  Initial memory: 1499.6 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1502.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 1502.0 MB

--- Window 423/640: 2024-12-13 19:01:45 to 2024-12-13 21:01:45 ---
Memory before window: 1502.0 MB
  Found 41411 trips in window
  Processing 34149 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1502.2 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1502.2 MB
  Initial memory: 1502.2 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1502.2 MB
  ✅ Generated 3750 feature rows
Memory after window: 1502.2 MB

--- Window 424/640: 2024-12-13 21:01:45 to 2024-12-13 23:01:45 ---
Memory before window: 1502.2 MB
  Found 32759 trips in window
  Processing 27754 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1502.5 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1502.5 MB
  Initial memory: 1502.5 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1502.5 MB
  ✅ Generated 3750 feature rows
Memory after window: 1502.5 MB

--- Window 425/640: 2024-12-13 23:01:45 to 2024-12-14 01:01:45 ---
Memory before window: 1502.5 MB
  Found 23704 trips in window
  Processing 20567 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1502.8 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1502.8 MB
  Initial memory: 1502.8 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1503.1 MB
  ✅ Generated 3750 feature rows
Memory after window: 1503.1 MB

--- Window 426/640: 2024-12-14 01:01:45 to 2024-12-14 03:01:45 ---
Memory before window: 1503.1 MB
  Found 16636 trips in window
  Processing 14678 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1503.2 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1503.2 MB
  Initial memory: 1503.2 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1503.4 MB
  ✅ Generated 3750 feature rows
Memory after window: 1503.4 MB

--- Window 427/640: 2024-12-14 03:01:45 to 2024-12-14 05:01:45 ---
Memory before window: 1503.4 MB
  Found 15217 trips in window
  Processing 13150 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1503.5 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1503.5 MB
  Initial memory: 1503.5 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1504.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 1504.0 MB

--- Window 428/640: 2024-12-14 05:01:45 to 2024-12-14 07:01:45 ---
Memory before window: 1504.0 MB
  Found 21802 trips in window
  Processing 17806 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1504.2 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1504.2 MB
  Initial memory: 1504.2 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1504.3 MB
  ✅ Generated 3750 feature rows
Memory after window: 1504.3 MB

--- Window 429/640: 2024-12-14 07:01:45 to 2024-12-14 09:01:45 ---
Memory before window: 1504.3 MB
  Found 29312 trips in window
  Processing 21905 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1504.4 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1504.4 MB
  Initial memory: 1504.4 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1504.4 MB
  ✅ Generated 3750 feature rows
Memory after window: 1504.4 MB

--- Window 430/640: 2024-12-14 09:01:45 to 2024-12-14 11:01:45 ---
Memory before window: 1504.4 MB
  Found 36141 trips in window
  Processing 28138 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1504.6 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1504.6 MB
  Initial memory: 1504.6 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1475.3 MB
  ✅ Generated 3750 feature rows
Memory after window: 1475.3 MB

--- Window 431/640: 2024-12-14 11:01:45 to 2024-12-14 13:01:45 ---
Memory before window: 1475.3 MB
  Found 40115 trips in window
  Processing 32515 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1468.2 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1468.4 MB
  Initial memory: 1468.4 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1468.4 MB
  ✅ Generated 3750 feature rows
Memory after window: 1468.4 MB

--- Window 432/640: 2024-12-14 13:01:45 to 2024-12-14 15:01:45 ---
Memory before window: 1468.4 MB
  Found 41561 trips in window
  Processing 33917 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1468.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1468.7 MB
  Initial memory: 1468.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1466.5 MB
  ✅ Generated 3750 feature rows
Memory after window: 1466.5 MB

--- Window 433/640: 2024-12-14 15:01:45 to 2024-12-14 17:01:45 ---
Memory before window: 1466.5 MB
  Found 43501 trips in window
  Processing 35717 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1466.8 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1466.8 MB
  Initial memory: 1466.8 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1471.2 MB
  ✅ Generated 3750 feature rows
Memory after window: 1471.2 MB

--- Window 434/640: 2024-12-14 17:01:45 to 2024-12-14 19:01:45 ---
Memory before window: 1471.2 MB
  Found 45069 trips in window
  Processing 36424 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1471.6 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1471.6 MB
  Initial memory: 1471.6 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1472.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 1472.0 MB

--- Window 435/640: 2024-12-14 19:01:45 to 2024-12-14 21:01:45 ---
Memory before window: 1472.0 MB
  Found 39631 trips in window
  Processing 32462 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1472.2 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1472.2 MB
  Initial memory: 1472.2 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1472.2 MB
  ✅ Generated 3750 feature rows
Memory after window: 1472.2 MB

--- Window 436/640: 2024-12-14 21:01:45 to 2024-12-14 23:01:45 ---
Memory before window: 1472.2 MB
  Found 32211 trips in window
  Processing 26832 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1472.4 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1472.4 MB
  Initial memory: 1472.4 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1469.7 MB
  ✅ Generated 3750 feature rows
Memory after window: 1469.7 MB

--- Window 437/640: 2024-12-14 23:01:45 to 2024-12-15 01:01:45 ---
Memory before window: 1469.7 MB
  Found 23481 trips in window
  Processing 19891 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1469.9 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1469.9 MB
  Initial memory: 1469.9 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1469.9 MB
  ✅ Generated 3750 feature rows
Memory after window: 1469.9 MB

--- Window 438/640: 2024-12-15 01:01:45 to 2024-12-15 03:01:45 ---
Memory before window: 1469.9 MB
  Found 16510 trips in window
  Processing 14327 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1470.0 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1470.0 MB
  Initial memory: 1470.0 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1470.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 1470.0 MB

--- Window 439/640: 2024-12-15 03:01:45 to 2024-12-15 05:01:45 ---
Memory before window: 1470.0 MB
  Found 14677 trips in window
  Processing 12924 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1470.1 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1470.1 MB
  Initial memory: 1470.1 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1467.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 1467.0 MB

--- Window 440/640: 2024-12-15 05:01:45 to 2024-12-15 07:01:45 ---
Memory before window: 1467.0 MB
  Found 19270 trips in window
  Processing 15732 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1467.1 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1467.1 MB
  Initial memory: 1467.1 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1468.6 MB
  ✅ Generated 3750 feature rows
Memory after window: 1468.6 MB

--- Window 441/640: 2024-12-15 07:01:45 to 2024-12-15 09:01:45 ---
Memory before window: 1468.6 MB
  Found 28088 trips in window
  Processing 21435 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1468.8 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1468.8 MB
  Initial memory: 1468.8 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1466.5 MB
  ✅ Generated 3750 feature rows
Memory after window: 1466.5 MB

--- Window 442/640: 2024-12-15 09:01:45 to 2024-12-15 11:01:45 ---
Memory before window: 1466.5 MB
  Found 34602 trips in window
  Processing 26881 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1466.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1466.7 MB
  Initial memory: 1466.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1466.9 MB
  ✅ Generated 3750 feature rows
Memory after window: 1466.9 MB

--- Window 443/640: 2024-12-15 11:01:45 to 2024-12-15 13:01:45 ---
Memory before window: 1466.9 MB
  Found 38350 trips in window
  Processing 30673 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1467.2 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1467.2 MB
  Initial memory: 1467.2 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1467.4 MB
  ✅ Generated 3750 feature rows
Memory after window: 1467.4 MB

--- Window 444/640: 2024-12-15 13:01:45 to 2024-12-15 15:01:45 ---
Memory before window: 1467.4 MB
  Found 39688 trips in window
  Processing 31620 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1467.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1467.7 MB
  Initial memory: 1467.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1467.9 MB
  ✅ Generated 3750 feature rows
Memory after window: 1467.9 MB

--- Window 445/640: 2024-12-15 15:01:45 to 2024-12-15 17:01:45 ---
Memory before window: 1467.9 MB
  Found 42381 trips in window
  Processing 33686 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1468.2 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1468.3 MB
  Initial memory: 1468.3 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1470.1 MB
  ✅ Generated 3750 feature rows
Memory after window: 1470.1 MB

--- Window 446/640: 2024-12-15 17:01:45 to 2024-12-15 19:01:45 ---
Memory before window: 1470.1 MB
  Found 42742 trips in window
  Processing 33428 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1470.4 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1470.4 MB
  Initial memory: 1470.4 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1468.3 MB
  ✅ Generated 3750 feature rows
Memory after window: 1468.3 MB

--- Window 447/640: 2024-12-15 19:01:45 to 2024-12-15 21:01:45 ---
Memory before window: 1468.3 MB
  Found 36865 trips in window
  Processing 29865 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1468.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1468.7 MB
  Initial memory: 1468.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1469.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 1469.0 MB

--- Window 448/640: 2024-12-15 21:01:45 to 2024-12-15 23:01:45 ---
Memory before window: 1469.0 MB
  Found 27220 trips in window
  Processing 22650 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1469.2 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1469.2 MB
  Initial memory: 1469.2 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1471.6 MB
  ✅ Generated 3750 feature rows
Memory after window: 1471.6 MB

--- Window 449/640: 2024-12-15 23:01:45 to 2024-12-16 01:01:45 ---
Memory before window: 1471.6 MB
  Found 18190 trips in window
  Processing 15738 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1471.8 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1471.8 MB
  Initial memory: 1471.8 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1471.8 MB
  ✅ Generated 3750 feature rows
Memory after window: 1471.8 MB

--- Window 450/640: 2024-12-16 01:01:45 to 2024-12-16 03:01:45 ---
Memory before window: 1471.8 MB
  Found 12858 trips in window
  Processing 11432 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1472.0 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1472.0 MB
  Initial memory: 1472.0 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1472.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 1472.0 MB

--- Window 451/640: 2024-12-16 03:01:45 to 2024-12-16 05:01:45 ---
Memory before window: 1472.0 MB
  Found 13157 trips in window
  Processing 11200 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1472.1 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1472.1 MB
  Initial memory: 1472.1 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1472.3 MB
  ✅ Generated 3750 feature rows
Memory after window: 1472.3 MB

--- Window 452/640: 2024-12-16 05:01:45 to 2024-12-16 07:01:45 ---
Memory before window: 1472.3 MB
  Found 23690 trips in window
  Processing 18535 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1472.5 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1472.5 MB
  Initial memory: 1472.5 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1472.7 MB
  ✅ Generated 3750 feature rows
Memory after window: 1472.7 MB

--- Window 453/640: 2024-12-16 07:01:45 to 2024-12-16 09:01:45 ---
Memory before window: 1472.7 MB
  Found 33499 trips in window
  Processing 24757 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1473.0 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1473.0 MB
  Initial memory: 1473.0 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1474.4 MB
  ✅ Generated 3750 feature rows
Memory after window: 1474.4 MB

--- Window 454/640: 2024-12-16 09:01:45 to 2024-12-16 11:01:45 ---
Memory before window: 1474.4 MB
  Found 36342 trips in window
  Processing 27640 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1474.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1474.8 MB
  Initial memory: 1474.8 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1477.8 MB
  ✅ Generated 3750 feature rows
Memory after window: 1477.8 MB

--- Window 455/640: 2024-12-16 11:01:45 to 2024-12-16 13:01:45 ---
Memory before window: 1477.8 MB
  Found 39024 trips in window
  Processing 30806 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1475.1 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1475.2 MB
  Initial memory: 1475.2 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1417.2 MB
  ✅ Generated 3750 feature rows
Memory after window: 1417.2 MB

--- Window 456/640: 2024-12-16 13:01:45 to 2024-12-16 15:01:45 ---
Memory before window: 1417.2 MB
  Found 40485 trips in window
  Processing 32784 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1417.5 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1417.5 MB
  Initial memory: 1417.5 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1417.5 MB
  ✅ Generated 3750 feature rows
Memory after window: 1417.5 MB

--- Window 457/640: 2024-12-16 15:01:45 to 2024-12-16 17:01:45 ---
Memory before window: 1417.5 MB
  Found 42072 trips in window
  Processing 33057 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1417.8 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1417.8 MB
  Initial memory: 1417.8 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1418.2 MB
  ✅ Generated 3750 feature rows
Memory after window: 1418.2 MB

--- Window 458/640: 2024-12-16 17:01:45 to 2024-12-16 19:01:45 ---
Memory before window: 1418.2 MB
  Found 42243 trips in window
  Processing 33496 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1418.4 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1418.4 MB
  Initial memory: 1418.4 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1422.8 MB
  ✅ Generated 3750 feature rows
Memory after window: 1422.8 MB

--- Window 459/640: 2024-12-16 19:01:45 to 2024-12-16 21:01:45 ---
Memory before window: 1422.8 MB
  Found 35732 trips in window
  Processing 28791 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1423.1 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1423.1 MB
  Initial memory: 1423.1 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1423.8 MB
  ✅ Generated 3750 feature rows
Memory after window: 1423.8 MB

--- Window 460/640: 2024-12-16 21:01:45 to 2024-12-16 23:01:45 ---
Memory before window: 1423.8 MB
  Found 25845 trips in window
  Processing 21597 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1424.0 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1424.0 MB
  Initial memory: 1424.0 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1424.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 1424.0 MB

--- Window 461/640: 2024-12-16 23:01:45 to 2024-12-17 01:01:45 ---
Memory before window: 1424.0 MB
  Found 16660 trips in window
  Processing 14779 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1424.3 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1424.3 MB
  Initial memory: 1424.3 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1424.3 MB
  ✅ Generated 3750 feature rows
Memory after window: 1407.9 MB

--- Window 462/640: 2024-12-17 01:01:45 to 2024-12-17 03:01:45 ---
Memory before window: 1407.9 MB
  Found 11569 trips in window
  Processing 10386 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1408.0 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1400.1 MB
  Initial memory: 1400.1 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1245.4 MB
  ✅ Generated 3750 feature rows
Memory after window: 1245.4 MB

--- Window 463/640: 2024-12-17 03:01:45 to 2024-12-17 05:01:45 ---
Memory before window: 1245.4 MB
  Found 11810 trips in window
  Processing 10295 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1245.4 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1245.4 MB
  Initial memory: 1245.4 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1225.6 MB
  ✅ Generated 3750 feature rows
Memory after window: 1225.6 MB

--- Window 464/640: 2024-12-17 05:01:45 to 2024-12-17 07:01:45 ---
Memory before window: 1225.6 MB
  Found 23382 trips in window
  Processing 18708 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1225.8 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1225.8 MB
  Initial memory: 1225.8 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1226.2 MB
  ✅ Generated 3750 feature rows
Memory after window: 1226.2 MB

--- Window 465/640: 2024-12-17 07:01:45 to 2024-12-17 09:01:45 ---
Memory before window: 1226.2 MB
  Found 34651 trips in window
  Processing 26607 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1226.5 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1226.5 MB
  Initial memory: 1226.5 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1228.3 MB
  ✅ Generated 3750 feature rows
Memory after window: 1228.3 MB

--- Window 466/640: 2024-12-17 09:01:45 to 2024-12-17 11:01:45 ---
Memory before window: 1228.3 MB
  Found 38633 trips in window
  Processing 30349 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1228.5 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1228.5 MB
  Initial memory: 1228.5 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1232.4 MB
  ✅ Generated 3750 feature rows
Memory after window: 1232.4 MB

--- Window 467/640: 2024-12-17 11:01:45 to 2024-12-17 13:01:45 ---
Memory before window: 1232.4 MB
  Found 40006 trips in window
  Processing 32063 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1232.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1232.7 MB
  Initial memory: 1232.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1232.7 MB
  ✅ Generated 3750 feature rows
Memory after window: 1232.7 MB

--- Window 468/640: 2024-12-17 13:01:45 to 2024-12-17 15:01:45 ---
Memory before window: 1232.7 MB
  Found 40625 trips in window
  Processing 32949 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1233.0 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1233.0 MB
  Initial memory: 1233.0 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1233.9 MB
  ✅ Generated 3750 feature rows
Memory after window: 1233.9 MB

--- Window 469/640: 2024-12-17 15:01:45 to 2024-12-17 17:01:45 ---
Memory before window: 1233.9 MB
  Found 44400 trips in window
  Processing 35130 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1234.1 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1234.3 MB
  Initial memory: 1234.3 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1236.2 MB
  ✅ Generated 3750 feature rows
Memory after window: 1236.2 MB

--- Window 470/640: 2024-12-17 17:01:45 to 2024-12-17 19:01:45 ---
Memory before window: 1236.2 MB
  Found 44141 trips in window
  Processing 34915 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1236.6 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1236.6 MB
  Initial memory: 1236.6 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1237.1 MB
  ✅ Generated 3750 feature rows
Memory after window: 1237.1 MB

--- Window 471/640: 2024-12-17 19:01:45 to 2024-12-17 21:01:45 ---
Memory before window: 1237.1 MB
  Found 38508 trips in window
  Processing 31575 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1237.5 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1237.5 MB
  Initial memory: 1237.5 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1237.5 MB
  ✅ Generated 3750 feature rows
Memory after window: 1237.5 MB

--- Window 472/640: 2024-12-17 21:01:45 to 2024-12-17 23:01:45 ---
Memory before window: 1237.5 MB
  Found 26809 trips in window
  Processing 22536 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1237.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1237.7 MB
  Initial memory: 1237.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1238.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 1238.0 MB

--- Window 473/640: 2024-12-17 23:01:45 to 2024-12-18 01:01:45 ---
Memory before window: 1238.0 MB
  Found 16146 trips in window
  Processing 14310 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1238.2 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1238.2 MB
  Initial memory: 1238.2 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1239.3 MB
  ✅ Generated 3750 feature rows
Memory after window: 1239.3 MB

--- Window 474/640: 2024-12-18 01:01:45 to 2024-12-18 03:01:45 ---
Memory before window: 1239.3 MB
  Found 10958 trips in window
  Processing 9881 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1239.3 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1239.3 MB
  Initial memory: 1239.3 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1239.4 MB
  ✅ Generated 3750 feature rows
Memory after window: 1239.4 MB

--- Window 475/640: 2024-12-18 03:01:45 to 2024-12-18 05:01:45 ---
Memory before window: 1239.4 MB
  Found 12141 trips in window
  Processing 10435 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1239.5 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1239.5 MB
  Initial memory: 1239.5 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1239.8 MB
  ✅ Generated 3750 feature rows
Memory after window: 1239.8 MB

--- Window 476/640: 2024-12-18 05:01:45 to 2024-12-18 07:01:45 ---
Memory before window: 1239.8 MB
  Found 24216 trips in window
  Processing 19703 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1239.9 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1239.9 MB
  Initial memory: 1239.9 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1240.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 1240.0 MB

--- Window 477/640: 2024-12-18 07:01:45 to 2024-12-18 09:01:45 ---
Memory before window: 1240.0 MB
  Found 35651 trips in window
  Processing 26853 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1240.2 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1240.2 MB
  Initial memory: 1240.2 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1243.2 MB
  ✅ Generated 3750 feature rows
Memory after window: 1243.2 MB

--- Window 478/640: 2024-12-18 09:01:45 to 2024-12-18 11:01:45 ---
Memory before window: 1243.2 MB
  Found 37283 trips in window
  Processing 29490 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1243.5 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1243.5 MB
  Initial memory: 1243.5 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1245.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 1245.0 MB

--- Window 479/640: 2024-12-18 11:01:45 to 2024-12-18 13:01:45 ---
Memory before window: 1245.0 MB
  Found 35175 trips in window
  Processing 28410 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1245.3 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1245.3 MB
  Initial memory: 1245.3 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1246.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 1246.0 MB

--- Window 480/640: 2024-12-18 13:01:45 to 2024-12-18 15:01:45 ---
Memory before window: 1246.0 MB
  Found 41282 trips in window
  Processing 33732 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1246.4 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1246.4 MB
  Initial memory: 1246.4 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1239.5 MB
  ✅ Generated 3750 feature rows
Memory after window: 1239.5 MB

--- Window 481/640: 2024-12-18 15:01:45 to 2024-12-18 17:01:45 ---
Memory before window: 1239.5 MB
  Found 45826 trips in window
  Processing 36900 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1239.8 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1239.8 MB
  Initial memory: 1239.8 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1234.2 MB
  ✅ Generated 3750 feature rows
Memory after window: 1234.2 MB

--- Window 482/640: 2024-12-18 17:01:45 to 2024-12-18 19:01:45 ---
Memory before window: 1234.2 MB
  Found 44491 trips in window
  Processing 35574 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1234.6 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1234.6 MB
  Initial memory: 1234.6 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1235.7 MB
  ✅ Generated 3750 feature rows
Memory after window: 1235.7 MB

--- Window 483/640: 2024-12-18 19:01:45 to 2024-12-18 21:01:45 ---
Memory before window: 1235.7 MB
  Found 38730 trips in window
  Processing 31811 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1236.0 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1236.0 MB
  Initial memory: 1236.0 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1236.1 MB
  ✅ Generated 3750 feature rows
Memory after window: 1236.1 MB

--- Window 484/640: 2024-12-18 21:01:45 to 2024-12-18 23:01:45 ---
Memory before window: 1236.1 MB
  Found 28653 trips in window
  Processing 24440 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1236.3 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1236.3 MB
  Initial memory: 1236.3 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1237.7 MB
  ✅ Generated 3750 feature rows
Memory after window: 1237.7 MB

--- Window 485/640: 2024-12-18 23:01:45 to 2024-12-19 01:01:45 ---
Memory before window: 1237.7 MB
  Found 18322 trips in window
  Processing 16059 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1237.9 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1237.9 MB
  Initial memory: 1237.9 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1238.2 MB
  ✅ Generated 3750 feature rows
Memory after window: 1238.2 MB

--- Window 486/640: 2024-12-19 01:01:45 to 2024-12-19 03:01:45 ---
Memory before window: 1238.2 MB
  Found 12471 trips in window
  Processing 11295 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1238.3 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1238.3 MB
  Initial memory: 1238.3 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1238.6 MB
  ✅ Generated 3750 feature rows
Memory after window: 1238.6 MB

--- Window 487/640: 2024-12-19 03:01:45 to 2024-12-19 05:01:45 ---
Memory before window: 1238.6 MB
  Found 13209 trips in window
  Processing 11392 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1238.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1238.7 MB
  Initial memory: 1238.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1238.7 MB
  ✅ Generated 3750 feature rows
Memory after window: 1238.7 MB

--- Window 488/640: 2024-12-19 05:01:45 to 2024-12-19 07:01:45 ---
Memory before window: 1238.7 MB
  Found 25097 trips in window
  Processing 20120 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1238.8 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1238.8 MB
  Initial memory: 1238.8 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1238.8 MB
  ✅ Generated 3750 feature rows
Memory after window: 1238.8 MB

--- Window 489/640: 2024-12-19 07:01:45 to 2024-12-19 09:01:45 ---
Memory before window: 1238.8 MB
  Found 35287 trips in window
  Processing 27149 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1239.1 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1239.1 MB
  Initial memory: 1239.1 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1240.5 MB
  ✅ Generated 3750 feature rows
Memory after window: 1240.5 MB

--- Window 490/640: 2024-12-19 09:01:45 to 2024-12-19 11:01:45 ---
Memory before window: 1240.5 MB
  Found 37890 trips in window
  Processing 29880 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1240.8 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1240.8 MB
  Initial memory: 1240.8 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1242.7 MB
  ✅ Generated 3750 feature rows
Memory after window: 1242.7 MB

--- Window 491/640: 2024-12-19 11:01:45 to 2024-12-19 13:01:45 ---
Memory before window: 1242.7 MB
  Found 37858 trips in window
  Processing 30949 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1242.9 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1242.9 MB
  Initial memory: 1242.9 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1245.1 MB
  ✅ Generated 3750 feature rows
Memory after window: 1245.1 MB

--- Window 492/640: 2024-12-19 13:01:45 to 2024-12-19 15:01:45 ---
Memory before window: 1245.1 MB
  Found 42148 trips in window
  Processing 34579 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1245.4 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1245.4 MB
  Initial memory: 1245.4 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1245.4 MB
  ✅ Generated 3750 feature rows
Memory after window: 1245.4 MB

--- Window 493/640: 2024-12-19 15:01:45 to 2024-12-19 17:01:45 ---
Memory before window: 1245.4 MB
  Found 45472 trips in window
  Processing 36548 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1245.6 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1245.7 MB
  Initial memory: 1245.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1248.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 1248.0 MB

--- Window 494/640: 2024-12-19 17:01:45 to 2024-12-19 19:01:45 ---
Memory before window: 1248.0 MB
  Found 44802 trips in window
  Processing 35497 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1248.2 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1248.2 MB
  Initial memory: 1248.2 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1249.3 MB
  ✅ Generated 3750 feature rows
Memory after window: 1249.3 MB

--- Window 495/640: 2024-12-19 19:01:45 to 2024-12-19 21:01:45 ---
Memory before window: 1249.3 MB
  Found 38618 trips in window
  Processing 30775 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1249.5 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1249.9 MB
  Initial memory: 1249.9 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1252.3 MB
  ✅ Generated 3750 feature rows
Memory after window: 1252.3 MB

--- Window 496/640: 2024-12-19 21:01:45 to 2024-12-19 23:01:45 ---
Memory before window: 1252.3 MB
  Found 28534 trips in window
  Processing 24496 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1252.5 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1252.5 MB
  Initial memory: 1252.5 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1253.2 MB
  ✅ Generated 3750 feature rows
Memory after window: 1253.2 MB

--- Window 497/640: 2024-12-19 23:01:45 to 2024-12-20 01:01:45 ---
Memory before window: 1253.2 MB
  Found 18816 trips in window
  Processing 16839 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1253.3 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1253.3 MB
  Initial memory: 1253.3 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1253.4 MB
  ✅ Generated 3750 feature rows
Memory after window: 1253.4 MB

--- Window 498/640: 2024-12-20 01:01:45 to 2024-12-20 03:01:45 ---
Memory before window: 1253.4 MB
  Found 12120 trips in window
  Processing 11106 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1253.4 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1253.4 MB
  Initial memory: 1253.4 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1253.6 MB
  ✅ Generated 3750 feature rows
Memory after window: 1253.6 MB

--- Window 499/640: 2024-12-20 03:01:45 to 2024-12-20 05:01:45 ---
Memory before window: 1253.6 MB
  Found 12453 trips in window
  Processing 10928 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1253.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1253.7 MB
  Initial memory: 1253.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1254.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 1254.0 MB

--- Window 500/640: 2024-12-20 05:01:45 to 2024-12-20 07:01:45 ---
Memory before window: 1254.0 MB
  Found 23258 trips in window
  Processing 18939 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1254.1 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1254.2 MB
  Initial memory: 1254.2 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1251.1 MB
  ✅ Generated 3750 feature rows
Memory after window: 1251.1 MB

--- Window 501/640: 2024-12-20 07:01:45 to 2024-12-20 09:01:45 ---
Memory before window: 1251.1 MB
  Found 34712 trips in window
  Processing 25968 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1251.3 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1251.3 MB
  Initial memory: 1251.3 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1244.1 MB
  ✅ Generated 3750 feature rows
Memory after window: 1244.1 MB

--- Window 502/640: 2024-12-20 09:01:45 to 2024-12-20 11:01:45 ---
Memory before window: 1244.1 MB
  Found 35309 trips in window
  Processing 27795 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1236.5 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1236.5 MB
  Initial memory: 1236.5 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1238.5 MB
  ✅ Generated 3750 feature rows
Memory after window: 1238.5 MB

--- Window 503/640: 2024-12-20 11:01:45 to 2024-12-20 13:01:45 ---
Memory before window: 1238.5 MB
  Found 32189 trips in window
  Processing 25853 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1238.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1238.7 MB
  Initial memory: 1238.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1238.8 MB
  ✅ Generated 3750 feature rows
Memory after window: 1238.8 MB

--- Window 504/640: 2024-12-20 13:01:45 to 2024-12-20 15:01:45 ---
Memory before window: 1238.8 MB
  Found 41882 trips in window
  Processing 33982 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1239.1 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1239.3 MB
  Initial memory: 1239.3 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1243.3 MB
  ✅ Generated 3750 feature rows
Memory after window: 1243.3 MB

--- Window 505/640: 2024-12-20 15:01:45 to 2024-12-20 17:01:45 ---
Memory before window: 1243.3 MB
  Found 46001 trips in window
  Processing 36905 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1243.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1243.7 MB
  Initial memory: 1243.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1244.1 MB
  ✅ Generated 3750 feature rows
Memory after window: 1244.1 MB

--- Window 506/640: 2024-12-20 17:01:45 to 2024-12-20 19:01:45 ---
Memory before window: 1244.1 MB
  Found 46761 trips in window
  Processing 37031 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1244.4 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1245.0 MB
  Initial memory: 1245.0 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1245.7 MB
  ✅ Generated 3750 feature rows
Memory after window: 1245.7 MB

--- Window 507/640: 2024-12-20 19:01:45 to 2024-12-20 21:01:45 ---
Memory before window: 1245.7 MB
  Found 40956 trips in window
  Processing 32656 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1246.0 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1246.0 MB
  Initial memory: 1246.0 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1246.3 MB
  ✅ Generated 3750 feature rows
Memory after window: 1246.3 MB

--- Window 508/640: 2024-12-20 21:01:45 to 2024-12-20 23:01:45 ---
Memory before window: 1246.3 MB
  Found 32798 trips in window
  Processing 26799 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1246.6 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1246.6 MB
  Initial memory: 1246.6 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1248.9 MB
  ✅ Generated 3750 feature rows
Memory after window: 1248.9 MB

--- Window 509/640: 2024-12-20 23:01:45 to 2024-12-21 01:01:45 ---
Memory before window: 1248.9 MB
  Found 24780 trips in window
  Processing 20732 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1249.0 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1249.0 MB
  Initial memory: 1249.0 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1249.1 MB
  ✅ Generated 3750 feature rows
Memory after window: 1249.1 MB

--- Window 510/640: 2024-12-21 01:01:45 to 2024-12-21 03:01:45 ---
Memory before window: 1249.1 MB
  Found 17297 trips in window
  Processing 15063 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1249.2 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1249.2 MB
  Initial memory: 1249.2 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1249.3 MB
  ✅ Generated 3750 feature rows
Memory after window: 1249.3 MB

--- Window 511/640: 2024-12-21 03:01:45 to 2024-12-21 05:01:45 ---
Memory before window: 1249.3 MB
  Found 15580 trips in window
  Processing 13471 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1249.4 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1249.4 MB
  Initial memory: 1249.4 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1250.5 MB
  ✅ Generated 3750 feature rows
Memory after window: 1250.5 MB

--- Window 512/640: 2024-12-21 05:01:45 to 2024-12-21 07:01:45 ---
Memory before window: 1250.5 MB
  Found 21495 trips in window
  Processing 17244 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1250.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1250.7 MB
  Initial memory: 1250.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1248.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 1248.0 MB

--- Window 513/640: 2024-12-21 07:01:45 to 2024-12-21 09:01:45 ---
Memory before window: 1248.0 MB
  Found 30095 trips in window
  Processing 22397 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1248.2 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1248.2 MB
  Initial memory: 1248.2 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1248.3 MB
  ✅ Generated 3750 feature rows
Memory after window: 1248.3 MB

--- Window 514/640: 2024-12-21 09:01:45 to 2024-12-21 11:01:45 ---
Memory before window: 1248.3 MB
  Found 38221 trips in window
  Processing 29332 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1248.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1242.3 MB
  Initial memory: 1242.3 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1218.7 MB
  ✅ Generated 3750 feature rows
Memory after window: 1218.7 MB

--- Window 515/640: 2024-12-21 11:01:45 to 2024-12-21 13:01:45 ---
Memory before window: 1218.7 MB
  Found 41874 trips in window
  Processing 33519 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1218.9 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1218.9 MB
  Initial memory: 1218.9 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1219.2 MB
  ✅ Generated 3750 feature rows
Memory after window: 1219.2 MB

--- Window 516/640: 2024-12-21 13:01:45 to 2024-12-21 15:01:45 ---
Memory before window: 1219.2 MB
  Found 43041 trips in window
  Processing 34601 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1219.5 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1219.5 MB
  Initial memory: 1219.5 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1214.4 MB
  ✅ Generated 3750 feature rows
Memory after window: 1214.4 MB

--- Window 517/640: 2024-12-21 15:01:45 to 2024-12-21 17:01:45 ---
Memory before window: 1214.4 MB
  Found 46147 trips in window
  Processing 37056 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1214.8 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1214.8 MB
  Initial memory: 1214.8 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1212.6 MB
  ✅ Generated 3750 feature rows
Memory after window: 1212.6 MB

--- Window 518/640: 2024-12-21 17:01:45 to 2024-12-21 19:01:45 ---
Memory before window: 1212.6 MB
  Found 47537 trips in window
  Processing 37600 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1212.9 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1212.9 MB
  Initial memory: 1212.9 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1212.1 MB
  ✅ Generated 3750 feature rows
Memory after window: 1212.1 MB

--- Window 519/640: 2024-12-21 19:01:45 to 2024-12-21 21:01:45 ---
Memory before window: 1212.1 MB
  Found 40589 trips in window
  Processing 32719 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1213.6 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1213.6 MB
  Initial memory: 1213.6 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1212.9 MB
  ✅ Generated 3750 feature rows
Memory after window: 1212.9 MB

--- Window 520/640: 2024-12-21 21:01:45 to 2024-12-21 23:01:45 ---
Memory before window: 1212.9 MB
  Found 31340 trips in window
  Processing 25689 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1213.3 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1213.3 MB
  Initial memory: 1213.3 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1160.6 MB
  ✅ Generated 3750 feature rows
Memory after window: 1160.6 MB

--- Window 521/640: 2024-12-21 23:01:45 to 2024-12-22 01:01:45 ---
Memory before window: 1160.6 MB
  Found 23393 trips in window
  Processing 19812 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1192.2 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1192.2 MB
  Initial memory: 1192.2 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1192.2 MB
  ✅ Generated 3750 feature rows
Memory after window: 1192.2 MB

--- Window 522/640: 2024-12-22 01:01:45 to 2024-12-22 03:01:45 ---
Memory before window: 1192.2 MB
  Found 16279 trips in window
  Processing 14425 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1192.4 MB
  Memory before neighbor processing: 1192.4 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Initial memory: 1192.4 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1192.5 MB
  ✅ Generated 3750 feature rows
Memory after window: 1192.5 MB

--- Window 523/640: 2024-12-22 03:01:45 to 2024-12-22 05:01:45 ---
Memory before window: 1192.5 MB
  Found 14760 trips in window
  Processing 12846 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1192.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1192.7 MB
  Initial memory: 1192.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1193.9 MB
  ✅ Generated 3750 feature rows
Memory after window: 1193.9 MB

--- Window 524/640: 2024-12-22 05:01:45 to 2024-12-22 07:01:45 ---
Memory before window: 1193.9 MB
  Found 20345 trips in window
  Processing 16697 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1194.4 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1194.5 MB
  Initial memory: 1194.5 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 1195.7 MB
  ✅ Generated 3750 feature rows
Memory after window: 1195.7 MB

--- Window 525/640: 2024-12-22 07:01:45 to 2024-12-22 09:01:45 ---
Memory before window: 1195.7 MB
  Found 28434 trips in window
  Processing 21481 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 1196.4 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 1196.4 MB
  Initial memory: 1196.4 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 821.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 821.0 MB

--- Window 526/640: 2024-12-22 09:01:45 to 2024-12-22 11:01:45 ---
Memory before window: 821.0 MB
  Found 36345 trips in window
  Processing 27638 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 856.3 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 857.3 MB
  Initial memory: 857.3 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 855.6 MB
  ✅ Generated 3750 feature rows
Memory after window: 855.6 MB

--- Window 527/640: 2024-12-22 11:01:45 to 2024-12-22 13:01:45 ---
Memory before window: 855.6 MB
  Found 39643 trips in window
  Processing 31206 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 856.2 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 856.2 MB
  Initial memory: 856.2 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 860.3 MB
  ✅ Generated 3750 feature rows
Memory after window: 860.3 MB

--- Window 528/640: 2024-12-22 13:01:45 to 2024-12-22 15:01:45 ---
Memory before window: 860.3 MB
  Found 42555 trips in window
  Processing 34281 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 861.0 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 862.3 MB
  Initial memory: 862.3 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 870.3 MB
  ✅ Generated 3750 feature rows
Memory after window: 870.3 MB

--- Window 529/640: 2024-12-22 15:01:45 to 2024-12-22 17:01:45 ---
Memory before window: 870.3 MB
  Found 43898 trips in window
  Processing 34645 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 871.5 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 871.5 MB
  Initial memory: 871.5 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 872.7 MB
  ✅ Generated 3750 feature rows
Memory after window: 872.7 MB

--- Window 530/640: 2024-12-22 17:01:45 to 2024-12-22 19:01:45 ---
Memory before window: 872.7 MB
  Found 43201 trips in window
  Processing 33597 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 873.9 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 873.9 MB
  Initial memory: 873.9 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 875.9 MB
  ✅ Generated 3750 feature rows
Memory after window: 875.9 MB

--- Window 531/640: 2024-12-22 19:01:45 to 2024-12-22 21:01:45 ---
Memory before window: 875.9 MB
  Found 36719 trips in window
  Processing 29763 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 876.9 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 876.9 MB
  Initial memory: 876.9 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 878.3 MB
  ✅ Generated 3750 feature rows
Memory after window: 878.3 MB

--- Window 532/640: 2024-12-22 21:01:45 to 2024-12-22 23:01:45 ---
Memory before window: 878.3 MB
  Found 28597 trips in window
  Processing 24058 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 878.8 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 878.8 MB
  Initial memory: 878.8 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 880.2 MB
  ✅ Generated 3750 feature rows
Memory after window: 880.2 MB

--- Window 533/640: 2024-12-22 23:01:45 to 2024-12-23 01:01:45 ---
Memory before window: 880.2 MB
  Found 20020 trips in window
  Processing 17240 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 880.6 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 880.6 MB
  Initial memory: 880.6 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 880.7 MB
  ✅ Generated 3750 feature rows
Memory after window: 880.7 MB

--- Window 534/640: 2024-12-23 01:01:45 to 2024-12-23 03:01:45 ---
Memory before window: 880.7 MB
  Found 13601 trips in window
  Processing 12053 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 880.9 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 880.9 MB
  Initial memory: 880.9 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 881.1 MB
  ✅ Generated 3750 feature rows
Memory after window: 881.1 MB

--- Window 535/640: 2024-12-23 03:01:45 to 2024-12-23 05:01:45 ---
Memory before window: 881.1 MB
  Found 12850 trips in window
  Processing 11019 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 881.5 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 881.5 MB
  Initial memory: 881.5 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 881.8 MB
  ✅ Generated 3750 feature rows
Memory after window: 881.8 MB

--- Window 536/640: 2024-12-23 05:01:45 to 2024-12-23 07:01:45 ---
Memory before window: 881.8 MB
  Found 23968 trips in window
  Processing 18935 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 882.5 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 882.5 MB
  Initial memory: 882.5 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 883.5 MB
  ✅ Generated 3750 feature rows
Memory after window: 883.5 MB

--- Window 537/640: 2024-12-23 07:01:45 to 2024-12-23 09:01:45 ---
Memory before window: 883.5 MB
  Found 34319 trips in window
  Processing 25742 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 884.2 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 884.2 MB
  Initial memory: 884.2 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 884.8 MB
  ✅ Generated 3750 feature rows
Memory after window: 884.8 MB

--- Window 538/640: 2024-12-23 09:01:45 to 2024-12-23 11:01:45 ---
Memory before window: 884.8 MB
  Found 38285 trips in window
  Processing 29119 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 885.6 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 885.7 MB
  Initial memory: 885.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 885.8 MB
  ✅ Generated 3750 feature rows
Memory after window: 885.8 MB

--- Window 539/640: 2024-12-23 11:01:45 to 2024-12-23 13:01:45 ---
Memory before window: 885.8 MB
  Found 39324 trips in window
  Processing 31401 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 886.9 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 886.9 MB
  Initial memory: 886.9 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 888.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 888.0 MB

--- Window 540/640: 2024-12-23 13:01:45 to 2024-12-23 15:01:45 ---
Memory before window: 888.0 MB
  Found 42281 trips in window
  Processing 33944 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 889.0 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 889.0 MB
  Initial memory: 889.0 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 889.8 MB
  ✅ Generated 3750 feature rows
Memory after window: 889.8 MB

--- Window 541/640: 2024-12-23 15:01:45 to 2024-12-23 17:01:45 ---
Memory before window: 889.8 MB
  Found 43818 trips in window
  Processing 34704 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 890.8 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 890.9 MB
  Initial memory: 890.9 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 889.9 MB
  ✅ Generated 3750 feature rows
Memory after window: 889.9 MB

--- Window 542/640: 2024-12-23 17:01:45 to 2024-12-23 19:01:45 ---
Memory before window: 889.9 MB
  Found 42640 trips in window
  Processing 33925 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 890.8 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 890.8 MB
  Initial memory: 890.8 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 827.8 MB
  ✅ Generated 3750 feature rows
Memory after window: 827.8 MB

--- Window 543/640: 2024-12-23 19:01:45 to 2024-12-23 21:01:45 ---
Memory before window: 827.8 MB
  Found 38510 trips in window
  Processing 31590 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 870.6 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 871.0 MB
  Initial memory: 871.0 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 875.2 MB
  ✅ Generated 3750 feature rows
Memory after window: 875.2 MB

--- Window 544/640: 2024-12-23 21:01:45 to 2024-12-23 23:01:45 ---
Memory before window: 875.2 MB
  Found 28691 trips in window
  Processing 24084 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 875.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 876.0 MB
  Initial memory: 876.0 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 878.1 MB
  ✅ Generated 3750 feature rows
Memory after window: 878.1 MB

--- Window 545/640: 2024-12-23 23:01:45 to 2024-12-24 01:01:45 ---
Memory before window: 878.1 MB
  Found 18506 trips in window
  Processing 16132 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 878.6 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 878.7 MB
  Initial memory: 878.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 530.9 MB
  ✅ Generated 3750 feature rows
Memory after window: 531.0 MB

--- Window 546/640: 2024-12-24 01:01:45 to 2024-12-24 03:01:45 ---
Memory before window: 531.0 MB
  Found 12564 trips in window
  Processing 11389 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 564.3 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 559.6 MB
  Initial memory: 559.9 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 362.5 MB
  ✅ Generated 3750 feature rows
Memory after window: 362.5 MB

--- Window 547/640: 2024-12-24 03:01:45 to 2024-12-24 05:01:45 ---
Memory before window: 362.5 MB
  Found 13356 trips in window
  Processing 11574 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 411.5 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 412.4 MB
  Initial memory: 412.4 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 311.6 MB
  ✅ Generated 3750 feature rows
Memory after window: 311.8 MB

--- Window 548/640: 2024-12-24 05:01:45 to 2024-12-24 07:01:45 ---
Memory before window: 311.8 MB
  Found 25188 trips in window
  Processing 20182 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 387.6 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 380.3 MB
  Initial memory: 380.3 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 252.5 MB
  ✅ Generated 3750 feature rows
Memory after window: 252.7 MB

--- Window 549/640: 2024-12-24 07:01:45 to 2024-12-24 09:01:45 ---
Memory before window: 252.7 MB
  Found 34670 trips in window
  Processing 26758 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 402.2 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 404.8 MB
  Initial memory: 404.8 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 418.3 MB
  ✅ Generated 3750 feature rows
Memory after window: 418.3 MB

--- Window 550/640: 2024-12-24 09:01:45 to 2024-12-24 11:01:45 ---
Memory before window: 418.3 MB
  Found 38609 trips in window
  Processing 29581 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 425.5 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 426.3 MB
  Initial memory: 426.3 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 387.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 387.0 MB

--- Window 551/640: 2024-12-24 11:01:45 to 2024-12-24 13:01:45 ---
Memory before window: 387.0 MB
  Found 41067 trips in window
  Processing 33106 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 437.1 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 437.5 MB
  Initial memory: 437.5 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 438.8 MB
  ✅ Generated 3750 feature rows
Memory after window: 438.1 MB

--- Window 552/640: 2024-12-24 13:01:45 to 2024-12-24 15:01:45 ---
Memory before window: 438.1 MB
  Found 42783 trips in window
  Processing 34610 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 441.0 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 441.2 MB
  Initial memory: 441.2 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 444.2 MB
  ✅ Generated 3750 feature rows
Memory after window: 444.2 MB

--- Window 553/640: 2024-12-24 15:01:45 to 2024-12-24 17:01:45 ---
Memory before window: 444.2 MB
  Found 45621 trips in window
  Processing 35780 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 448.2 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 448.6 MB
  Initial memory: 448.6 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 453.2 MB
  ✅ Generated 3750 feature rows
Memory after window: 453.2 MB

--- Window 554/640: 2024-12-24 17:01:45 to 2024-12-24 19:01:45 ---
Memory before window: 453.2 MB
  Found 46230 trips in window
  Processing 36458 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 455.3 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 455.3 MB
  Initial memory: 455.3 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 402.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 398.4 MB

--- Window 555/640: 2024-12-24 19:01:45 to 2024-12-24 21:01:45 ---
Memory before window: 398.4 MB
  Found 40492 trips in window
  Processing 32320 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 429.5 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 233.7 MB
  Initial memory: 233.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 220.2 MB
  ✅ Generated 3750 feature rows
Memory after window: 221.1 MB

--- Window 556/640: 2024-12-24 21:01:45 to 2024-12-24 23:01:45 ---
Memory before window: 221.1 MB
  Found 30822 trips in window
  Processing 25927 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 401.8 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 403.0 MB
  Initial memory: 403.0 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 356.3 MB
  ✅ Generated 3750 feature rows
Memory after window: 356.3 MB

--- Window 557/640: 2024-12-24 23:01:45 to 2024-12-25 01:01:45 ---
Memory before window: 356.3 MB
  Found 20132 trips in window
  Processing 17302 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 399.5 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 400.8 MB
  Initial memory: 400.8 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 418.1 MB
  ✅ Generated 3750 feature rows
Memory after window: 418.1 MB

--- Window 558/640: 2024-12-25 01:01:45 to 2024-12-25 03:01:45 ---
Memory before window: 418.1 MB
  Found 14577 trips in window
  Processing 12941 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 420.1 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 420.4 MB
  Initial memory: 420.4 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 418.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 418.0 MB

--- Window 559/640: 2024-12-25 03:01:45 to 2024-12-25 05:01:45 ---
Memory before window: 418.0 MB
  Found 14465 trips in window
  Processing 12550 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 426.6 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 426.6 MB
  Initial memory: 426.6 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 427.6 MB
  ✅ Generated 3750 feature rows
Memory after window: 427.6 MB

--- Window 560/640: 2024-12-25 05:01:45 to 2024-12-25 07:01:45 ---
Memory before window: 427.6 MB
  Found 25526 trips in window
  Processing 20024 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 437.4 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 437.8 MB
  Initial memory: 437.8 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 438.3 MB
  ✅ Generated 3750 feature rows
Memory after window: 437.7 MB

--- Window 561/640: 2024-12-25 07:01:45 to 2024-12-25 09:01:45 ---
Memory before window: 437.7 MB
  Found 35461 trips in window
  Processing 26500 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 443.2 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 443.4 MB
  Initial memory: 443.4 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 395.7 MB
  ✅ Generated 3750 feature rows
Memory after window: 395.7 MB

--- Window 562/640: 2024-12-25 09:01:45 to 2024-12-25 11:01:45 ---
Memory before window: 395.7 MB
  Found 39062 trips in window
  Processing 30559 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 439.4 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 439.7 MB
  Initial memory: 439.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 190.6 MB
  ✅ Generated 3750 feature rows
Memory after window: 191.6 MB

--- Window 563/640: 2024-12-25 11:01:45 to 2024-12-25 13:01:45 ---
Memory before window: 191.6 MB
  Found 42084 trips in window
  Processing 34011 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 393.9 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 400.0 MB
  Initial memory: 400.2 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 420.2 MB
  ✅ Generated 3750 feature rows
Memory after window: 420.2 MB

--- Window 564/640: 2024-12-25 13:01:45 to 2024-12-25 15:01:45 ---
Memory before window: 420.2 MB
  Found 43634 trips in window
  Processing 35521 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 427.2 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 429.4 MB
  Initial memory: 429.4 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 371.1 MB
  ✅ Generated 3750 feature rows
Memory after window: 371.1 MB

--- Window 565/640: 2024-12-25 15:01:45 to 2024-12-25 17:01:45 ---
Memory before window: 371.1 MB
  Found 47536 trips in window
  Processing 38317 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 422.3 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 422.5 MB
  Initial memory: 422.5 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 434.1 MB
  ✅ Generated 3750 feature rows
Memory after window: 434.1 MB

--- Window 566/640: 2024-12-25 17:01:45 to 2024-12-25 19:01:45 ---
Memory before window: 434.1 MB
  Found 48770 trips in window
  Processing 38684 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 437.0 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 438.5 MB
  Initial memory: 438.5 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 241.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 241.6 MB

--- Window 567/640: 2024-12-25 19:01:45 to 2024-12-25 21:01:45 ---
Memory before window: 241.6 MB
  Found 43505 trips in window
  Processing 35151 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 410.1 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 350.9 MB
  Initial memory: 351.0 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 376.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 376.3 MB

--- Window 568/640: 2024-12-25 21:01:45 to 2024-12-25 23:01:45 ---
Memory before window: 376.3 MB
  Found 33690 trips in window
  Processing 27967 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 426.9 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 427.0 MB
  Initial memory: 427.0 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 432.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 432.0 MB

--- Window 569/640: 2024-12-25 23:01:45 to 2024-12-26 01:01:45 ---
Memory before window: 432.0 MB
  Found 23688 trips in window
  Processing 20312 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 433.6 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 432.3 MB
  Initial memory: 432.3 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 430.5 MB
  ✅ Generated 3750 feature rows
Memory after window: 430.5 MB

--- Window 570/640: 2024-12-26 01:01:45 to 2024-12-26 03:01:45 ---
Memory before window: 430.5 MB
  Found 15722 trips in window
  Processing 13980 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 425.4 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 396.0 MB
  Initial memory: 396.0 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 219.1 MB
  ✅ Generated 3750 feature rows
Memory after window: 219.5 MB

--- Window 571/640: 2024-12-26 03:01:45 to 2024-12-26 05:01:45 ---
Memory before window: 219.5 MB
  Found 14779 trips in window
  Processing 12858 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 379.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 381.1 MB
  Initial memory: 381.1 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 378.3 MB
  ✅ Generated 3750 feature rows
Memory after window: 378.3 MB

--- Window 572/640: 2024-12-26 05:01:45 to 2024-12-26 07:01:45 ---
Memory before window: 378.3 MB
  Found 24085 trips in window
  Processing 19283 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 394.5 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 394.6 MB
  Initial memory: 394.8 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 358.5 MB
  ✅ Generated 3750 feature rows
Memory after window: 358.5 MB

--- Window 573/640: 2024-12-26 07:01:45 to 2024-12-26 09:01:45 ---
Memory before window: 358.5 MB
  Found 31541 trips in window
  Processing 23943 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 412.9 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 413.0 MB
  Initial memory: 413.0 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 369.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 369.0 MB

--- Window 574/640: 2024-12-26 09:01:45 to 2024-12-26 11:01:45 ---
Memory before window: 369.0 MB
  Found 35793 trips in window
  Processing 28088 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 431.3 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 431.7 MB
  Initial memory: 431.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 435.4 MB
  ✅ Generated 3750 feature rows
Memory after window: 435.4 MB

--- Window 575/640: 2024-12-26 11:01:45 to 2024-12-26 13:01:45 ---
Memory before window: 435.4 MB
  Found 39054 trips in window
  Processing 31126 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 438.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 438.8 MB
  Initial memory: 438.8 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 440.8 MB
  ✅ Generated 3750 feature rows
Memory after window: 440.8 MB

--- Window 576/640: 2024-12-26 13:01:45 to 2024-12-26 15:01:45 ---
Memory before window: 440.8 MB
  Found 40807 trips in window
  Processing 33187 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 443.6 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 433.2 MB
  Initial memory: 433.2 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 394.9 MB
  ✅ Generated 3750 feature rows
Memory after window: 394.9 MB

--- Window 577/640: 2024-12-26 15:01:45 to 2024-12-26 17:01:45 ---
Memory before window: 394.9 MB
  Found 42575 trips in window
  Processing 33853 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 441.2 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 442.0 MB
  Initial memory: 442.0 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 355.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 355.3 MB

--- Window 578/640: 2024-12-26 17:01:45 to 2024-12-26 19:01:45 ---
Memory before window: 355.3 MB
  Found 45153 trips in window
  Processing 35753 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 421.1 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 418.5 MB
  Initial memory: 418.5 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 433.5 MB
  ✅ Generated 3750 feature rows
Memory after window: 433.5 MB

--- Window 579/640: 2024-12-26 19:01:45 to 2024-12-26 21:01:45 ---
Memory before window: 433.5 MB
  Found 42214 trips in window
  Processing 34310 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 436.4 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 436.7 MB
  Initial memory: 436.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 438.9 MB
  ✅ Generated 3750 feature rows
Memory after window: 437.7 MB

--- Window 580/640: 2024-12-26 21:01:45 to 2024-12-26 23:01:45 ---
Memory before window: 437.7 MB
  Found 30513 trips in window
  Processing 25763 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 439.4 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 439.9 MB
  Initial memory: 439.9 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 410.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 410.0 MB

--- Window 581/640: 2024-12-26 23:01:45 to 2024-12-27 01:01:45 ---
Memory before window: 410.0 MB
  Found 19973 trips in window
  Processing 17651 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 441.2 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 441.6 MB
  Initial memory: 441.6 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 441.7 MB
  ✅ Generated 3750 feature rows
Memory after window: 441.7 MB

--- Window 582/640: 2024-12-27 01:01:45 to 2024-12-27 03:01:45 ---
Memory before window: 441.7 MB
  Found 14039 trips in window
  Processing 12620 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 442.6 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 442.6 MB
  Initial memory: 442.6 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 443.1 MB
  ✅ Generated 3750 feature rows
Memory after window: 443.1 MB

--- Window 583/640: 2024-12-27 03:01:45 to 2024-12-27 05:01:45 ---
Memory before window: 443.1 MB
  Found 13963 trips in window
  Processing 11954 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 445.3 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 445.3 MB
  Initial memory: 445.3 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 440.2 MB
  ✅ Generated 3750 feature rows
Memory after window: 437.6 MB

--- Window 584/640: 2024-12-27 05:01:45 to 2024-12-27 07:01:45 ---
Memory before window: 437.6 MB
  Found 25260 trips in window
  Processing 20357 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 442.8 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 441.8 MB
  Initial memory: 441.8 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 441.3 MB
  ✅ Generated 3750 feature rows
Memory after window: 441.3 MB

--- Window 585/640: 2024-12-27 07:01:45 to 2024-12-27 09:01:45 ---
Memory before window: 441.3 MB
  Found 34876 trips in window
  Processing 26830 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 443.2 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 443.2 MB
  Initial memory: 443.2 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 448.7 MB
  ✅ Generated 3750 feature rows
Memory after window: 448.7 MB

--- Window 586/640: 2024-12-27 09:01:45 to 2024-12-27 11:01:45 ---
Memory before window: 448.7 MB
  Found 39144 trips in window
  Processing 29988 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 450.5 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 450.5 MB
  Initial memory: 450.5 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 454.8 MB
  ✅ Generated 3750 feature rows
Memory after window: 454.8 MB

--- Window 587/640: 2024-12-27 11:01:45 to 2024-12-27 13:01:45 ---
Memory before window: 454.8 MB
  Found 43432 trips in window
  Processing 33711 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 456.6 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 456.7 MB
  Initial memory: 456.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 458.5 MB
  ✅ Generated 3750 feature rows
Memory after window: 458.5 MB

--- Window 588/640: 2024-12-27 13:01:45 to 2024-12-27 15:01:45 ---
Memory before window: 458.5 MB
  Found 44627 trips in window
  Processing 35550 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 459.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 459.7 MB
  Initial memory: 459.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 452.1 MB
  ✅ Generated 3750 feature rows
Memory after window: 451.8 MB

--- Window 589/640: 2024-12-27 15:01:45 to 2024-12-27 17:01:45 ---
Memory before window: 451.8 MB
  Found 47937 trips in window
  Processing 37820 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 453.5 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 454.7 MB
  Initial memory: 454.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 458.1 MB
  ✅ Generated 3750 feature rows
Memory after window: 458.1 MB

--- Window 590/640: 2024-12-27 17:01:45 to 2024-12-27 19:01:45 ---
Memory before window: 458.1 MB
  Found 49380 trips in window
  Processing 38467 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 459.4 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 459.6 MB
  Initial memory: 459.6 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 469.5 MB
  ✅ Generated 3750 feature rows
Memory after window: 469.5 MB

--- Window 591/640: 2024-12-27 19:01:45 to 2024-12-27 21:01:45 ---
Memory before window: 469.5 MB
  Found 45426 trips in window
  Processing 35945 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 470.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 471.2 MB
  Initial memory: 471.2 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 448.6 MB
  ✅ Generated 3750 feature rows
Memory after window: 448.6 MB

--- Window 592/640: 2024-12-27 21:01:45 to 2024-12-27 23:01:45 ---
Memory before window: 448.6 MB
  Found 35500 trips in window
  Processing 28904 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 471.5 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 471.6 MB
  Initial memory: 471.6 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 473.1 MB
  ✅ Generated 3750 feature rows
Memory after window: 473.1 MB

--- Window 593/640: 2024-12-27 23:01:45 to 2024-12-28 01:01:45 ---
Memory before window: 473.1 MB
  Found 25200 trips in window
  Processing 20906 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 472.8 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 473.2 MB
  Initial memory: 473.2 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 475.4 MB
  ✅ Generated 3750 feature rows
Memory after window: 475.4 MB

--- Window 594/640: 2024-12-28 01:01:45 to 2024-12-28 03:01:45 ---
Memory before window: 475.4 MB
  Found 17916 trips in window
  Processing 15407 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 476.2 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 476.2 MB
  Initial memory: 476.2 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 473.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 473.0 MB

--- Window 595/640: 2024-12-28 03:01:45 to 2024-12-28 05:01:45 ---
Memory before window: 473.0 MB
  Found 15691 trips in window
  Processing 13437 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 473.3 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 473.3 MB
  Initial memory: 473.3 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 475.2 MB
  ✅ Generated 3750 feature rows
Memory after window: 475.2 MB

--- Window 596/640: 2024-12-28 05:01:45 to 2024-12-28 07:01:45 ---
Memory before window: 475.2 MB
  Found 21214 trips in window
  Processing 16820 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 475.6 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 476.0 MB
  Initial memory: 476.0 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 431.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 429.0 MB

--- Window 597/640: 2024-12-28 07:01:45 to 2024-12-28 09:01:45 ---
Memory before window: 429.0 MB
  Found 30532 trips in window
  Processing 22740 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 457.5 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 457.5 MB
  Initial memory: 457.5 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 465.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 465.0 MB

--- Window 598/640: 2024-12-28 09:01:45 to 2024-12-28 11:01:45 ---
Memory before window: 465.0 MB
  Found 38407 trips in window
  Processing 28356 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 465.9 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 463.5 MB
  Initial memory: 463.5 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 445.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 444.9 MB

--- Window 599/640: 2024-12-28 11:01:45 to 2024-12-28 13:01:45 ---
Memory before window: 444.9 MB
  Found 42124 trips in window
  Processing 32913 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 452.2 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 452.3 MB
  Initial memory: 452.3 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 453.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 453.0 MB

--- Window 600/640: 2024-12-28 13:01:45 to 2024-12-28 15:01:45 ---
Memory before window: 453.0 MB
  Found 43625 trips in window
  Processing 34184 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 455.3 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 455.3 MB
  Initial memory: 455.3 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 432.1 MB
  ✅ Generated 3750 feature rows
Memory after window: 432.1 MB

--- Window 601/640: 2024-12-28 15:01:45 to 2024-12-28 17:01:45 ---
Memory before window: 432.1 MB
  Found 46153 trips in window
  Processing 36241 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 454.5 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 454.8 MB
  Initial memory: 454.8 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 460.5 MB
  ✅ Generated 3750 feature rows
Memory after window: 460.5 MB

--- Window 602/640: 2024-12-28 17:01:45 to 2024-12-28 19:01:45 ---
Memory before window: 460.5 MB
  Found 47523 trips in window
  Processing 37228 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 462.4 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 462.5 MB
  Initial memory: 462.5 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 463.5 MB
  ✅ Generated 3750 feature rows
Memory after window: 463.5 MB

--- Window 603/640: 2024-12-28 19:01:45 to 2024-12-28 21:01:45 ---
Memory before window: 463.5 MB
  Found 41077 trips in window
  Processing 32693 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 464.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 464.8 MB
  Initial memory: 464.8 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 469.4 MB
  ✅ Generated 3750 feature rows
Memory after window: 469.4 MB

--- Window 604/640: 2024-12-28 21:01:45 to 2024-12-28 23:01:45 ---
Memory before window: 469.4 MB
  Found 32965 trips in window
  Processing 26879 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 470.2 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 470.2 MB
  Initial memory: 470.2 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 468.8 MB
  ✅ Generated 3750 feature rows
Memory after window: 468.8 MB

--- Window 605/640: 2024-12-28 23:01:45 to 2024-12-29 01:01:45 ---
Memory before window: 468.8 MB
  Found 23026 trips in window
  Processing 19161 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 470.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 470.8 MB
  Initial memory: 470.8 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 461.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 461.0 MB

--- Window 606/640: 2024-12-29 01:01:45 to 2024-12-29 03:01:45 ---
Memory before window: 461.0 MB
  Found 15981 trips in window
  Processing 14154 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 464.1 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 464.4 MB
  Initial memory: 464.4 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 436.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 436.0 MB

--- Window 607/640: 2024-12-29 03:01:45 to 2024-12-29 05:01:45 ---
Memory before window: 436.0 MB
  Found 14493 trips in window
  Processing 12540 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 452.3 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 452.1 MB
  Initial memory: 452.1 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 449.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 446.4 MB

--- Window 608/640: 2024-12-29 05:01:45 to 2024-12-29 07:01:45 ---
Memory before window: 446.4 MB
  Found 19337 trips in window
  Processing 15218 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 454.8 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 454.8 MB
  Initial memory: 454.8 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 458.5 MB
  ✅ Generated 3750 feature rows
Memory after window: 458.5 MB

--- Window 609/640: 2024-12-29 07:01:45 to 2024-12-29 09:01:45 ---
Memory before window: 458.5 MB
  Found 26782 trips in window
  Processing 19893 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 457.2 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 457.5 MB
  Initial memory: 457.5 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 453.6 MB
  ✅ Generated 3750 feature rows
Memory after window: 453.6 MB

--- Window 610/640: 2024-12-29 09:01:45 to 2024-12-29 11:01:45 ---
Memory before window: 453.6 MB
  Found 35015 trips in window
  Processing 25507 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 445.5 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 434.5 MB
  Initial memory: 434.5 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 445.8 MB
  ✅ Generated 3750 feature rows
Memory after window: 445.8 MB

--- Window 611/640: 2024-12-29 11:01:45 to 2024-12-29 13:01:45 ---
Memory before window: 445.8 MB
  Found 38963 trips in window
  Processing 29480 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 463.5 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 459.9 MB
  Initial memory: 459.9 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 453.2 MB
  ✅ Generated 3750 feature rows
Memory after window: 453.2 MB

--- Window 612/640: 2024-12-29 13:01:45 to 2024-12-29 15:01:45 ---
Memory before window: 453.2 MB
  Found 39136 trips in window
  Processing 30478 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 462.6 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 462.6 MB
  Initial memory: 462.6 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 464.4 MB
  ✅ Generated 3750 feature rows
Memory after window: 464.4 MB

--- Window 613/640: 2024-12-29 15:01:45 to 2024-12-29 17:01:45 ---
Memory before window: 464.4 MB
  Found 42332 trips in window
  Processing 33170 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 466.0 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 466.1 MB
  Initial memory: 466.1 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 462.6 MB
  ✅ Generated 3750 feature rows
Memory after window: 462.6 MB

--- Window 614/640: 2024-12-29 17:01:45 to 2024-12-29 19:01:45 ---
Memory before window: 462.6 MB
  Found 42860 trips in window
  Processing 33725 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 466.6 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 466.6 MB
  Initial memory: 466.6 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 466.7 MB
  ✅ Generated 3750 feature rows
Memory after window: 466.7 MB

--- Window 615/640: 2024-12-29 19:01:45 to 2024-12-29 21:01:45 ---
Memory before window: 466.7 MB
  Found 37020 trips in window
  Processing 30127 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 467.5 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 467.8 MB
  Initial memory: 467.8 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 470.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 470.0 MB

--- Window 616/640: 2024-12-29 21:01:45 to 2024-12-29 23:01:45 ---
Memory before window: 470.0 MB
  Found 29422 trips in window
  Processing 24811 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 470.8 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 471.1 MB
  Initial memory: 471.1 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 471.5 MB
  ✅ Generated 3750 feature rows
Memory after window: 471.5 MB

--- Window 617/640: 2024-12-29 23:01:45 to 2024-12-30 01:01:45 ---
Memory before window: 471.5 MB
  Found 20796 trips in window
  Processing 17906 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 472.0 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 472.0 MB
  Initial memory: 472.0 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 455.3 MB
  ✅ Generated 3750 feature rows
Memory after window: 455.3 MB

--- Window 618/640: 2024-12-30 01:01:45 to 2024-12-30 03:01:45 ---
Memory before window: 455.3 MB
  Found 13841 trips in window
  Processing 12277 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 460.3 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 460.3 MB
  Initial memory: 460.3 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 404.8 MB
  ✅ Generated 3750 feature rows
Memory after window: 404.8 MB

--- Window 619/640: 2024-12-30 03:01:45 to 2024-12-30 05:01:45 ---
Memory before window: 404.8 MB
  Found 12891 trips in window
  Processing 11136 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 428.9 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 429.7 MB
  Initial memory: 429.8 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 438.3 MB
  ✅ Generated 3750 feature rows
Memory after window: 438.3 MB

--- Window 620/640: 2024-12-30 05:01:45 to 2024-12-30 07:01:45 ---
Memory before window: 438.3 MB
  Found 18376 trips in window
  Processing 14768 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 441.1 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 441.3 MB
  Initial memory: 441.3 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 443.9 MB
  ✅ Generated 3750 feature rows
Memory after window: 443.9 MB

--- Window 621/640: 2024-12-30 07:01:45 to 2024-12-30 09:01:45 ---
Memory before window: 443.9 MB
  Found 26821 trips in window
  Processing 20123 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 447.0 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 447.0 MB
  Initial memory: 447.0 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 450.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 450.0 MB

--- Window 622/640: 2024-12-30 09:01:45 to 2024-12-30 11:01:45 ---
Memory before window: 450.0 MB
  Found 34709 trips in window
  Processing 25862 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 451.8 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 451.8 MB
  Initial memory: 451.8 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 453.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 453.0 MB

--- Window 623/640: 2024-12-30 11:01:45 to 2024-12-30 13:01:45 ---
Memory before window: 453.0 MB
  Found 39330 trips in window
  Processing 29902 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 454.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 454.8 MB
  Initial memory: 454.8 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 451.7 MB
  ✅ Generated 3750 feature rows
Memory after window: 451.7 MB

--- Window 624/640: 2024-12-30 13:01:45 to 2024-12-30 15:01:45 ---
Memory before window: 451.7 MB
  Found 40575 trips in window
  Processing 31310 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 455.2 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 455.2 MB
  Initial memory: 455.2 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 431.9 MB
  ✅ Generated 3750 feature rows
Memory after window: 431.9 MB

--- Window 625/640: 2024-12-30 15:01:45 to 2024-12-30 17:01:45 ---
Memory before window: 431.9 MB
  Found 43237 trips in window
  Processing 33447 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 448.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 448.7 MB
  Initial memory: 448.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 451.1 MB
  ✅ Generated 3750 feature rows
Memory after window: 451.1 MB

--- Window 626/640: 2024-12-30 17:01:45 to 2024-12-30 19:01:45 ---
Memory before window: 451.1 MB
  Found 42260 trips in window
  Processing 33047 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 457.2 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 457.4 MB
  Initial memory: 457.4 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 461.4 MB
  ✅ Generated 3750 feature rows
Memory after window: 461.4 MB

--- Window 627/640: 2024-12-30 19:01:45 to 2024-12-30 21:01:45 ---
Memory before window: 461.4 MB
  Found 36922 trips in window
  Processing 29237 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 462.4 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 462.4 MB
  Initial memory: 462.4 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 462.3 MB
  ✅ Generated 3750 feature rows
Memory after window: 462.3 MB

--- Window 628/640: 2024-12-30 21:01:45 to 2024-12-30 23:01:45 ---
Memory before window: 462.3 MB
  Found 28699 trips in window
  Processing 23353 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 463.4 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 463.7 MB
  Initial memory: 463.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 463.6 MB
  ✅ Generated 3750 feature rows
Memory after window: 463.6 MB

--- Window 629/640: 2024-12-30 23:01:45 to 2024-12-31 01:01:45 ---
Memory before window: 463.6 MB
  Found 20868 trips in window
  Processing 17523 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 464.1 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 462.2 MB
  Initial memory: 462.2 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 459.6 MB
  ✅ Generated 3750 feature rows
Memory after window: 459.6 MB

--- Window 630/640: 2024-12-31 01:01:45 to 2024-12-31 03:01:45 ---
Memory before window: 459.6 MB
  Found 15139 trips in window
  Processing 13569 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 460.2 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 460.2 MB
  Initial memory: 460.2 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 461.2 MB
  ✅ Generated 3750 feature rows
Memory after window: 461.2 MB

--- Window 631/640: 2024-12-31 03:01:45 to 2024-12-31 05:01:45 ---
Memory before window: 461.2 MB
  Found 13260 trips in window
  Processing 11495 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 461.5 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 461.9 MB
  Initial memory: 461.9 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 439.4 MB
  ✅ Generated 3750 feature rows
Memory after window: 439.4 MB

--- Window 632/640: 2024-12-31 05:01:45 to 2024-12-31 07:01:45 ---
Memory before window: 439.4 MB
  Found 16779 trips in window
  Processing 13582 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 452.9 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 452.9 MB
  Initial memory: 452.9 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 458.2 MB
  ✅ Generated 3750 feature rows
Memory after window: 458.2 MB

--- Window 633/640: 2024-12-31 07:01:45 to 2024-12-31 09:01:45 ---
Memory before window: 458.2 MB
  Found 24389 trips in window
  Processing 18068 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 459.3 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 459.3 MB
  Initial memory: 459.3 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 455.4 MB
  ✅ Generated 3750 feature rows
Memory after window: 455.4 MB

--- Window 634/640: 2024-12-31 09:01:45 to 2024-12-31 11:01:45 ---
Memory before window: 455.4 MB
  Found 33188 trips in window
  Processing 24101 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 459.2 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 459.2 MB
  Initial memory: 459.2 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 464.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 464.0 MB

--- Window 635/640: 2024-12-31 11:01:45 to 2024-12-31 13:01:45 ---
Memory before window: 464.0 MB
  Found 37080 trips in window
  Processing 27356 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 465.1 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 465.1 MB
  Initial memory: 465.1 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 327.2 MB
  ✅ Generated 3750 feature rows
Memory after window: 327.6 MB

--- Window 636/640: 2024-12-31 13:01:45 to 2024-12-31 15:01:45 ---
Memory before window: 327.6 MB
  Found 38391 trips in window
  Processing 29735 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 405.3 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 407.7 MB
  Initial memory: 407.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 303.8 MB
  ✅ Generated 3750 feature rows
Memory after window: 303.8 MB

--- Window 637/640: 2024-12-31 15:01:45 to 2024-12-31 17:01:45 ---
Memory before window: 303.8 MB
  Found 41429 trips in window
  Processing 31246 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 419.9 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 420.2 MB
  Initial memory: 420.2 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 423.9 MB
  ✅ Generated 3750 feature rows
Memory after window: 423.9 MB

--- Window 638/640: 2024-12-31 17:01:45 to 2024-12-31 19:01:45 ---
Memory before window: 423.9 MB
  Found 41594 trips in window
  Processing 32317 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 430.8 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 431.1 MB
  Initial memory: 431.1 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 435.1 MB
  ✅ Generated 3750 feature rows
Memory after window: 435.1 MB

--- Window 639/640: 2024-12-31 19:01:45 to 2024-12-31 21:01:45 ---
Memory before window: 435.1 MB
  Found 38347 trips in window
  Processing 30908 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 437.0 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 437.0 MB
  Initial memory: 437.0 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 434.5 MB
  ✅ Generated 3750 feature rows
Memory after window: 434.5 MB

--- Window 640/640: 2024-12-31 21:01:45 to 2024-12-31 23:01:45 ---
Memory before window: 434.5 MB
  Found 32581 trips in window
  Processing 27289 trips in 150 cells
  Building features with h3_res=7, max_cells=150
  Initial memory: 435.7 MB

/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)
/var/folders/qb/yf4211gs4kv7hy5d5jp7q6bw0000gn/T/ipykernel_2481/1425735835.py:111: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  frame = frame.groupby(group_col, group_keys=False).apply(_per_group)

  Memory before neighbor processing: 435.7 MB
  Initial memory: 435.7 MB
  Processing cell batch 1/5 (30 cells)
  Processing cell batch 2/5 (30 cells)
  Processing cell batch 3/5 (30 cells)
  Processing cell batch 4/5 (30 cells)
  Processing cell batch 5/5 (30 cells)
  Final memory: 436.0 MB
  ✅ Generated 3750 feature rows
Memory after window: 436.0 MB

=== RESULTS ===
Successfully processed 382 windows
Total feature rows: 1394272
Combining results...
Saving to files...
✅ Saved 1394272 feature rows to:
  - /Users/jul/Desktop/uni/Data Analytics/Taxi-Income-Optimizer/PickUP rate/prepared_data/X_features_5min_optimized.csv
  - /Users/jul/Desktop/uni/Data Analytics/Taxi-Income-Optimizer/PickUP rate/prepared_data/y_target_5min_optimized.csv
  - /Users/jul/Desktop/uni/Data Analytics/Taxi-Income-Optimizer/PickUP rate/prepared_data/meta_5min_optimized.csv

: